### ISSUE TITLE
conda update conda (anaconda) doesn't reflect in anaconda-navigator

### ISSUE THREAD

**Issue by pwolter** [ContinuumIO/anaconda-issues#1024]
I just did an "conda update conda" and "conda update anaconda" on terminal on my Mac. I launched the anaconda-navigator and on my environment I see I can filter the "Upgradable" packages. This is a very nice feature, but I just did an update, so why there are still packages need of upgrade?

And, how do I upgrade the filtered upgradable packages in navigator? Wouldn't be nice to have an "Upgrade selected" or "Upgrade all" button/option in navigator?

**Comment by goanpeca** [comment]
Hi @pwolter, thanks for the feedback

> `conda update anaconda`

Will update anaconda to the latest, but anaconda is a meta package, that is it points to a list of packages and versions. 

>This is a very nice feature, but I just did an update, so why there are still packages need of upgrade?

Since the latest anaconda went out a couple of months ago, it is very likely that some of the packages included have newer versions so even if you update anaconda, you might get packages that do not correspond to the latest.

Additional to this, any extra package (not included in the anaconda metapackage) does not update with the command you issued.

>And, how do I upgrade the filtered upgradable packages in navigator?
Wouldn't be nice to have an "Upgrade selected" or "Upgrade all" button/option in navigator?

Upgrade all is a functionality that has been requested and suggested and we are exploring it including it in a newer version of Navigator.

Thanks again :-)
