### ISSUE TITLE
Navigator does not update package

### ISSUE THREAD

**Issue by Mark799** [ContinuumIO/anaconda-issues#10963]
Hello,

I'm trying to update Scipy, it's been busy for an hour now.
I get the message: The following packages will be modified. (but the pop up screen is empty)

Is this normal? Or is there something wrong?

Thanks in advance!

**Comment by csoja** [comment]
If you have a very complicated environment, the solver can take a very, very long time to figure out the solution.  There have been many improvements made in the upcoming release of conda to address that.  You might want to give that version of conda (4.7.1+) in the conda-canary channel a try.  _conda install -c conda-canary conda_   This may be easiest from the command line instead of within Navigator.
