### ISSUE TITLE
Question regarding anaconda on Linux

### ISSUE THREAD

**Issue by afettouhi** [ContinuumIO/anaconda-issues#10988]
I am running Arch Linux and I have just installed anaconda2 via the AUR. Anaconda is installed in `/opt/anaconda2`. I activate anaconda via this command

`source /opt/anaconda2/bin/activate root`

I noticed that I can only install packages as my user if I append the pip install with `--user`. Then the package is installed in 

`$HOME/.local/lib/python2.7/site-packages/`

and the anaconda environment can't see the package unless I add it to the path with export. My question is really how do I add my local packages to path of anaconda? So that they are available when I activate the environment? Or would be better to install anaconda locally in my home directory instead?

**Comment by csoja** [comment]
The power of the Anaconda distribution is in using conda to install and update packages instead of pip.  Are the packages you are looking to install unavailable as conda packages from repo.anaconda.com or conda-forge (https://anaconda.org/conda-forge)?  

Here are a couple of blog posts you might find helpful:
https://www.anaconda.com/understanding-conda-and-pip/
https://www.anaconda.com/using-pip-in-a-conda-environment/

**Comment by afettouhi** [comment]
My question wasn't really in regards to installing packages with either pip or anaconda. My question was more regarding best practice, when the anaconda install is installed in a place that requires root access. Should you just clone the anaconda install to local directory in the home directory of the user or just install the anaconda distribution from scratch as a user?

**Comment by csoja** [comment]
It is probably safest to install from scratch as a user.
