### ISSUE TITLE
CaseInsensitiveFileSystemError error in installing ncurses and creating virital env using conda

### ISSUE THREAD

**Issue by anuragpassi** [ContinuumIO/anaconda-issues#11028]
### Actual Behavior

I am trying to create conda environment using 
conda create -n venf

It should have created an environment called venf. However, all the packages were installed except for ncurses. This is the error I am getting

``CaseInsensitiveFileSystemError: Cannot extract package to a case-insensitive file system.
  package location: /Volumes/export/isn/anurag/.conda/pkgs/ncurses-6.1-he6710b0_1.tar.bz2
  extract location: /Volumes/export/isn/anurag/.conda/pkgs/ncurses-6.1-he6710b0_1``

I have tried to install ncurses using
``conda install -c anaconda ncurses``
But get the same error

Please advise

**Comment by DPeterK** [comment]
I've also just hit this exact bug – is there any solution?

**Comment by msarahan** [comment]
You are using a volume that is not case sensitive.  That leads to problems because the package you are using needs case sensitivity - it has files that are different, but the filenames only differ by capitalization.  You need to figure out why you're on a case insensitive filesystem and what options are available to you (pick a different location, probably).  Windows formatted drives are generally case insensitive.  Linux and macOS are usually case sensitive, but not always.

**Comment by anuragpassi** [comment]
Thank you for clarifying that....!!!

**Comment by glacials** [comment]
Hiya, thanks for the response above! Sorry to necro but I wanted to leave a comment on this part:

> You need to figure out why you're on a case insensitive filesystem and what options are available to you (pick a different location, probably). Windows formatted drives are generally case insensitive. Linux and macOS are usually case sensitive, but not always.

macOS is by default case-insensitive, and AFAIK has always been; to make it case-sensitive you have to reformat your hard drive and explicitly change the filesystem away from the default selection. If you do, many popular programs like Adobe Premier ([source](https://helpx.adobe.com/creative-suite/kb/error-case-sensitive-drives-supported.html)) and Steam ([source](https://support.steampowered.com/kb_article.php?ref=8601-RYPX-5789)) break! For these two reasons most macOS users, I'd guess >99%, don't make the change.

Because of this I believe this incompatibility is preventing ~all macOS users from installing, and ~none of them would perform the proposed workaround of changing their filesystem. Hopefully this helps understand the use case! Thanks for all the hard work 😃

**Comment by mingwandroid** [comment]
> macOS is by default case-insensitive, and AFAIK has always been; to make it case-sensitive you have to reformat your hard drive and explicitly change the filesystem away from the default selection. If you do, many popular programs like Adobe Premier (source) and Steam (source) break! For these two reasons most macOS users, I'd guess >99%, don't make the change.

You can mount a case-sensitive APFS volume inside another non case-sensitive APFS volume. It is very easy and for (what I define) serious work, essential.
