### ISSUE TITLE
Conda update to Spyder 3.5.5 deletes all my already installed packages

### ISSUE THREAD

**Issue by garethwalkom** [ContinuumIO/anaconda-issues#11073]
### Actual Behavior

When I updated my Spyder to version 3.5.5 in the Anaconda Prompt, and then opened Spyder, the following packages needed to be installed again:
- Numpy
- Pandas
- Matplotlib
- Imageio
- Scipy
- Scikit-image

### Expected Behavior

Expected Spyder to have kept all my packages after updating Spyder to 3.5.5

### Steps to Reproduce

1. Open Anaconda Prompt
2. $ conda update spyder
3. $ spyder

##### Anaconda or Miniconda version:

Spyder version: 3.5.5

##### Operating System:
Windows 10

**Comment by 634549** [comment]
Same thing happened to me and I'm unable to use the command prompt (apparently because of the update) to reinstall two essential packages. Disaster!

**Comment by aakhmetz** [comment]
ha, I had the same problem today but regarding some "libtiff" package (looks like the trigger was not really connected to spider package and it was by chance).

**Comment by aakhmetz** [comment]
Look like this is the response https://github.com/conda/conda/issues/8842

**Comment by garethwalkom** [comment]
Thank you @aakhmetz !

`conda install --only-deps anaconda` gave me an error when I reopened Spyder.

`conda install --only-deps anaconda=2019` fixed it for me for now... This changes the version from Spyder 3.5.5 to Spyder 3.3.3.

**Comment by msarahan** [comment]
No, it shouldn't be reoccurring.  Please read https://github.com/conda/conda/issues/8842 more carefully.  We'll be writing up a blog post to explain it, too.  The change in conda 4.7.5 is in how it collects input for the solver.  When packages don't have a parent that is somehow connected to an explicit spec, they are not collected, which effectively prunes them.  The bug is with the anaconda metapackage, "custom" version, which depends only on python.  It eschews the many packages, leaving them orphaned, and that's why they get removed.  We will be publishing updated anaconda metapackages today, but your --only-deps command also makes all of these packages explicitly installed and thus not vulnerable to this issue later.

**Comment by msarahan** [comment]
closing to consolidate at conda/conda#8842
