### ISSUE TITLE
Issue Opening Anaconda

### ISSUE THREAD

**Issue by yrider** [ContinuumIO/anaconda-issues#11098]
### Actual Behavior

I cannot open Anaconda Navigator and have re-installed it and shut down/restarted my desktop numerous times. The following error message appears:

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\yorkr\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\yorkr\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Expected Behavior

Anaconda Navigator should just simply open.

Can anyone help? Thank you!

**Comment by tschuerhaus** [comment]
I have this same error

**Comment by yrider** [comment]
> I have this same error

Hi, 

Someone showed me a solution to this problem so see below:

'It might be something with the directory you're installing it.

1. install Python directly through www.python.org.
2. Download the latest version for Python 3. When installing it, make sure to add it to path, too.
3. After installing it, open your CMD Prompt and run pip install jupyter . It will ask for confirmation, press y to confirm that you want to install Jupyter Notebook.
4. When it's done, at your CMD Prompt window, run jupyter notebook and you'll be able to open Jupyter Notebook as you were using Anaconda Navigator.'

Hope this helps!

**Comment by msarahan** [comment]
That's throwing the baby out with the bath water, but good luck.  I'm pretty sure the navigator error was happening because of a warning message showing up.  The warning message results in navigator not understanding conda's response, leading to your very-hard-to-understand traceback.

The problem originated in libarchive not being loaded because of a lack of PATH information.  It was fixed in recent python-libarchive-c packages.  If anyone comes across this issue, let us know and we can try to help you figure out how to download the new package and put it in place.

**Comment by yrider** [comment]
Hi,

If your method is better can you show me how to download the new package?

Thank you, 

York

**Comment by yrider** [comment]
> That's throwing the baby out with the bath water, but good luck. I'm pretty sure the navigator error was happening because of a warning message showing up. The warning message results in navigator not understanding conda's response, leading to your very-hard-to-understand traceback.
> 
> The problem originated in libarchive not being loaded because of a lack of PATH information. It was fixed in recent python-libarchive-c packages. If anyone comes across this issue, let us know and we can try to help you figure out how to download the new package and put it in place.

Hi,

If your method is better can you show me how to download the new package?

Thank you,

York

**Comment by tschuerhaus** [comment]
That's throwing the baby out with the bath water, but good luck. I'm pretty sure the navigator error was happening because of a warning message showing up. The warning message results in navigator not understanding conda's response, leading to your very-hard-to-understand traceback.

The problem originated in libarchive not being loaded because of a lack of PATH information. It was fixed in recent python-libarchive-c packages. If anyone comes across this issue, let us know and we can try to help you figure out how to download the new package and put it in place.

Hi,

If your method is better can you show me how to download the new package?

Thank you,

Tristan

**Comment by msarahan** [comment]
- Open "anaconda prompt" from your start menu
- run "conda install "conda-build>3.18.3"
- try opening navigator again

**Comment by yrider** [comment]
> * Open "anaconda prompt" from your start menu
> * run "`conda install "conda-build>3.18.3"`"
> * try opening navigator again

Hi, 

I appreciate your quick reply. 

Unfortunately, when I try to run the above an error message appears saying Windows cannot find 'conda'. Can you help with this? 

Thanks again, 

York
