### ISSUE TITLE
missing package: openblas==0.3.5

### ISSUE THREAD

**Issue by yottamoe** [ContinuumIO/anaconda-issues#11126]
### Actual Behavior

I tried to create an environment from a yml file, but it gives me the following error:
ResolvePackageNotFound:
  - libblas==3.8.0=4_openblas
  - openblas=0.3.5
  - liblapacke==3.8.0=4_openblas
  - libblas==3.8.0=4_openblas
  - openblas=0.3.5
  - openblas==0.3.5=h436c29b_1001
  - liblapack==3.8.0=4_openblas
  - libblas==3.8.0=4_openblas
  - openblas=0.3.5
  - libcblas==3.8.0=4_openblas
  - libblas==3.8.0=4_openblas
  - openblas=0.3.5
  - blas==2.4=openblas
  - libblas==3.8.0=4_openblas
  - openblas=0.3.5

I did:
conda search openblas==0.3.5
and the package is not available any more.

##### Anaconda or Miniconda version:

openblas=0.3.5=h436c29b_1001
##### Operating System:
osx-64
##### `conda info`

<details>

```


```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by msarahan** [comment]
Filling out the issue template is not really optional. Your problem appears to be with conda forge packages, but we can't tell because you left out channel information that would show up in the requested template information. You need to take your issue over to the appropriate conda forge feedstock repository.
