### ISSUE TITLE
Suddenly dropping support for many package versions

### ISSUE THREAD

**Issue by kchawla-pi** [ContinuumIO/anaconda-issues#11146]
This is in the default channel.

A few weeks ago, conda==4.7.5 seemed to drop support for Scipy==0.17, & Scikit-Learn==0.18. Attempting to install these specific versions of these packages lead to the error --
`PackagesNotFoundError: The following packages are not available from current channels:`
It broke our CIs. We decided to bump up the minimum versions of Scipy, Scikit-learn to 0.19 . for our package.

Now in conda==4.7.10, there seems to be no support for Scipy==0.19 & Python==3.5 . I m getting the same error as above. Scikit-learn==0.19 is supported.

Is this a glitch? What's going on? Where can I get more information? Is there a place where this is regularly updated, warning users about these changes in advance?

**Comment by msarahan** [comment]
All packages are still available, but conda 4.7 now tries a different index file first: current_repodata.json, instead of repodata.json.  Conda automatically falls back to repodata.json, but you may be seeing a bug in that fallback behavior.  There is one known issue so far: https://github.com/conda/conda/issues/8975

**Comment by kchawla-pi** [comment]
Thanks for the reply.

This is a big problem for us. Short of downloading an older version of conda, what are the workarounds? Is there  a time frame for this to be fixed?

**Comment by kchawla-pi** [comment]
>  There is one known issue so far: conda/conda#8975

Now there are two ;-)

**Comment by msarahan** [comment]
You have not filled out the issue template, nor given us any hint towards why you're seeing a problem.  We have no idea what your issue is, other than a vague symptom.  We have no idea if you're passing the -S flag, or anything.

You can pass `--repodata-fn=repodata.json` to conda to bypass the current_repodata.json.  It will be fixed in the next conda bugfix release, but no, there is no timeframe for that.

**Comment by jjhelmus** [comment]
conda 4.7 removed the `free` channel from the collection of channels searched for by default.  The older version of scipy and scikit-learn are available in this channel and therefore will not be found by default.  If you re-enable the `free` channel using `conda config --set restore_free_channel true`.  

For more information about this change please see the [blog post](https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/) on the topic.
