### ISSUE TITLE
Add Qt / PyQt5 for 5.10+

### ISSUE THREAD

**Issue by leofang** [ContinuumIO/anaconda-issues#11183]
This is a follow-up of #9124. Now v5.13 of Qt/PyQt is already out, but on Anaconda still stays at v5.9. Is it possible to provide packages with newer versions?

**Comment by msarahan** [comment]
5.9 took us probably at least a combined man-month to accomplish.  A lot of this was because we tried to support VS2008, which 5.9 definitely did not.  Yes, it is possible to provide newer packages, but without a pressing need (like a customer demanding and paying us to update rstudio), it is hard to undertake with the current resources that we have available.  If you would like to help, the best way is to contribute to the community effort at https://github.com/conda-forge/qt-feedstock/pull/110

**Comment by leofang** [comment]
Thank you. I didn't know building Qt is such a painful experience. I'll follow up with that PR.

**Comment by leofang** [comment]
Closing this one in favor of conda-forge/pyqt-feedstock#58.

**Comment by BrenBarn** [comment]
I know nothing about the gnarly details of getting these builds to work, but given that it eventually was made to work in conda-forge, is there any way to leverage that for the main anaconda channels?  Or is it too intertwined with other dependencies in conda-forge?

**Comment by mingwandroid** [comment]
I am the most active maintainer of the Qt recipe which is shared between conda-forge and Anaconda Distribution.

AD hasn't had time to update beyond 5.9 yet. There's more to it than the package itself, there are dependencies to worry about.

But please you shouldn't comment in closed issues (nor should I).
