### ISSUE TITLE
Test Anaconda installations into home directory with spaces and unicode

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#1130]
Anaconda 2 and Anaconda 3 installations should be tested on Windows, Mac, and Linux into home directories with spaces and unicode characters in their name.  If we know in advance that this will definitely not work then we should warn and suggest an alternative before proceeding.  Or figure out how to modify the installation process so it does work properly.  See Oct 1st 2016 Anaconda ML thread for user where even base installation failed (not just Navigator operation).

Related to #1029

**Comment by AHardReset** [comment]
Hi! few days ago I tried to install Anaconda 2.7 in windows 10, but when the install almost finish an error appears:
![bandicam 2016-09-30 18-23-41-507](https://cloud.githubusercontent.com/assets/22583153/19026400/4c614670-88da-11e6-999c-7498a3568778.jpg)

This happen because my username have an non ascii characters (in this case ó´´ from Aarón)
I verified this when I opened the CMD (Windows + R, then CMD and enter) and my personal folder appears like this (C:/users/Aarón)
so for some reason python have problems with this.

The community brings help as Batman will and offer me some solutions:

1. Install Anaconda 3 (Not was able to me, I need to learn python 2 because is a specification for the project)

2. Install in C:/ (Not worked to me, I don't know what, the same error appears, windows... -_-)
3. Create a new admin-user in windows with only anscii characters

I do the third option and works.

Thanks for the support! Grettings from Mexico

======ESPAÑOL======SPANISH======

Hola! hace unos días intente instalar Anaconda 2.7 en Windows 10, pero cuando la instalación casi termina un error aparece:
Esto pasa porque mi nombre de usuario tiene un carácter no ancii (en este caso 'ó' de Aarón)
Verifique esto cuando abrí el CMD (Windows + R después CMD y enter) y mi carpeta personal aparece como esto (C:/users/Aarón)
así que por alguna razón python tiene problemas con esto.

La comunidad me brindo ayuda como Batman lo haría y me ofreció algunas soluciones:
1. Instalar anaconda 3 (No fue apta para mi, necesito aprender python 2 porque es una especificación para el proyecto)
2. Instalar en C:/ (No funcionó para mí, no se porque, el mismo error apareció, windows... -_-)
3. Crear un nuevo usuario administrador en windows con solo carácteres anscii

Hice la tercer opción y funciono.

Gracias por el soporte! Saludos desde México

======SPECIAL THANKS======
This users help me, I would never know the problem:
@ijstokes 
@msarahan

**Comment by ijstokes** [comment]
Here is the link to the Anaconda ML thread: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/zTQQ0NqqIvk

**Comment by mingwandroid** [comment]
Hi @ijstokes, we definitely need to do better. Here are my thoughts.

Unicode: With Python3 this should be OK, but with Python2 I wouldn't allow this on Windows. From past investigations, the C code in Python2 uses the ASCII variant of the Win32 API instead of the wide variant. A problem here is that you could install Miniconda3 and then create an env. with Python2 and then things will start to fail badly.

Spaces: I would caution against this on all systems. We'd be playing whack-a-mole with bugs over all of our packages. A good example is GNU make. It cannot (without extensive ugly hoop jumping) handle spaces. The meta make systems (Autotools and CMake) don't jump those hoops when targeting GNU make. Passing parameters to most shell scripts will go wrong. Scripts that use `program "$PREFIX"` will be fine, but those that just use `program $PREFIX` will not. In the latter case, program will see multiple single-word arguments.

I'd be happy to see some up-front strong warnings or even better, flat-out refusal to install to paths with spaces or unicode.

**Comment by ijstokes** [comment]
@csoja we've got a good concrete proposal from @mingwandroid for how we should proceed with enhancements to the installer, and probably also carry-over behavior for `conda` and *Navigator* when dealing with environment creation.

**Comment by ijstokes** [comment]
@MulticastMatt I'm not sure who is managing the testing teams and their testing protocol, but I think we have some confirmation that this is an issue we need to test for.

**Comment by csoja** [comment]
@ijstokes we've got this on the list for Anaconda Distribution v4.3.
