### ISSUE TITLE
install pymatgen through anaconda2

### ISSUE THREAD

**Issue by jxzhu** [ContinuumIO/anaconda-issues#11335]
##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by jxzhu** [comment]
I am new to this. How shall I fill out the form?

Thanks,

Jianxin

**Comment by csoja** [comment]
@jxzhu you need to submit the relevant information in the body of the issue (in the "write/preview" section)  There is some text in that section to get you started, and to give you a skeleton of the information required to enable someone to help you with your issue.  
i.e. Where it says "Actual Behavior" "Expected Behavior" etc.  If you are still confused, you can probably find additional information on issues and how they work in the Github documentation.
