### ISSUE TITLE
oracle-instantclient not available for Mac

### ISSUE THREAD

**Issue by michaelaye** [ContinuumIO/anaconda-issues#11383]
This link:

https://anaconda.org/anaconda/oracle-instantclient

is offering a package for the oracle-instantclient but it is missing the Mac version.

If you could provide me with your conda recipe, I could add the Mac client myself, if you don't have the capacity to do it yourself. I would need your recipe to follow the pattern for how to distribute binary libraries, which I never did before. I only built pure Python conda packages based on pypi layout.

**Comment by msarahan** [comment]
We don't maintain a recipe. We no longer provide those packages due to licensing concerns. The fact that they are on the anaconda channel is a mirroring bug. They are not on any repo.anaconda.com channel.

You might find this interesting: https://enterprise-docs.anaconda.com/en/latest/data-science-workflows/data/instantclient.html
