### ISSUE TITLE
cv2 

### ISSUE THREAD

**Issue by bassemkabesh** [ContinuumIO/anaconda-issues#11405]
### Actual Behavior

When I try to call the cv2 lib on python, I get the error (ImportError: DLL load failed: The specified module could not be found.)
cv2 is in the directory I have checked.

Yet here I am. 
I am supposed to use the cv2 module for image analysis. 

### Expected Behavior

it is supposed to confirm it has installed like the others 

### Steps to Reproduce

when I try to install the lib I get this error (ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2)
I tried yesterday to install the lib through conda shell, I had a problem with the hdf5 which I removed and re-installed then I used conda install and downloaded OpenCV which said it is successfully installed. 

##### Anaconda or Miniconda version:
NA

##### Operating System:
Windows 10
##### `conda info`

NA 
i am trying to import the library which i already installed via conda 
<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by csoja** [comment]
The information requested in the issue template is critical in order to be able to even begin to help with a problem like this.
If it is a DLL conflict with another application you have installed, this troubleshooting section might be of help: https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed
