### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MananDhunna** [ContinuumIO/anaconda-issues#1140]
Anaconda Navigator Update error:

/Users/manandhunna/anaconda/bin/python /Users/manandhunna/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.1: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.1*
  - orange3 -> pyqt 4.*
Use "conda info <package>" to see the dependencies for each package.

{'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386', 'version': '1.2.1', 'pyqt': '4.11.4', 'qt': '4.8.7', 'platform': 'osx-64', 'conda': '4.2.9', 'python': '3.5.2', 'language': 'en'}

**Comment by goanpeca** [comment]
Hi @Maggie-M due to recent changes with the Qt library (version5 is now available and the default for the latest anaconda distribution), Navigator and Orange are not compatible as Orange does not provide (yet) a Qt5 compatible versions.

You can update Anaconda to the latest by typing on the command line

`conda update anaconda`

And if you need to use orange, you can install into a new environment (different from root)

Cheers
