### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AlbinB** [ContinuumIO/anaconda-issues#1143]
Anaconda Navigator Update error:

/Users/albin/anaconda/bin/python /Users/albin/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.1: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.3.1*
Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'python': '3.5.1', 'conda': '4.2.9', 'version': '1.2.1', 'qt': '4.8.7', 'platform': 'osx-64', 'language': 'en', 'os': 'Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386'}

**Comment by freyreeste** [comment]
Hi

I cannot neither open Anaconda Cloud by double click on 
![anaconda navigator issue 20161008](https://cloud.githubusercontent.com/assets/18019518/19215247/115180b0-8d6f-11e6-9039-36c25ec50db7.jpg)
the icon nor by using the anaconda-navigator comand. Enclosed is a print screen of the error shown. I would be grateful if you can help me to solve this issue.

**Comment by goanpeca** [comment]
Hi @freyreeste due to recent changes with the Qt library (version5 is now available and the default for the latest anaconda distribution), Navigator and Orange are not compatible as Orange does not provide (yet) a Qt5 compatible versions.

So I suggest you do the following, on the command prompt type

`conda remove orange-app`  # Depending on which one you have installed
`conda remove orange2`  # Depending on which one you have installed
`conda remove orange3`  # Depending on which one you have installed

The you should make sure the latest navigator is installed with the correct qt and pyqt bindings
`conda install anaconda-navigator pyqt=5 qt=5`  # Depending on which one you have installed

Or even better you can update Anaconda to the latest by typing on the command line

`conda update anaconda`

If you need to use orange, you can install into a new environment (different from root)

Cheers
