### ISSUE TITLE
wrong pinning of qt in pyqt 4.11.4-py35_6

### ISSUE THREAD

**Issue by jschueller** [ContinuumIO/anaconda-issues#1164]
hi,
it seems pyqt 4.11.4-py35_6 from defaults overrides pyqt from conda-forge but does not properly pin qt 4 so qt 5.6 gets pulled and a matplotlib import fails:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.8123/job/qsqd3y5kblho068p
(https://github.com/conda-forge/staged-recipes/pull/1727)

**Comment by jakirkham** [comment]
Copying @ccordoba12 and @ocefpaf as they have been following the Qt situation more closely.

**Comment by ccordoba12** [comment]
Why are you using build 6 when 7 is the last one?

**Comment by jschueller** [comment]
I did not specify build 7...

**Comment by jschueller** [comment]
retried, build 7 doesn't get pulled:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.8147/job/sthsh78x3u082007

**Comment by ocefpaf** [comment]
@ccordoba12 in `conda-forge` pinnings I tied `pyqt  4.11.*` to `qt 4.8.*` everywhere I could to avoid getting `qt 5.*` but it seems that some of `defaults` `pyqt  4.11.*` are still OK with `qt 5`.

One way to fix this would be to over-specify `qt 4` in all feedstocks that uses `pyqt  4.11.*` (because pinning `pyqt` in conda-forge won't work as we do not have `qt` for all platform in `conda-forge` and we do rely on `defaults`). I do not like that solution but doing that in `matplotlib`, for example, will solve @jschueller issue here.

Another fix, that I do prefer, is to get a `conda-forge` version of  `qt` built and upload to the channel manually. @jschueller for that I would like to point you to https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5 and ask you to show your support there.

PS: IMO there is another bug in play here. Conda should never catch an lower build number as higher build number always represent a fix and for the same version. Lower build numbers are only for reproducibility's sake and not for use in production!

**Comment by jschueller** [comment]
I still think pyqt from defaults is just not pinning qt 4.

**Comment by ocefpaf** [comment]
> I still think pyqt from defaults is just not pinning qt 4.

@jschueller build number `7` of `pyqt` does seems to be properly pinned to `qt 4`. See the json info from https://anaconda.org/anaconda/pyqt/4.11.4/download/win-64/pyqt-4.11.4-py35_7.tar.bz2 for example.

So the issue is IMO the bug I mentioned above. And, since we cannot fix that as that is not considered a bug, we must choose a way to workaround it.

**Comment by goanpeca** [comment]
There is no way for conda to know the meaning of build numbers for packages with the same name and a different amount of build numbers in different channels. So a higher build number in default does not mean a better package than a lower build number i conda forge

**Comment by jschueller** [comment]
ok, but then the question is why did conda pick 4.11.4-py35_6 instead of 4.11.4-py35_7 ?
could it be a mirror issue or something ?

**Comment by ocefpaf** [comment]
> There is no way for conda to know the meaning of build numbers for packages with the same name and a different amount of build numbers in different channels.

That is fine and the channel preference takes care of it.

> ok, but then the question is why did conda pick 4.11.4-py35_6 instead of 4.11.4-py35_7 of that same channel ?

That is the issue and `conda` is known to do that. I won't mention the many issues where I raised that as that solver behavior is explained to me as a feature and not a bug... Conda is trying to maximize the versions installed and goes for a lower build number to do that as that build number is unpinned and "easy" to satisfy the solver.

**Comment by jschueller** [comment]
if conda goes for the lower build number how could package updates be taken into account ? that makes no sense ???

**Comment by mingwandroid** [comment]
You can inspect the pinning here:
http://repo.continuum.io/pkgs/free/win-64/repodata.json

You'll see:
```
    "pyqt-4.11.4-py35_7.tar.bz2": {
      "build": "py35_7",
      "build_number": 7,
      "date": "2016-07-14",
      "depends": [
        "python 3.5*",
        "qt 4.8.*",
        "sip 4.18"
      ],
      "license": "Commercial, GPLv2, GPLv3",
      "license_family": "GPL3",
      "md5": "66eafbd5b0b5ab3d268d7b6e4c47c03c",
      "name": "pyqt",
      "requires": [],
      "size": 3983388,
      "version": "4.11.4"
    },
```
But as @ccordoba12 pointed out, the problem is you are using build 6 instead of 7 (for some reason). Build 6 pinning is indeed broken and will happily pull in qt 5.6.0:
```
    "pyqt-4.11.4-py35_6.tar.bz2": {
      "build": "py35_6",
      "build_number": 6,
      "date": "2016-06-15",
      "depends": [
        "python 3.5*",
        "qt >=4.8.7",
        "sip >=4.16.4"
      ],
      "license": "Commercial, GPLv2, GPLv3",
      "license_family": "GPL3",
      "md5": "10635ee2337563dfe0a4feadf22c6d8f",
      "name": "pyqt",
      "requires": [],
      "size": 4031024,
      "version": "4.11.4"
    },
```

**Comment by ocefpaf** [comment]
>  the problem is you are using build 6 instead of 7 

by `you`  you mean `conda`, right :wink: 

See https://github.com/ContinuumIO/anaconda-issues/issues/1164#issuecomment-254507648 , https://github.com/ContinuumIO/anaconda-issues/issues/1164#issuecomment-254453691 , and https://github.com/ContinuumIO/anaconda-issues/issues/1164#issuecomment-254506765

**Comment by mingwandroid** [comment]
Right. I actually wrote my comment hours ago and forgot to send it then didn't edit that part, but I just wanted to show where the numbers can be investigated for future reference.

**Comment by jakirkham** [comment]
cc @astrofrog
