### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by michaelgracie** [ContinuumIO/anaconda-issues#1191]
Anaconda Navigator Update error:

/Users/XXXXXXXX/anaconda/bin/python /Users/XXXXXXXX/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.3.2: UnsatisfiableError: The following specifications were found to be in conflict:
- anaconda-navigator 1.3.2*
- orange3 -> pyqt 4.*
  Use "conda info <package>" to see the dependencies for each package.

{'pyqt': '4.11.4', 'python': '3.5.2', 'version': '1.2.1', 'conda': '4.2.11', 'os': 'Darwin;16.1.0;Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64;x86_64;i386', 'platform': 'osx-64', 'qt': '4.8.7', 'language': 'en'}

**Comment by goanpeca** [comment]
Hi @michaelgracie due to recent changes with the Qt library (version5 is now available and the default for the latest anaconda distribution), Navigator and Orange are not compatible as Orange does not provide (yet) a Qt5 compatible versions.

So I suggest you do the following, on the command prompt type

`conda remove orange-app`  # Depending on which one you have installed
`conda remove orange2`  # Depending on which one you have installed
`conda remove orange3`  # Depending on which one you have installed

The you should make sure the latest navigator is installed with the correct qt and pyqt bindings
`conda install anaconda-navigator=pyqt=5 qt=5`

Or even better you can update Anaconda to the latest by typing on the command line

`conda update anaconda`

If you need to use orange, you can install into a new environment (different from root)

Cheers

**Comment by michaelgracie** [comment]
Thank you kindly.  Have a great day.

MG
