### ISSUE TITLE
package request - Feature-engine

### ISSUE THREAD

**Issue by solegalli** [ContinuumIO/anaconda-issues#11958]
Hello. I would like to suggest introducing th package **Feature-engine** for feature engineering for machine learning in the anaconda distribution:

https://pypi.org/project/feature-engine/
https://feature-engine.readthedocs.io/en/latest/

**Examples of its functionality can also be found in the following blogs:**
https://www.trainindata.com/post/feature-engine-a-new-open-source-python-package-for-feature-engineering
https://www.trainindata.com/post/feature-engineering-python-libraries-comparisons

I am the package creator and maintainer. I could try to help, if you point me to templates on how I could automate build and upload using circleci from the circleci config in the github repo?

Thank you!

**Comment by csoja** [comment]
Are you aware of conda-forge? https://conda-forge.org/  Having your package successfully building and available on the conda-forge channel is a good first step to getting a package into repo.anaconda.com

**Comment by solegalli** [comment]
Yes, I checked conda-forge yesterday before submitting an issue here. I didn't find it super straightforward to use, i.e., I didn't find a series of steps to package and upload a package from PyPi or a github repo, or a template, for submitting new packages. 

My idea would be, the same way I have set up continuous integration so that any update to Feature-engine is immediately packaged an uploaded to PyPi, I would like to have a config or setup so that it is packaged and uploaded to anaconda as well, ideally from circleci. So I was wondering, if you could help me with a template, or a website with instructions to do this?

**Comment by csoja** [comment]
anaconda is not PyPI.  conda-forge is a very good option for what you want to do.  The information you are looking for in order to add your package to conda-forge is here: https://conda-forge.org/#add_recipe
However, if you want someone to be able to easily install a conda package you've already built using conda, you could also create your own channel on anaconda.org and upload the packages there.  Then someone would just need to conda install -c your_channel_name_here your_package_name_here to install it into their conda environment.  Documentation: https://docs.anaconda.com/anaconda-cloud/user-guide/howto/#build-packages

**Comment by solegalli** [comment]
@csoja thanks, now got the handle of it. Made a PR to conda-forge. I think we can close this issue. Thanks a lot!
