### ISSUE TITLE
build python with --enable-optimizations and --with-lto for improved performance

### ISSUE THREAD

**Issue by brihh** [ContinuumIO/anaconda-issues#11963]
The python included in the Anaconda releases isn't (apparently) built with python --enable-optimizations and --with-lto flags.
```
(base) [bri_conda@nn ~]$ python -VVV
Python 3.8.1 (default, Jan  8 2020, 21:51:46) 
[GCC 7.3.0]
(base) [bri_conda@nn ~]$ python -c "import sysconfig; print(sysconfig.get_config_vars('CONFIG_ARGS'));"
["'--enable-shared' '--enable-ipv6' '--with-ensurepip=no' '--prefix=/home/bri_conda/anaconda3' '--with-tcltk-includes=-I/home/bri_conda/anaconda3/include' '--with-tcltk-libs=-L/home/bri_conda/anaconda3/lib -ltcl -ltk' 'CPPFLAGS=-I/home/bri_conda/anaconda3/include' 'LDFLAGS=-L/home/bri_conda/anaconda3/lib -Wl,-rpath=/home/bri_conda/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/' 'PKG_CONFIG_PATH=/home/bri_conda/anaconda3/lib/pkgconfig'"]
```

i tried to do a local build of the package with the build.sh recipe and it does 2 builds - a static and a shared. the static does the enable-optimizations but the shared doesn't. but then looking at the final build results, the static is not optimized. i used the conda debug, and again, that shows the --enable-optimizations on the build:
```
(/home/bri_conda/anaconda3/conda-bld/debug_1592339038783/_build_env) [bri_conda@p215n51 work]$ ../_h_env/bin/python3.8 -c "import sysconfig; print(sysconfig.get_config_vars('CONFIG_ARGS'));"
["'--prefix=/opt/anaconda1anaconda2anaconda3' '--build=powerpc64le-conda_cos7-linux-gnu' '--host=powerpc64le-conda_cos7-linux-gnu' '--enable-ipv6' '--with-ensurepip=no' '--with-computed-gotos' '--with-system-ffi' '--enable-loadable-sqlite-extensions' '--with-tcltk-includes=-I/opt/anaconda1anaconda2anaconda3/include' '--with-tcltk-libs=-L/opt/anaconda1anaconda2anaconda3/lib -ltcl -ltk' '--enable-optimizations' '--with-lto' '--disable-shared' 'build_alias=powerpc64le-conda_cos7-linux-gnu' 'host_alias=powerpc64le-conda_cos7-linux-gnu' 'CC=powerpc64le-conda_cos7-linux-gnu-gcc' 'CFLAGS=-mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -fdebug-prefix-map=/opt/conda/conda-bld/python_1512347718438/work=/usr/local/src/conda/python-3.8.3 -fdebug-prefix-map=/opt/anaconda1anaconda2anaconda3=/usr/local/src/conda-prefix -pipe     ' 'LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/opt/anaconda1anaconda2anaconda3/lib -L/opt/anaconda1anaconda2anaconda3/lib' 'CPPFLAGS=-D_FORTIFY_SOURCE=2 -O2 -I/opt/anaconda1anaconda2anaconda3/include' 'CPP=/opt/anaconda1anaconda2anaconda3/bin/powerpc64le-conda_cos7-linux-gnu-cpp' 'PKG_CONFIG_PATH=/opt/anaconda1anaconda2anaconda3/lib/pkgconfig'"]
```
but then something after that must throw that away? or is that not what's used on the official build? or .. ?

looking back, i found this issue:
https://github.com/ContinuumIO/anaconda-issues/issues/423
which seems to say that pgo and lto (which is what --enable-optimizations and --with-lto do in the python makefile) should be 'on' for all platforms. but .. ?

##### `conda info`
```
     active environment : base
    active env location : /home/bri_conda/anaconda3
            shell level : 1
       user config file : /home/bri_conda/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.1.final.0
       virtual packages : __glibc=2.28
       base environment : /home/bri_conda/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-ppc64le
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-ppc64le
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bri_conda/anaconda3/pkgs
                          /home/bri_conda/.conda/pkgs
       envs directories : /home/bri_conda/anaconda3/envs
                          /home/bri_conda/.conda/envs
               platform : linux-ppc64le
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.8.1 Linux/4.18.0-193.el8.ppc64le rhel/8.2 glibc/2.28
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by brihh** [comment]
@jjhelmus jason furmanek mentioned that you might be able to help here. thoughts?

**Comment by brihh** [comment]
anyone have thoughts? seeing the same thing?

**Comment by mingwandroid** [comment]
sysconfig doesn't give the flags that python was compiled with necessarily. It gives a dynamic version of the values contained in the config files (the makefile and the sysconfig python file). The CFLAGS we set in distutils for extension modules (esp. when using anaconda compilers) are optimized CFLAGS though. We even force exclude debugging info for size reasons.

The statically linked interpreter and all of its extension modules are built with optimizations, lto and pgo on all systems. It has been this way for a few years now.. The lto is not retained in the libraries nor executables because that bakes compiler implemention into elf files and that's not portable.

So lto is not used to compile downstream python extension modules because without the python lto info it's not usually very effective. If course any project that wants to could enable lto flags if they know it to be safe and useful for them.

I don't know about the shared library, optimisations wise. If you want to look at fixing that then please go ahead. I don't use it but it's important for some embedding scenarios.

Btw I added pyperfornance and pyperf packages to defaults recently in case you want to verify the performance of anaconda python against any other distro package or build. I haven't done this for a while but when I did we were in general doing just fine. I do compare anaconda python with old anaconda python more often and would hope to have spotted any serious regressions in speed. I am more than happy to be proved wrong in any if the statements above add its a chance to improve things!

Thanks.

**Comment by brihh** [comment]
Greetings.

Thanks for the detailed explanations! I don't have that much visibility into the build and testing, so I don't have any way to prove you wrong!! I trust that you've got the right facts!

thx! .bri.
