### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aditya98-ss** [ContinuumIO/anaconda-issues#12004]
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;x86;x86 Family 6 Model 37 Stepping 2, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by cjmartian** [comment]
Looks like you may be missing write permissions on `C:\ProgramData\Anaconda3`

I might be able to help more if you could fill out the template.



### Actual Behavior





### Expected Behavior





### Steps to Reproduce





##### Anaconda or Miniconda version:



##### Operating System:

##### `conda info`


<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`


<details>

```
PASTE OUTPUT HERE:

```

</details>
