### ISSUE TITLE
Spyder undate

### ISSUE THREAD

**Issue by srvmig** [ContinuumIO/anaconda-issues#12456]
Anaconda distribution doesn't have the new Spyder update. Has anaconda discontinued the Spyder update??

**Comment by Dan-Patterson** [comment]
[related issue](https://github.com/ContinuumIO/anaconda-issues/issues/12429)
There hasn't been a major update to the Anaconda channel since April 22... something must be holding up the pipeline.
There are alternate install options on the Spyder website in the interim

**Comment by awwad** [comment]
It seems like anaconda.**org**/main and anaconda.**org**/anaconda are a bit out of date.  https://repo.anaconda.com/pkgs/main/ should be up to date.  As for Spyder, there's a 5.0.0 release there, though I think there were a lot of issues fixed in .1, .2, and .3, and I don't think there's a build up for those yet.
