### ISSUE TITLE
Anaconda3 and Miniconda3 local privilege escalation vulnerability CVE-2022-26526

### ISSUE THREAD

**Issue by martinsohn** [ContinuumIO/anaconda-issues#12869]
This security issue is already known by Anaconda developers via private communication since December 16, 2021, but has not been resolved. My motivation for opening this issue is to make users aware of this risk.

In a certain installation scenario, Anaconda3 and Miniconda3 will introduce a local privilege escalation vulnerability to the system. If the applications is installed with this scenario on systems with non-administrative users, the non-administrative users may be able to elevate their privileges to be an administrator, or SYSTEM.

More information, **and possible mitigations**, can be found at: https://improsec.com/tech-blog/privilege-escalation-vulnerability-in-anaconda3-and-miniconda3

### Steps to Reproduce

Install Anaconda3 or Miniconda3 with the options  ”_Install for: All Users (required admin privileged)_” and ”_Add Anaconda3 to the system PATH environment variable_”.

##### Anaconda or Miniconda version:

- Anaconda3 version 2021.11.0.0 and likely prior versions
- Miniconda3 version 11.0.0.0 and prior versions, at least since 10.3.0.0

##### Operating System:

- Windows desktop
- Windows Server

**Comment by jedfrechette** [comment]
Is this issue still being worked on?

There is a notice in the current (4.14) Windows installation docs saying that All User installations have been disabled since version 4.12.0, but I can't find any discussion of that change in the release notes for 4.12.

The release notes for 4.14 do seem to include a mention of this issue, but only with regard to the addition of the notice mentioned above to the installation docs. That item in the release notes does link to "security concerns", but the github page it links to gives a 404 error. Is that link supposed to point to this issue or is there another discussion of the issue happening somewhere else that I haven't been able to find?

Secure multi-user installations are important in some environments so it would be helpful to know if Anaconda is working towards a better fix for this issue or if the planned solution is to just stop supporting multiuser installations on Windows?

**Comment by martinsohn** [comment]
@jedfrechette Received yesterday (almost a year since reporting) from support@anaconda.com:
_The vulnerabilities were mitigated in Anaconda 2022.05 and Miniconda3 4.12.0; all versions after those should also contain the fixes._

Looking at Anaconda 2022.05 change notes and the CVE is mentioned: https://www.anaconda.com/blog/new-release-anaconda-distribution-now-supporting-m1

I will not verify if the patch mitigates the risk. TBH I am disappointed by the lack of communication from Anaconda. I will keep this issue open until they close it.

**Comment by pseudoyim** [comment]
Apologies for the delay @martinsohn. We've described how we addressed CVE-2022-26526 in the [blog post](https://www.anaconda.com/blog/new-release-anaconda-distribution-now-supporting-m1) you linked to. I will close this issue now, but please reach out to us if you have any other questions.
