### ISSUE TITLE
AddToPath parameter doesn't work on installer Anaconda3-2022.05-Windows-x86_64

### ISSUE THREAD

**Issue by velden** [ContinuumIO/anaconda-issues#12995]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

Following documentation on https://docs.anaconda.com/anaconda/install/silent-mode/ and using same process as on previous version(s) we try to install Anaconda and let it add its paths to the path environment variable. It doesn't seem to work

Snippet from the script we use to install it:

```
:: set installation path
set installPath=C:\Anaconda3-2022.05

:: default installation
start /wait "" .\Anaconda3-2022.05-Windows-x86_64.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1 /S /D=%installPath%
```

Command window is run as administrator. 
Expected behavior: after installation and opening a **new** cmd window, `set path` should show added entries related to Anaconda.

The path environment variable seems untouched at all.

**Comment by pseudoyim** [comment]
Hello @velden 

Yes, as of [Anaconda Distribution 2022.05](https://docs.anaconda.com/anaconda/reference/release-notes/) and Miniconda-4.12.0, we disabled the option to `AddToPath` when running the installation for `AllUsers`. We did this to address [CVE-2022-26526](https://nvd.nist.gov/vuln/detail/CVE-2022-26526), which describes a security risk that was found when allowing the system `PATH` to be edited when running the installation in `AllUsers` mode. The `AddToPath` is still an option if you run the installation in `JustMe` mode.

We recommend the following workarounds:

- You could run the installation in `JustMe` mode.
- If you wish to continue using the `AllUsers` mode, you could remove the `/AddToPath=1` parameter from your command and add the installation path to your `PATH` in a separate step _after_ the installation completes.
- Since the `AddToPath` for AllUsers option was disabled in Anaconda Distribution 2022.05, you could just stick to installing an older version in order to keep using the option to `AddToPath` when installing for `AllUsers`. After the installation completes, you could then try to install an updated [`anaconda` metapackage](https://anaconda.org/anaconda/anaconda/files).

We have updated [the documentation page you referenced](https://docs.anaconda.com/anaconda/install/silent-mode/) so that other users can find this information more easily going forward.
