### ISSUE TITLE
Differences in list of checksums

### ISSUE THREAD

**Issue by IreneSophia** [ContinuumIO/anaconda-issues#13026]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

When installing anaconda on my Ubuntu 22.04 device, I noticed that there are differences between the checksums in these two links: 
https://docs.anaconda.com/anaconda/install/hashes/all/

```
Anaconda3-2022.05-Linux-x86_64.sh | 658.8 MiB | 2022-05-10 14:22:00 | a7c0afe862f6ea19a596801fc138bde0463abcbce1b753e8d5c474b506a2db2d
-- | -- | -- | --
```

https://repo.anaconda.com/archive/

```
Anaconda3-2022.05-Linux-x86_64.sh | 658.8M | 2022-05-10 13:22:00 | a01150aff48fcb6fcd6472381652de04
-- | -- | -- | --
```

Which one is the correct checksum to verify the installation file? After downloading the file from anaconda.org, the checksum I got matches the version in the first link (https://docs.anaconda.com/anaconda/install/hashes/all/).

**Comment by pseudoyim** [comment]
Hi @IreneSophia. Thank you for opening this issue.

The first location (https://docs.anaconda.com/anaconda/install/hashes/all/) lists the `sha256` checksum.
The second location (https://repo.anaconda.com/archive/) lists the `md5` checksum. 

I just downloaded the `Anaconda3-2022.05-Linux-x86_64.sh` installer and verified the following checksums for it:
- sha256: `a7c0afe862f6ea19a596801fc138bde0463abcbce1b753e8d5c474b506a2db2d `
- md5: `a01150aff48fcb6fcd6472381652de04`

We are working on updating the second location so that it lists `sha256` checksums, which will make things more consistent and less confusing for our users.

**Comment by cbouss** [comment]
The two locations are now aligned on displaying sha256 checksums.
