### ISSUE TITLE
Pytorch repodata is not up to date

### ISSUE THREAD

**Issue by atalman** [ContinuumIO/anaconda-issues#13073]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

I have uploaded latest package to pytorch:
https://anaconda.org/pytorch/pytorch-cuda

However I see that its not updated in repodata:
https://conda.anaconda.org/pytorch/noarch

Hence I am observing following failure:

```
#22 [linux/amd64 conda-installs 2/3] RUN case linux/amd64 in          "linux/arm64")  pip install --extra-index-url https://download.pytorch.org/whl/cpu/ torch torchvision torchtext ;;          *)              /opt/conda/bin/conda install -c "pytorch" -c "nvidia" -y "python=3.9" pytorch torchvision torchtext "pytorch-cuda=$(echo 11.6.2 | cut -d'.' -f 1-2)"  ;;     esac &&     /opt/conda/bin/conda clean -ya
#22 0.856 Collecting package metadata (current_repodata.json): ...working... done
#22 1.555 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#22 1.557 Collecting package metadata (repodata.json): ...working... done
#22 10.16 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#22 10.16 
#22 10.16 PackagesNotFoundError: The following packages are not available from current channels:
#22 10.16 
#22 10.16   - pytorch-cuda=11.6
#22 10.16 
#22 10.16 Current channels:
#22 10.16 
#22 10.16   - https://conda.anaconda.org/pytorch/linux-64
#22 10.16   - https://conda.anaconda.org/pytorch/noarch
#22 10.16   - https://conda.anaconda.org/nvidia/linux-64
#22 10.16   - https://conda.anaconda.org/nvidia/noarch
#22 10.16   - https://repo.anaconda.com/pkgs/main/linux-64
#22 10.16   - https://repo.anaconda.com/pkgs/main/noarch
#22 10.16   - https://repo.anaconda.com/pkgs/r/linux-64
#22 10.16   - https://repo.anaconda.com/pkgs/r/noarch
#22 10.16 
#22 10.16 To search for alternate channels that may provide the conda package you're
#22 10.16 looking for, navigate to
#22 10.16 
#22 10.16     https://anaconda.org/
#22 10.16 
#22 10.16 and use the search bar at the top of the page.
#22 10.16 
#22 10.16
```

cc @malfet @seemethere

### Conda info

```shell
na
```

### Conda config

```shell
na
```

### Conda list

```shell
na
```

### Additional Context

na

**Comment by malfet** [comment]
I can clearly see that repodata has not been updated yet:
```
nshulga@nshulga-mbp ~ % curl -v https://conda.anaconda.org/pytorch-test/noarch/repodata.json 2>&1|grep last-modified:
< last-modified: Mon, 17 Oct 2022 18:33:32 GMT
nshulga@nshulga-mbp ~ % curl -v https://conda.anaconda.org/pytorch/noarch/repodata.json 2>&1|grep last-modified: 
< last-modified: Wed, 07 Sep 2022 05:42:15 GMT
```

**Comment by csoja** [comment]
Thanks for highlighting this - we are looking into it.

**Comment by atalman** [comment]
@barabo yes this could be resolved now. Its working correctly

**Comment by malfet** [comment]
Thank you very much for you help, @csoja

**Comment by cfmh84** [comment]
I am having issue installing Pytorch useing: conda install pytorch torchvision torchaudio cpuonly -c pytorch

This is the error message I received:
-------------------------------------------------------------------
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://conda.anaconda.org/pytorch/win-64/current_repodata.json
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/pytorch/win-64'
----------------------------------------------------------------
Anyone has any idea what the issue is? I have no problem accessing https://conda.anaconda.org/pytorch/win-64 using a web browser.

I tried to use the following zoom link on this page https://github.com/pytorch/pytorch/wiki/Contact-Pytorch-Dev-Infra-Office for the office hour but saw an "Invalid meeting id":
https://fb.zoom.us/j/97659913934?pwd=cmxlcEgxNmZJckd2dTBUVWdRZkY3Zz09

Any help would be appreciated. Thanks!

**Comment by cfmh84** [comment]
Finally installed successfully. Thanks.
