### ISSUE TITLE
Update conda Debian package (from 4.12 to 23.1.0)

### ISSUE THREAD

**Issue by tobiasdiez** [ContinuumIO/anaconda-issues#13142]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [ ] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [X] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [ ] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

conda

### Version

latest

### Platform(s)

debian

### Reason for this request

https://repo.anaconda.com/pkgs/misc/debrepo/conda still installs 4.12 and not the most recent 23.1.0

**Comment by maurerle** [comment]
Since August 2023, new releases were created in the debian package.
The latest version is [conda 23.10](https://github.com/conda/conda/releases/tag/23.10.0) which is one release behind the latest release, which is fine (or wanted) in most cases where a stable environment is needed.

This issue can be closed.
