### ISSUE TITLE
NOTHING WORKS!! : Anaconda navigator, Jupyter notebooks, Anaconda prompt.

### ISSUE THREAD

**Issue by DuanBoomer** [ContinuumIO/anaconda-issues#13208]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

Okay i will keep it short and crisp.
NOTHING WORKS!!

I have installed the latest anaconda distribution for a windows machine and nothing works.
Anaconda Navigator 
```
The command prompt opens and closes a bunch of times and nothing happens
```
Jupyter Notebooks 
```
500 Internal server error
```
Spyder 
```
Missing packages
```
Anaconda powershell prompt
```
Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At C:\Users\Chirag Chetan\anaconda3\shell\condabin\Conda.psm1:76 char:36
+         Invoke-Expression -Command $activateCommand;
+                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo
   keExpressionCommand
```
Anaconda prompt
```
Doesn't recognise jupyter-notebook or anaconda-navigator
```

### Expected behavior or outcome

Everything should work and launch fine.

### Conda info

```shell
Unable to create process using 'C:\Users\Chirag Chetan\anaconda3\python.exe "C:\Users\Chirag Chetan\anaconda3\Scripts\conda-script.py" info'
```

### Conda config

```shell
Unable to create process using 'C:\Users\Chirag Chetan\anaconda3\python.exe "C:\Users\Chirag Chetan\anaconda3\Scripts\conda-script.py" config --show-sources'
```

### Conda list

```shell
Unable to create process using 'C:\Users\Chirag Chetan\anaconda3\python.exe "C:\Users\Chirag Chetan\anaconda3\Scripts\conda-script.py" list --show-channel-urls'
```

### Additional information

![ana-ins](https://github.com/ContinuumIO/anaconda-issues/assets/75297171/04e9be9c-ec77-4a92-9cfa-4e58d7840908)

This is what I installed.
![ana-logo](https://github.com/ContinuumIO/anaconda-issues/assets/75297171/1ec309a2-0f50-439f-9853-e71e50558dee)

**Comment by DuanBoomer** [comment]
cc @pseudoyim @myancy-anaconda @asmeurer @ilanschnell @csoja @jezdez @CAM-Gerlach @msarahan @jjhelmus @LtDan33

**Comment by DuanBoomer** [comment]
I have reinstalled it 3 times by now. Still nothing works.
Please help me. I got shit that needs to get done.

**Comment by brendancol** [comment]
@DuanBoomer Have you tried installing an earlier version?

**Comment by DuanBoomer** [comment]
Sorry about the profinity. It's just anaconda is supposed to be the best out their, but it just doesn't seem to work.

What version do you recommend sir?

**Comment by DuanBoomer** [comment]
@brendancol

**Comment by brendancol** [comment]
@DuanBoomer Maybe for some strange combination of your system and the most recent MS Anaconda build, it would warrant trying past version from the archieve here: https://repo.anaconda.com/archive/

**Comment by CAM-Gerlach** [comment]
I'm not totally sure why I was pinged here, as I'm not an Anaconda/Conda developer, so I can't really speak much to that. My naive suspicions based on your symptoms would be perhaps you have some security software interfering with it, something went very wrong with the install (perhaps due to said security software), or your system itself has serious problems. One other possibility is `--user` installed Python packages, under `<Your User Name>/AppData/Local/Python`, left over from a previous install.

You could try downloading, for instance, [Miniforge](https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe) instead, try to install some packages in a new environment and see if that works (make sure to move or delete any `.condarc` file in your user home directory, `C:/Users/<Your user name>./condarc` first). If so, then something went wrong with Anaconda's installer specifically; if not, likely something broader is going on.

For Spyder, you can download our [latest standalone installer for Windows](https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe), which should work reliably outside of the interference of security software or permissions issues. It includes the common scientific Python packages, though as of right now you'll still need to connect it to an external Python install (Python.org, conda-based, WinPython, etc) if you want to install your own packages.

Best of luck!

**Comment by DuanBoomer** [comment]
One last thing @brendancol,
How to uninstall anaconda properly?
Till now I have ran the ` uninstall-anaconda3.exe ` in the main folder for this purpose.
The official website tells me to do ` conda anaconda-clean ` but I can't use ` conda `

So shall I just run ` uninstall-anaconda3.exe ` ?

**Comment by DuanBoomer** [comment]
Soo some updates.
I installed ` Anaconda 2019.10 64-bit `.
But before installation I removed everything. All python, packages and anaconda stuff.
Installed the new 2019.10.  ` Note: Do not put space in the path during installation `
I finally installed it and everything works now jupyter, navigator, prompt and spyder.
Thanks @brendancol and @CAM-Gerlach for helping me solve this issue.

> Closing the issue

**Comment by CAM-Gerlach** [comment]
`2019.10` is not "new", but rather extremely outdated, by over three and a half _years_ (which is a very long time in the scientific Python world). For example, that probably has Spyder 3.x, whereas Spyder 5.4.3 is the current version (with Spyder 6 already in alpha). If the issue was due to the space in the path used for installation, I would suggest uninstalling that and re-installing the up to date Anaconda 2023.03 [available from the Anaconda web site](https://www.anaconda.com/download).

**Comment by DuanBoomer** [comment]
I guess I will install the new version after sometime.
But there is something interesting in `2019.10`. It actually gave me a warning saying `you have a space in your path`. That's how I got to know about the problem.
What shocks me is that the new version doesn't show any kind of warning and installs anaconda which will surely break because of the path problem.

> Anaconda should have a warning for path in every version.
