### ISSUE TITLE
Conda Navigator always automatically start VsCode 

### ISSUE THREAD

**Issue by jpsk666** [ContinuumIO/anaconda-issues#13271]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

and Conda is forced to be hanged/stuck if VsCode is running. This happens every time I start the navigator or click an evironment

**Comment by HoffmanGeospatial** [comment]
I am also experiencing this issue in Navigator (2.5.0, latest release, Windows10) and it's verily obnoxious! Every navigating action/click in either of the two top drop-downs for the applications options and environments causes VSCode window to pop open and must be closed in order to continue using Navigator.

**Comment by 21Apirlo21** [comment]
Same here, still didn't find a solution

**Comment by jpsk666** [comment]
Already solved——select File in the upper left corner, click on Preferences, and fill in the VS Code path below. Fill in the complete directory in the VS Code directory

**Comment by Helen-Mars** [comment]
I tried. If you run anaconda by administrator, it will not happen.
