### ISSUE TITLE
Test Anaconda 4.3 with non-ascii and spaces and commas installation directories on Windows

### ISSUE THREAD

**Issue by ccordoba12** [ContinuumIO/anaconda-issues#1336]
It seems one of the major problems for Qt5 packages on Windows (i.e. Navigator and Spyder) is the presence of those types of directories in the Anaconda installation path.

See for example https://github.com/jupyter/qtconsole/issues/181. I also received a private email telling me that a user installed Anaconda in `C:\Users\Ramón` and it had to changed to `C:\Users\Ramon`.

@csoja, we need to make a thorough testing of these cases on Windows to avoid the multitude of bug reports about Navigator and Spyder we are receiving lately.

**Comment by TheMitchWorksPro** [comment]
In case this helps, I downloaded Anaconda 4.2 earlier this week.  Did not know 4.3 would be out so soon.
On my enviornment which is Windows 7, I successfully installed to C:\ProgramFilesCoders\Anaconda2

(was building Python 27 default with 3.6 and R as secondary environments)

Something to test for that has changed my installation process:

The one symptom I experienced of note is that under Anaconda 4.1:  When you change directories during installation, if you try to make the new "Anaconda2" directory in a new location (that you already have) (i.e. - I tried to add "Anaconda2" to C:\ProgramFilesCoders that I already had as part of my organizational choice) - you get an error that the folder already exists when you then try to use it.  If instead - you navigate during installation to where Anaconda2 will go and then type or copy and paste in the Anaconda2 subpath, the error does not occur.  Using the GUI - it is as if it builds the folder, then throws an error that you can't use the folder because it already exists.  Experiencing this on 4.1, I used this work-around on 4.2 and sailed through the process.  I have not tested whether this very minor glitch still exists 4.2+ or not but it is something you may want to look for in testing just to confirm the problem does not occur in your newer better Anacondas.

**Comment by ccordoba12** [comment]
@TheMitchWorksPro, your problem is going to be fixed in Anaconda 4.3.

Closing this issue, as installations in these kind of directories is not going to be allowed since Anaconda 4.3.
