### ISSUE TITLE
Anaconda Jupyter notebook links should start Jupyter in home folder

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#1341]
On windows (and possibly other platforms) if you use the "Jupyter Notebook" link in the start-menu to start the jupyter notebook server, it will start in the anaconda folder.
That's very confusing, and relatively useless. Users are unlikely to store their notebooks in a subfolder of the anaconda folder.
It would be much better to start the server in the home folder, so that people can navigate to their desktop or documents or downloads.

I'm not sure what happens on other platforms, but I noticed that windows users are particularly likely to start jupyter via the command line, but that will leave them in a place that doesn't allow them to access their notebooks.

**Comment by msarahan** [comment]
Thanks, good suggestion.  This should be a pretty straightforward fix.

**Comment by amueller** [comment]
sweet thanks :)

**Comment by amueller** [comment]
It would be awesome if you could get this into the release ;)

**Comment by msarahan** [comment]
Agreed.  I'll make sure it stays on the agenda.

**Comment by Dmayblom** [comment]
When creating the jupyter kernel (in windows) for a new conda environment it uses your location as returned my the operating system not the location of the phyton.exe for that new environment. Why cant a jupyter kernel be created automatically when creating the conda environment?

**Comment by msarahan** [comment]
Because the jupyter kernel is an in-memory construct that only exists while you're running it?  Because users often want jupyter notebook sessions with different start folders?

**Comment by Dmayblom** [comment]
With all respect you seemed to have missed the point. It took me around 10 hours to sort this problem and it seems such a simple fix.


I am not talking about the Jupyter kernel but the location of the python kernel used by Jupyter. 

After creating a new environment with conda you need to issue an ipykernel call to point to the appropriate location.

From: https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments
source activate myenv
python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
This creates a “kernel.json” file that jupyter uses to locate the appropriate kernel. But the location written to “kernel.json” is your current location as returned by the operating system and not the location of the python kernel. 

For example, in my case I had to go in and manually edit the “kernel.json” and change 

From

"c:\\Users\\DES\\Anaconda3\\python.exe",                                # my location when I issued the ipykernel call (c:\\Users\\DES\\Anaconda3) 

To

"c:\\Users\\DES\\Anaconda3\\envs\\betfair\\python.exe",             # the actual location of the active environment

and everything worked.

It was only with help from https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/ that I managed it. 

I will bet there are lots of people that don’t end up using jupyter because they can’t get it to work.

Hope I have been of some help.

Thanks,

Des.

**Comment by nehaljwani** [comment]
@Dmayblom Sorry, I am not able to reproduce the problem that you have mentioned. It seems more like a user error to me.

I am mentioning the missing parts in the steps provided by you (on windows):
```
activate myenv
where python <-- Make sure that you are using the python from the myenv environment and not your base environment
conda install ipykernel <-- Make sure you install the ipykernel conda package in this new environment
python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
```

On following these steps, I see the behaviour which one would expect:
```
(base) C:\Users\Wani\Downloads\scratch>conda create -yn myenv

(base) C:\Users\Wani\Downloads\scratch>conda activate myenv

(myenv) C:\Users\Wani\Downloads\scratch>conda install -y ipykernel

(myenv) C:\Users\Wani\Downloads\scratch>where python
C:\Users\Wani\Downloads\mx\envs\myenv\python.exe
C:\Users\Wani\Downloads\mx\python.exe

(myenv) C:\Users\Wani\Downloads\scratch>python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
Installed kernelspec myenv in C:\Users\Wani\AppData\Roaming\jupyter\kernels\myenv

(myenv) C:\Users\Wani\Downloads\scratch>type C:\Users\Wani\AppData\Roaming\jupyter\kernels\myenv\kernel.json
{
 "argv": [
  "C:\\Users\\Wani\\Downloads\\mx\\envs\\myenv\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python (myenv)",
 "language": "python"
}
```

The [docs](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments) are also pretty much clear about this:
>Make sure you have ipykernel **installed in your environment**
>source activate myenv
>conda install ipykernel
>...
>And in a second environment, **after making sure ipykernel is installed in it**:
>source activate other-env
>python -m ipykernel install --user --name other-env --display-name "Python (other-env)"

**Comment by Dmayblom** [comment]
Nehal,

Thankyou for taking the time to respond. You are right it was user error but I did not see “the documentation” I saw “some documentation” from a google search and it seems that I am not the only one. 

Why isn’t the installation of ipykernel automatically included as part of the creation of the environment? 

From what I saw a lot of people have similar problems. You and your team and in fact all the community that creates open source software, thank the lord, do a fantastic job. But programmers don’t think like the average person and what is intuitive for you does not always make sense to the rest of us. Perhaps having an artist help design interfaces might make the software more widely used.

Once again thankyou. Now that I have it working it is great software.

Des. Mayblom
