### ISSUE TITLE
qt5 depends on freetype 2.5

### ISSUE THREAD

**Issue by looooo** [ContinuumIO/anaconda-issues#1368]
with earlier versions of qt anything higher then freetype 2.5 could be used. With qt5 only freetype 2.5 is possible. Would it be possible to change this?

**Comment by ccordoba12** [comment]
@mingwandroid?

**Comment by mingwandroid** [comment]
No. Binary compatibility does not allow much flexibility around this issue.

**Comment by ccordoba12** [comment]
He means that freetype 2.5 and 2.6 have a different API and that it's not possible to compile Qt5 with support for both, sorry.

**Comment by ccordoba12** [comment]
different API and perhaps ABI too.

**Comment by looooo** [comment]
Thanks for your answer.
So anaconda has freetype 2.5 pinned. Conda-forge pinns 2.6. So I will wait for a conda-forge qt5.

**Comment by ccordoba12** [comment]
It seems you're mixing conda-forge and Continuum packages. Please don't it.

You should create and work in a dedicated environment when installing conda-forge packages, instead of doing it directly in your root environment. That's because conda-forge and defaults have different build specs and they can't be mixed or else you'll see odd crashes.
