### ISSUE TITLE
Add Orange back to Anaconda Navigator front screen

### ISSUE THREAD

**Issue by brylie** [ContinuumIO/anaconda-issues#1381]
Orange Machine Learning was removed from the Anaconda Navigator front page, due to its dependency on Qt4. As of version 3.3.9, Orange Machine Learning is compatible with Qt5.

Please consider adding Orange Machine Learning back to the 'front page' of Anaconda Navigator.

**Comment by astaric** [comment]
The orange3-3.3.11 build on conda-forge can be used with both pyqt=4 and pyqt=5. It installs nicely from navigator and can be run from there as well. The only problem is that it lack the icon, instead of the smiling orange, it shows the default green circle.

The recipe already has the "icon:" key in the app section of the recipe, and the icon gets included in the distribution. Is there anything else I need to add to make it show?

**Comment by goanpeca** [comment]
@astaric the current state of affairs is that we cannot fetch the icon from the information stored in anaconda-cloud. This requires both changes in navigator and anaconda cloud. So for the moment we will just have to wait on that.

**Comment by goanpeca** [comment]
The icon fetching problems is now being actively worked on. In the meantime orange is back for some months now.
