### ISSUE TITLE
Applications not showing up in Anaconda Navigator

### ISSUE THREAD

**Issue by washcycle** [ContinuumIO/anaconda-issues#1455]
Windows 7 x64, Anaconda Navigator 1.4.3

After a reboot the only application I see is qtconsole. 

I can still open the other applications via CLI.

**Comment by goanpeca** [comment]
@washcycle did you install anaconda for the current user? or all users?

**Comment by washcycle** [comment]
I did whatever was recommended which is current user, if I'm not mistaken. It was working earlier, but I recently upgrade to the latest version and thought it might be related. Either way it is odd behavior. I'm try and reboot at the end of the day to see if it fixes it.

**Comment by nsv59** [comment]
Was this resolved?  I have the same issue after my system crashed

**Comment by washcycle** [comment]
I fixed it with the nuclear option. Uninstall and reinstall.

**Comment by nsv59** [comment]
It may be coincidental, but every thing is back to the way it was working before.  The only difference I can identify is that my Wifi connection was unavailable initially when I was having this issue.  Not sure if this needs to access a licenses server somewhere on the net.  This issue was reproducible this morning, when my wifi access was down!!
