### ISSUE TITLE
ssl_verify in .condarc resets

### ISSUE THREAD

**Issue by washcycle** [ContinuumIO/anaconda-issues#1456]
I have to set a corporate root certificate and use the follow to accomplish that.

`conda config --set ssl_verify "root.cer"

Random actions will reset it... randomly.

The most recent was Signing in to Anaconda Cloud from the Anaconda Navigator. Sometimes the `conda update *` or `conda install *` will cause the ssl_verify setting to get overriden.

**Comment by kalefranz** [comment]
What does it get overwritten with?

**Comment by goanpeca** [comment]
@washcycle Navigator uses the setting from anaconda client configuration and will update .condarc to match the setting to avoid having different configurations.

**Comment by washcycle** [comment]
It will get set to ssl_verify = true.

Regards,
Matthew Landowski

**Comment by ct00** [comment]
Hi I installed the latest anaconda distribution in my office and updated all packages. However I am still having a problem with verify_ssl=false (I need this set to false due to some issue in my office). I can specify that in .condarc and have no issues working within the anaconda terminal but the moment I launch navigator, it updates .condarc verify_ssl to true as mentioned above. I thought I could change this within the ini files under .anaconda but still always resets back to true. I have looked everywhere in anaconda-issues and elsewhere on the web but am at a loss how to stop this from happening. I must be missing something overly simple but can anyone point me to the answer? Thanks

**Comment by goanpeca** [comment]
@ct00 since Navigator relies on anaconda-client, we give the setting of anaconda-client precedence over the conda one. If you set the `ssl_verify` to False on anaconda client, Navigator will not reset it.

**Comment by ct00** [comment]
thanks for the quick reply but also tried to figure that out but came up short - how do I do that on anaconda client? I am not using anaconda cloud (that seemed to be related to some of the seaches I did over anaconda-client)

**Comment by goanpeca** [comment]
`anaconda config --set ssl_verify True` ?

**Comment by ct00** [comment]
Tried that (to set to false) but doesn't seem to have worked. I did the following:
(base) C:\Users\telmerco>anaconda config --set ssl_verify False

This created .continuum/anaconda-client/config.yaml that contains the single line "ssl_verify: false"

I made sure that .condarc had ssl_verify=false and ran navigator from the anaconda terminal and the output is below along with condo info and conda list. After it started I looked in .condarc and ssl_verify had been reset to true. What am I missing? I had an older distribution (4.40?) that this worked fine (ie. just changing ssl_verify=false in .condarc). One thing I noted is when navigator launches I I go to file->preferences and deselect ssl, if won't let me as the anaconda api domain is an ssl domain (i.e. https//). Is that possibly what keeps forcing it back? Thanks

(base) C:\Users\telmerco>anaconda-navigator
2018-01-04 19:04:40,217 - ERROR client_api._get_api_info:554
HTTPSConnectionPool(host=/'api.anaconda.org/', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError('bad handshake: Error([(/'SSL routines/', /'ssl3_get_server_certificate/', /'certificate verify failed/')],)',),))
 
2018-01-04 19:06:32,396 - ERROR download_api._is_valid_api_url:326
Expecting value: line 1 column 1 (char 0)
 
(base) C:\Users\telmerco>conda info
 
     active environment : base
    active env location : C:\Anaconda3
            shell level : 1
       user config file : C:\Users\telmerco\.condarc
populated config files : C:\Users\telmerco\.condarc
          conda version : 4.4.6
    conda-build version : 3.2.1
         python version : 3.6.3.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\telmerco\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\telmerco\AppData\Local\conda\conda\envs
                          C:\Users\telmerco\.conda\envs
               platform : win-64
             user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.3 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
 
 
 
(base) C:\Users\telmerco>conda list
# packages in environment at C:\Anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
_license                  1.1                      py36_1    http://nexus.xxxxxx.com:8081/nexus/content/sites/ib-cto-python
alabaster                 0.7.10           py36hcd07829_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.6.6            py36ha174c20_0    defaults
anaconda-navigator        1.6.11           py36h25c516c_0    defaults
anaconda-project          0.8.2            py36hfad2e28_0    defaults
asn1crypto                0.23.0           py36h546eea3_0    defaults
astroid                   1.5.3            py36h9d85297_0    defaults
astropy                   2.0.3            py36hfa6e2cd_0    defaults
attrs                     17.3.0           py36hc87868e_0    defaults
babel                     2.5.0            py36h35444c1_0    defaults
backports                 1.0              py36h81696a8_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    defaults
beautifulsoup4            4.6.0            py36hd4cc5e8_1    defaults
bitarray                  0.8.1            py36h6af124b_0    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blaze                     0.11.3           py36h8a29ca5_0    defaults
bleach                    2.1.1            py36h834942a_0    defaults
bokeh                     0.12.13          py36h047fa9f_0    defaults
boto                      2.48.0           py36h1a776d2_1    defaults
bottleneck                1.2.1            py36hd119dfa_0    defaults
bzip2                     1.0.6                haa5b126_2    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py36hfe50d7b_0    defaults
certifi                   2017.11.5        py36hb8ac631_0    defaults
cffi                      1.11.2           py36h829d1a5_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
click                     6.7              py36hec8c647_0    defaults
cloudpickle               0.5.2            py36h6b1d831_0    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
comtypes                  1.1.2            py36heb9b3d1_0    defaults
conda                     4.4.6                    py36_0    defaults
conda-build               3.2.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h065de53_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
coverage                  4.4.2            py36hd32d05b_0    defaults
cryptography              2.1.4            py36he1d7878_0    defaults
curl                      7.55.1               h3b839b5_4    defaults
cycler                    0.10.0           py36h009560c_0    defaults
cython                    0.27.3           py36h22f4c84_0    defaults
cytoolz                   0.8.2            py36h547e66e_0    defaults
dask                      0.16.0           py36hea4f2f0_0    defaults
dask-core                 0.16.0           py36h5683b08_0    defaults
datashape                 0.5.4            py36h5770b85_0    defaults
decorator                 4.1.2            py36he63a57b_0    defaults
distlib                   0.2.5            py36h51371be_0    defaults
distributed               1.20.2                   py36_0    defaults
docutils                  0.14             py36h6012d8f_0    defaults
entrypoints               0.2.3            py36hfd66bb0_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hffdae1b_0    defaults
filelock                  2.0.13           py36h20000bf_0    defaults
flask                     0.12.2           py36h98b5e8f_0    defaults
flask-cors                3.0.3            py36h8a3855d_0    defaults
freetype                  2.8                  h51f8f2c_1    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py36h342a76c_0    defaults
glob2                     0.6              py36hdf76b57_0    defaults
greenlet                  0.4.12           py36ha00ad21_0    defaults
h5py                      2.7.1            py36he54a1c3_0    defaults
hdf5                      1.10.1               h98b8871_1    defaults
heapdict                  1.0.0            py36h21fa5f4_0    defaults
html5lib                  1.0.1            py36h047fa9f_0    defaults
hypothesis                3.38.5           py36h987501d_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.6              py36h148d497_1    defaults
imageio                   2.2.0            py36had6c2d2_0    defaults
imagesize                 0.7.1            py36he29f638_0    defaults
intel-openmp              2018.0.0             hd92c6cd_8    defaults
ipykernel                 4.7.0            py36h2f9c1c0_0    defaults
ipython                   6.2.1            py36h9cf0123_1    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.0.5            py36h6314756_0    defaults
isort                     4.2.15           py36h6198cc5_0    defaults
itsdangerous              0.24             py36hb6c5a24_1    defaults
jdcal                     1.3              py36h64a5255_0    defaults
jedi                      0.11.0                   py36_2    defaults
jinja2                    2.10             py36h292fed1_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0            py36h422fd7e_2    defaults
jupyter_client            5.1.0            py36h9902a9a_0    defaults
jupyter_console           5.2.0            py36h6d89b47_1    defaults
jupyter_core              4.4.0            py36h56e9d50_0    defaults
jupyterlab                0.30.6           py36h047fa9f_0    defaults
jupyterlab_launcher       0.6.0                    py36_0    defaults
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.32               h140d38e_4    defaults
libssh2                   1.8.0                h75d9407_3    defaults
libtiff                   4.0.9                h0f13578_0    defaults
libxml2                   2.9.4                h41ea7b2_6    defaults
libxslt                   1.1.29               h0037b19_6    defaults
llvmlite                  0.21.0           py36he0b0552_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
lxml                      4.1.1            py36he0adb16_0    defaults
lzo                       2.10                 h6df0209_2    defaults
markupsafe                1.0              py36h0e26971_1    defaults
matplotlib                2.1.1            py36h2062329_0    defaults
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.10           py36h42196fb_0    defaults
mistune                   0.8.1            py36h007b88b_0    defaults
mkl                       2018.0.1             h2108138_4    defaults
mkl-service               1.1.2            py36h57e144c_4    defaults
mpmath                    1.0.0            py36hacc8adf_2    defaults
msgpack-python            0.4.8            py36h58b1e9d_0    defaults
multipledispatch          0.4.9            py36he44c36e_0    defaults
navigator-updater         0.1.0            py36h8a7b86b_0    defaults
nbconvert                 5.3.1            py36h8dc0fde_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  2.0              py36hff991e3_0    defaults
nltk                      3.2.5            py36h76d52bb_0    defaults
nose                      1.3.7            py36h1c3779e_2    defaults
notebook                  5.2.2            py36hc48260a_0    defaults
numba                     0.36.2          np113py36h0128aa7_0    defaults
numexpr                   2.6.4            py36h30784b8_0    defaults
numpy                     1.13.3           py36ha320f96_0    defaults
numpydoc                  0.7.0            py36ha25429e_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.44             py36h0a7bdd2_0    defaults
openpyxl                  2.4.9            py36h6c6577a_0    defaults
openssl                   1.0.2n               h74b6da3_0    defaults
packaging                 16.8             py36ha0986f6_1    defaults
pandas                    0.22.0           py36h6538335_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
parso                     0.1.1            py36hae3edee_0    defaults
partd                     0.3.8            py36hc8e763b_0    defaults
path.py                   10.5             py36h2b94a8f_0    defaults
pathlib2                  2.3.0            py36h7bfb78b_0    defaults
patsy                     0.4.1            py36h42cefec_0    defaults
pep8                      1.7.0            py36h0f3d67a_0    defaults
pickleshare               0.7.4            py36h9de030f_0    defaults
pillow                    5.0.0            py36h0738816_0    defaults
pip                       9.0.1            py36h226ae91_4    defaults
pkginfo                   1.4.1            py36hb0f9cfa_1    defaults
pluggy                    0.6.0            py36hc7daf1e_0    defaults
ply                       3.10             py36h1211beb_0    defaults
progress                  1.3              py36hbeca8d3_0    defaults
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults
psutil                    5.4.1            py36h257d382_0    defaults
py                        1.5.2            py36hbcfbabc_0    defaults
pycodestyle               2.3.1            py36h7cc55cd_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pycrypto                  2.6.1            py36he68e6e2_1    defaults
pycurl                    7.43.0           py36h086bf4c_3    defaults
pyflakes                  1.6.0            py36h0b975d6_0    defaults
pygments                  2.2.0            py36hb010967_0    defaults
pylint                    1.7.4            py36ha4e6ded_0    defaults
pympler                   0.5              py36h863af32_0    defaults
pyodbc                    4.0.21           py36h82c9817_0    defaults
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pyqt                      5.6.0            py36hb5ed885_5    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
pytables                  3.4.2            py36h71138e3_2    defaults
pytest                    3.3.0            py36hf3522a2_0    defaults
python                    3.6.3                h3b118a2_4    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
pytz                      2017.3           py36h1d3fa6b_0    defaults
pywavelets                0.5.2            py36hc649158_0    defaults
pywin32                   221              py36h9c10281_0    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
pyzmq                     16.0.3           py36he714bf5_0    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.3.1            py36h99a29a9_0    defaults
qtpy                      1.3.1            py36hb8717c5_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
rope                      0.10.7           py36had63a69_0    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
scikit-image              0.13.0           py36h6dffa3f_1    defaults
scikit-learn              0.19.1           py36h53aea1b_0    defaults
scipy                     1.0.0            py36h1260518_0    defaults
seaborn                   0.8.1            py36h9b69545_0    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
simplegeneric             0.8.1            py36heab741f_0    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.18.1           py36h9c25514_2    defaults
six                       1.11.0           py36h4db2310_1    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         0.5.3            py36hbefa0ab_0    defaults
sortedcontainers          1.5.7            py36ha90ac20_0    defaults
sphinx                    1.6.3            py36h9bb690b_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1    defaults
spyder                    3.2.5                    py36_0    defaults
sqlalchemy                1.1.13           py36h5948d12_0    defaults
sqlite                    3.20.1               h9eeafa9_2    defaults
statsmodels               0.8.0            py36h6189b4c_0    defaults
sympy                     1.1.1            py36h96708e0_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
toolz                     0.8.2            py36he152a52_0    defaults
tornado                   4.5.2            py36h57f6048_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
typing                    3.6.2            py36hb035bda_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_2    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
werkzeug                  0.12.2           py36h866a736_0    defaults
wheel                     0.30.0           py36h6c3ec14_1    defaults
widgetsnbextension        3.0.8            py36h933dd4f_0    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xlrd                      1.1.0            py36h1cb58dc_1    defaults
xlsxwriter                1.0.2            py36hf723b7d_0    defaults
xlwings                   0.11.4           py36hd3cf94d_0    defaults
xlwt                      1.3.0            py36h1a4751e_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zict                      0.1.3            py36h2d8e73e_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
zope                      1.0                      py36_0    defaults
zope.interface            4.4.3            py36h56cab3c_0    defaults

**Comment by goanpeca** [comment]
If you do `anaconda config --set verify_ssl True` ?

I think we renamed that recently, so now we have to track both names I am doing a navigator release next week so I can take care of this nuisance, but  `anaconda config --set verify_ssl True` should work

**Comment by ct00** [comment]
unfortunately that still didn't work (ie run the command you mentioned above with arg True but when I launch navigator, verify_ssl reverts to true in .condarc). Seems like it has something to do with my firewall? When I try to deselect ssl in navigator and hit apply the error "Invalid Anaconda api url. Check the url is valid and corresponds to the api endpoint". Same error message below. Also I have no issues deselecting ssl on the same distribution set on my Mac at home. Thoughts?

(base) C:\Users\telmerco>anaconda config --show
sites:
  alpha:
    url: http://api.alpha.binstar.org
  binstar:
    url: https://api.anaconda.org
ssl_verify: true
 
 
(base) C:\Users\telmerco>anaconda-navigator
2018-01-04 19:36:28,171 - ERROR client_api._get_api_info:554
HTTPSConnectionPool(host=/'api.anaconda.org/', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError('bad handshake: Error([(/'SSL routines/', /'ssl3_get_server_certificate/', /'certificate verify failed/')],)',),))
 
 
 
Invalid Anaconda api url
 
Check the url is valid and corresponds to the api endpoint

**Comment by goanpeca** [comment]
@ct00 looking into this tomorrow, it may be related to the firewall.. but not sure :-\ should be working

**Comment by ct00** [comment]
thanks help is very much appreciated

**Comment by ct00** [comment]
Also it is working on my colleague's machine with 4.40 - if it helps I can do some diagnostic comparisons if you tell me the commands to run tomorrow. Cheers

**Comment by goanpeca** [comment]
Hi @ct00 I think I meant `anaconda config --set verify_ssl False` in the previous message. So let's try

`anaconda config --set verify_ssl False`

and

`anaconda config --set ssl_verify False`

And then on navi again. I think this is related to some changes in anaconda-client 1.6.6 (see ). Is anaconda-client 1.6.5 working for you?

**Comment by ct00** [comment]
Sorry for the delay - the first of two commands worked. When I tried the second, it warned there was no option by that name so I removed it from the config.yaml file and then opened navigator and verify_ssl=false in my .condarc did not get changed back to true. Thanks for the help and will open as a new issue next time. Cheers
