### ISSUE TITLE
openjdk version is misleading

### ISSUE THREAD

**Issue by rvalieris** [ContinuumIO/anaconda-issues#1460]
The version string of the [openjdk](https://anaconda.org/anaconda/openjdk) package reflects the internal version of the zulu jvm, not the actual version of the jdk.

```
$ ~/conda/pkgs/openjdk-8.17.0.3-1/bin/java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (Zulu 8.17.0.3-linux64) (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (Zulu 8.17.0.3-linux64) (build 25.102-b14, mixed mode)
```

to be consistent and comparable with other JVMs and other packages that ship the openjdk the version string should be based on the first line: `openjdk version "1.8.0_102"`

for example, the version of the [conda-forge::openjdk](https://github.com/conda-forge/openjdk-feedstock/blob/master/recipe/meta.yaml) is "8.0.112"

**Comment by sodre** [comment]
Hi folks, I am one of the co-maintainers of [conda-forge/openjdk-feedstock](https://github.com/conda-forge/openjdk-feedstock) and I am interested if there are any plans to fix this versioning issue.

Also, I think there is a bug in the recipe for your openjdk, you forgot to add jre/lib to the rpath. Please feel free to verify by adding the test cases from the conda-forge recipe to yours.

**Comment by msarahan** [comment]
@kalefranz what is the status of the new build that you did?

@sodre this was a high priority for us, and I know that Kale did new builds with the fixed versioning, but I don't see the packages available on our repository.  I'll follow up with Kale first thing next week.

**Comment by kalefranz** [comment]
> what is the status of the new build that you did?

The PR for the updated recipe is merged in `ContinuumIO/anaconda`, but it can't be successfully built because of the `--no-activate` flag.  The PR itself was a trivial update.  At this point, I don't have a lot of hope we'll resolve the `--no-activate` flag discussion, given entrenched positions.

I'm working hard with @tyler-thetyrant to get concourse up and running.  @tyler-thetyrant, we're counting on you..

![yourmyonlyhope-vblog](https://cloud.githubusercontent.com/assets/1418419/25300861/85f9a4b6-26de-11e7-850e-fe8444bffcc5.png)

**Comment by kalefranz** [comment]
openjdk 8.0.121 (build 2) is released to defaults.  Thanks @mingwandroid for the help.

**Comment by mingwandroid** [comment]
No problem!
