### ISSUE TITLE
Anaconda "failed to start because it could not find or load the Qt platform plugin"

### ISSUE THREAD

**Issue by precessor** [ContinuumIO/anaconda-issues#1467]
PROBLEM: Anaconda Navigator won't start (nor will Spyder, IPython, ...). Error is reported:
This application failed to start because it could not find or load the Qt platform plugin "windows" in ""

SOLUTION:
Copy the 
Continuum\Anaconda3\Library\plugins\platforms
folder to 
Continuum\Anaconda3

Using Windows 7 64 bit. Tried to install Anaconda 4.3.0 64bit. Uninstalled then 32bit. Then Anaconda 4.2.0 too. 

Dave Higgins

PS
Not sure if related: I also got the commonly reported failures to write to the PATH env, menus and directories at the end of the install process, and did those manually in a CMD "Run as administrator":

"C:\Users\<username>\AppData\Local\Continuum\Anaconda3\pythonw.exe" -E -s "C:\Users\<username>\AppData\Local\Continuum\Anaconda3\Lib\_nsis.py" addpath
"C:\Users\<username>\AppData\Local\Continuum\Anaconda3\pythonw.exe" -E -s "C:\Users\<username>\AppData\Local\Continuum\Anaconda3\Lib\_nsis.py" mkdirs
"C:\Users\<username>\AppData\Local\Continuum\Anaconda3\pythonw.exe" -E -s "C:\Users\<username>\AppData\Local\Continuum\Anaconda3\Lib\_nsis.py" mkmenus

Note: my user is an Administrator on this PC (HP Elitebook). I also tried running the Anaconda installer executable as Administrator (right-click, Run as Admin, etc). No change in loading error after install and reboots.

**Comment by mingwandroid** [comment]
This bug was a bug in the installer logic where paths containing more than 30 characters could not be used.

Anaconda 4.3.0.1 fixed this issue.

**Comment by precessor** [comment]
The long-paths bug was not the issue (I was using 4.3.0.1), but another installation of Qt was.
Others with this problem may wish to search their systems for other instances of Qt (e.g. search for Qt*.dll files), and whether they are included in your PATH environment variable, thereby causing the "wrong" Qt files to be used by Anaconda.

**Comment by mingwandroid** [comment]
Yes, this is why I always caution against adding things to `PATH` on Windows, including `Anaconda`!

**Comment by geometrikal** [comment]
I'm having the same error message recently. It is not an issue of characters / spaces for me.

The problem is that matplotlib is loading qt dlls from somewhere else on the system path. In my case it was from my miktex installation. Removing the miktex bin directory from the path fixed it, but now latex won't compile with texstudio...

Running the "activate" script beforehand adds the python directories to the front of the path, and everything works. However, this is limited to the current session, and when running python in, for example, pycharm, the error is still there. When launching other things, for example, spyder, presumably anaconda navigators runs "activate" beforehand and this is why they work. ping @karimandres 

What I found that worked was installing Anaconda with the PATH option ticked and the path added to the user's environment. Then move any offending paths (e.g. the miktex one) from the system path to last on the the user path.

Ultimately I believe this must be a problem with matplotlib. It should load the correct dlls in its own directory first, should it not? Maybe anaconda is moving the dlls around, forcing a search of the path?

**Comment by markjay4k** [comment]
@geometrikal thank you. that was my problem as well. I had to remove my path to texstudio from my system path and move it to last entry in my user path. everything is working now.

**Comment by Sdnzr** [comment]
Hello, i having similiar issue with qt in cmd. both qt and PyQt is installed in anaconda directories. when i run  my program through anaconda prompt, it runs fine and doe sense qt. but when i run it through cmd its not. so cmd is not sensing qt. i tried adding an env variable to miktex qt...it didnt work. pls help.
________________________________________________________________________________-
F:\SUAVE\tutorials\Tutorials-1.0.2\Tutorials-1.0.2>python tut_solar_uav.py
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Available platform plugins are: minimal, offscreen, windows.

Reinstalling the application may fix this problem.
_______________________________________________________________________________
and then the python crashes.
to find a work around. i deleted qtconfig file in anaconda directory, and found the same error in anaconda prompt as well. so it is able to sense this file and find qt directories..which contains this
_____________________________________________________________________________--
[Paths] 
Prefix = C:/Users/Saad/Anaconda2/Library 
Binaries = C:/Users/Saad/Anaconda2/Library/bin 
Libraries = C:/Users/Saad/Anaconda2/Library/lib 
Headers = C:/Users/Saad/Anaconda2/Library/include/qt 
_____________________________________________________________________________
So cmd is unable to find qt in anaconda directory,,,,,,,,,,so how to fix this??????

**Comment by yorzh86** [comment]
got same problem trying to run pylab in win10. Works with anaconda/spyder...

**Comment by ugurgudelek** [comment]
I have solved the issue when I remove the entry of miktex on my PATH. Probably, there was a conflict with qt dll files.
