### ISSUE TITLE
Anaconda Navigator doesn't show an update as being available for new builds of conda packages

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#1523]
If I install e.g. glueviz=0.10.0=py36_1 from conda-forge, then open the Anaconda Navigator, I don't see any updates as being available for glueviz even though py36_2 exists (note that conda-forge needs to be added as a global channel of course). Is this a bug or expected behavior?

**Comment by goanpeca** [comment]
@astrofrog I dont think we are showing different builds as an option for updates by default. In this specific case we would need to remove and install so that the latest build is picked up by conda.

Probably not the solution you expect right now. I am moving this to internal tracker and get back to you, ok?
