### ISSUE TITLE
Anaconda too liberal in adding entries to the PATH variable on Windows

### ISSUE THREAD

**Issue by krcools** [ContinuumIO/anaconda-issues#1543]
As part of a standard installation, the following directories are added to the system path:

```
...\Anaconda3
...\Anaconda3\Scripts
...\Anaconda3\Library\bin
```

Apart from binaries the package wants to expose to command line users, these dirs contain dlls of very popular libraries such as hdf5 and Qt. I have had these dlls interfere with e.g. cmake system introspection several times already. Please could Anaconda be more conservative in its dll proliferation...

**Comment by mingwandroid** [comment]
There's actually 5 paths added and there's nothing we can do about this. Mostly it comes from needing to mix MSVC compiled software with two variants of GCC compiled software and those things being incompatible. Even if we could reduce some of them that horse has *long* since bolted.

I recommend that you never let the installer add any entries to your `PATH` environment variable though (as this is the fastest route to DLL-hell) and instead launch via the `Anaconda Prompt` or `Anaconda Navigator`. This will prevent most problems.
