### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by elnene315** [ContinuumIO/anaconda-issues#1561]
Anaconda Navigator Update error:

/Users/Andres/anaconda/bin/python /Users/Andres/anaconda/bin/conda install --yes --json --force-pscheck --name root anaconda-navigator=1.5.0: UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator 1.5.0*
  - pyqtgraph -> pyqt 4.*
  - pyqtgraph -> python 2.7*|3.4*
Use "conda info <package>" to see the dependencies for each package.

{'conda': '4.2.12', 'os': 'Darwin;16.4.0;Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64;x86_64;i386', 'pyqt': '4.11.4', 'platform': 'osx-64', 'language': 'en', 'python': '3.5.2', 'qt': '4.8.7', 'version': '1.2.1'}

**Comment by goanpeca** [comment]
@elnene315 as the error indicates, you cannot update navigator to the latests because it depends on qt=5. Currenty you have a package (pyqtgraph) that is apparently not compatible with qt=4.

You could update Navigator to the latests release by removing `pyqtgraph` first, Please open a terminal and type

`$ conda remove pyqtgraph`
`$ conda install anaconda-navigator=1.5`
