### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".  Reinstalling the application may fix this problem.

### ISSUE THREAD

**Issue by ohTAZ** [ContinuumIO/anaconda-issues#1603]
My config now:
Windows 10, latest
Python 3.6 64 bit

Problem is: 
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
When i try to start the spyder

I have already completed the update with the command:
conda update --all

**Comment by mingwandroid** [comment]
Please show the output from:
`conda info`
`conda list --show-channel-urls`

How did you try to launch `spyder`? Please try to launch `spyder` from the `Anaconda Prompt`.

**Comment by ohTAZ** [comment]
[conda info.txt](https://github.com/ContinuumIO/anaconda-issues/files/924709/conda.info.txt)
[conda list --show.txt](https://github.com/ContinuumIO/anaconda-issues/files/924710/conda.list.--show.txt)
i try to launch it from the Anaconda Prompt then
>spyder
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.

**Comment by mingwandroid** [comment]
Unfortunately Anaconda does not work when installed to a folder with non-ASCII characters. Please install it somewhere else than `C:\Users\Jo„oVictor\Anaconda3`.

**Comment by ohTAZ** [comment]
The non-ASCII characters is JoãoVictor is my name, because this is my name user. How will i instal it in another folder?
Thank you for your contributions with me.

**Comment by ohTAZ** [comment]
i rename my folder "Jo„oVictor" and are a solucion. 
Thank's @mingwandroid 
You is the best. <3

**Comment by muditrastogi** [comment]
I am also facing the same issue using windows 7 32 bit system
c:\Anaconda2\Scripts>spyder
This application failed to start because it could not find or load the Qt platform plugin "windows" in  "".

`conda info`

`Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : c:\Anaconda2  (writable)
    default environment : c:\Anaconda2
       envs directories : c:\Anaconda2\envs
          package cache : c:\Anaconda2\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\RAJA\.condarc
           offline mode : False
`

`conda list`
`# packages in environment at c:\Anaconda2:
#
_license                  1.1                      py27_1
alabaster                 0.7.9                    py27_0
anaconda                  4.3.0               np111py27_0
anaconda-client           1.6.0                    py27_0
anaconda-navigator        1.4.3                    py27_0
argcomplete               1.0.0                    py27_1
astroid                   1.4.9                    py27_0
astropy                   1.3                 np111py27_0
babel                     2.3.4                    py27_0
backports                 1.0                      py27_0
backports_abc             0.5                      py27_0
beautifulsoup4            4.5.3                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
bokeh                     0.12.4                   py27_0
boto                      2.45.0                   py27_0
bottleneck                1.2.0               np111py27_0
bzip2                     1.0.6                     vc9_3  [vc9]
cdecimal                  2.3                      py27_2
cffi                      1.9.1                    py27_0
chardet                   2.3.0                    py27_0
chest                     0.2.3                    py27_0
click                     6.7                      py27_0
cloudpickle               0.2.2                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
comtypes                  1.1.2                    py27_0
conda                     4.2.13                   py27_0    conda-forge
conda-env                 2.6.0                         0
configobj                 5.0.6                    py27_0
configparser              3.5.0                    py27_0
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.4                    py27_0
crab                      0.5.0                     <pip>
cryptography              1.7.1                    py27_0
curl                      7.52.1                    vc9_0  [vc9]
cx-Freeze                 5.0.1                     <pip>
cycler                    0.10.0                   py27_0
cython                    0.25.2                   py27_0
cytoolz                   0.8.2                    py27_0
dask                      0.13.0                   py27_0
datashape                 0.5.4                    py27_0
decorator                 4.0.11                   py27_0
dill                      0.2.5                    py27_0
Django                    1.11                      <pip>
docutils                  0.13.1                   py27_0
entrypoints               0.2.2                    py27_0
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
fastcache                 1.0.2                    py27_1
flask                     0.12                     py27_0
flask-cors                3.0.2                    py27_0
freetype                  2.5.5                     vc9_2  [vc9]
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.2.1                    py27_0
greenlet                  0.4.11                   py27_0
grin                      1.2.1                    py27_3
h5py                      2.6.0               np111py27_2
hdf5                      1.8.15.1                  vc9_4  [vc9]
heapdict                  1.0.0                    py27_1
icu                       57.1                      vc9_0  [vc9]
idna                      2.2                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.18                   py27_0
ipykernel                 4.5.2                    py27_0
ipython                   5.1.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                5.2.2                    py27_1
isort                     4.2.5                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.3                      py27_0
jedi                      0.9.0                    py27_1
jinja2                    2.9.4                    py27_0
jpeg                      9b                        vc9_0  [vc9]
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.1                    py27_0
Keras                     2.0.2                     <pip>
lazy-object-proxy         1.2.2                    py27_0
libpng                    1.6.27                    vc9_0  [vc9]
libpython                 2.0                      py27_0
libtiff                   4.0.6                     vc9_3  [vc9]
llvmlite                  0.15.0                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.7.2                    py27_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
markupsafe                0.23                     py27_2
matplotlib                2.0.0               np111py27_0
menuinst                  1.4.4                    py27_0
mingw                     4.7                           1
mistune                   0.7.3                    py27_0
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py27_3
mpmath                    0.19                     py27_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.2.0                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2.2                    py27_0
nose                      1.3.7                    py27_1
notebook                  4.3.1                    py27_1
numba                     0.30.1              np111py27_0
numexpr                   2.6.1               np111py27_2
numpy                     1.11.3                   py27_0
numpydoc                  0.6.0                    py27_0
odo                       0.5.0                    py27_1
olefile                   0.44                      <pip>
opencv-python             3.2.0.7                   <pip>
openpyxl                  2.4.1                    py27_0
openssl                   1.0.2k                    vc9_0  [vc9]
pandas                    0.19.2              np111py27_1
partd                     0.3.7                    py27_0
path.py                   10.0                     py27_0
pathlib2                  2.2.0                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pickleshare               0.7.4                    py27_0
pil                       1.1.7                    py27_0
pillow                    4.0.0                    py27_0
pip                       9.0.1                    py27_1
ply                       3.9                      py27_0
prompt_toolkit            1.0.9                    py27_0
psutil                    5.0.1                    py27_0
py                        1.4.32                   py27_0
pyasn1                    0.1.9                    py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.17                     py27_0
pycrypto                  2.6.1                    py27_5
pycurl                    7.43.0                   py27_2
pyflakes                  1.5.0                    py27_0
pygame                    1.9.3                     <pip>
pygments                  2.1.3                    py27_0
pylint                    1.6.4                    py27_1
pyopenssl                 16.2.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pytables                  3.2.2               np111py27_4
pytest                    3.0.5                    py27_0
python                    2.7.13                        0
python-dateutil           2.6.0                    py27_0
pytz                      2016.10                  py27_0
pywin32                   220                      py27_2
pyyaml                    3.12                     py27_0
pyzmq                     16.0.2                   py27_0
qt                        5.6.2                     vc9_3  [vc9]
qtawesome                 0.4.3                    py27_0
qtconsole                 4.2.1                    py27_2
qtpy                      1.2.1                    py27_0
requests                  2.12.4                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_1
scandir                   1.4                      py27_0
scikit-image              0.12.3              np111py27_1
scikit-learn              0.18.1              np111py27_1
scipy                     0.18.1              np111py27_1
seaborn                   0.7.1                    py27_0
setuptools                27.2.0                   py27_1
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.3                    py27_0
sphinx                    1.5.1                    py27_0
spyder                    3.1.2                    py27_0
sqlalchemy                1.1.5                    py27_0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1               np111py27_1
subprocess32              3.2.7                    py27_0
sympy                     1.0                      py27_0
Theano                    0.9.0                     <pip>
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.8.2                    py27_0
tornado                   4.4.2                    py27_0
traitlets                 4.3.1                    py27_0
unicodecsv                0.14.1                   py27_0
vs2008_runtime            9.00.30729.5054               0
wcwidth                   0.1.7                    py27_0
werkzeug                  0.11.15                  py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        1.2.6                    py27_0
win_unicode_console       0.5                      py27_0
wrapt                     1.10.8                   py27_0
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.6                    py27_0
xlwings                   0.10.2                   py27_0
xlwt                      1.2.0                    py27_0
zlib                      1.2.8                     vc9_3  [vc9]`

**Comment by JonnasSeaworth2015** [comment]
Hi,

Is there a way to create the .anaconda directory in another place that it is not the user home directory ?
My windows is in portuguese and the path to my user includes non ascii characters but I don't have admin powers in the windows environment to change it. I installed Anaconda in a directory I created in drive D (D:\Dev ) but the .anaconda is  in my home so it does not run.

**Comment by ohTAZ** [comment]
I have completed this topic because I can change the username of my windows system, removing the non ascii characters, so I believe that one solution would be to install the .anaconda on another user, or if you can change the name by the records and forcing them to work, Look for some tutorials there. Good luck, bring us the news.

**Comment by karimandres** [comment]
Hi everyone,
I wrote a script using spyder and used a few of the libraries Anaconda comes with. I'm having this issue(This application failed to start because it could not find or load the Qt platform plugin "windows" in "". Reinstalling the application may fix this problem.) but only after converting my file to an executable file and try running it. In other words, when I run the code in spyder it works perfect and I just want to be able to have an executable file. I have very little coding experience by the way. Can anyone help? need more details?

**Comment by ThomasThelen** [comment]
It may be worthwhile linking https://github.com/ContinuumIO/anaconda-issues/issues/1270 to this

**Comment by fauskanger** [comment]
I have Anaconda3 installed on "e:\Anaconda3" and I get the same error. 

I was running ipython in the "default" env. (I'm not using Spyder)

My user folder has no non-ascii letters.

**Comment by VladLimbean** [comment]
I found out this may be an issue when your windows user contains spaces. Like, "windows user".

Removing the spaces is a solution. Ie. "windowsuser"

**Comment by ivandrucey** [comment]
I found the solution is to add this to the pyinstaller command line:
--add-data "Miniconda3/Library/plugins;plugins"

Then add this to the start of the Python code:
import sys
tmpDir = sys._MEIPASS
import os
os.environ['QT_PLUGIN_PATH'] = tmpDir + "/" + "plugins"
