### ISSUE TITLE
import error for vtk

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1757]
_From @lcebaman on May 23, 2017 14:33_

`conda install vtk` works beautifully , however we get:
```
>>> import vtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z01/z01/lcebaman/.conda/envs/e1/lib/python2.7/site-packages/vtk/__init__.py", line 58, in <module>
    from vtkRenderingFreeType import *
  File "/home/z01/z01/lcebaman/.conda/envs/e1/lib/python2.7/site-packages/vtk/vtkRenderingFreeType.py", line 1, in <module>
    from vtkRenderingFreeTypePython import *
ImportError: /usr/lib64/libxcb-xlib.so.0: undefined symbol: _xcb_unlock_io
```

_Copied from original issue: conda/conda#5409_

**Comment by nehaljwani** [comment]
@lcebaman Which Linux distribution are you using?

**Comment by lcebaman** [comment]
Cray linux
-------- Original message --------From: Nehal J Wani <notifications@github.com> Date: 6/4/17  05:58  (GMT+00:00) To: ContinuumIO/anaconda-issues <anaconda-issues@noreply.github.com> Cc: Luis Cebamanos <l.cebamanos@epcc.ed.ac.uk>, Mention <mention@noreply.github.com> Subject: Re: [ContinuumIO/anaconda-issues] import error for vtk (#1757) 
@lcebaman Which Linux distribution are you using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ContinuumIO/anaconda-issues","title":"ContinuumIO/anaconda-issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ContinuumIO/anaconda-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nehaljwani in #1757: @lcebaman Which Linux distribution are you using? "}],"action":{"name":"View Issue","url":"https://github.com/ContinuumIO/anaconda-issues/issues/1757#issuecomment-306018407"}}}
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by nehaljwani** [comment]
@lcebaman Does `conda install libxcb` solve the issue for you?

**Comment by lcebaman** [comment]
I am afraid it doesn't. I have done it, but I get the same error. Any
other ideas?

On 04/06/2017 10:59, Nehal J Wani wrote:


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ccordoba12** [comment]
I'm sorry to tell you that your distribution can't be supported by Anaconda because it uses a very old version of `libxcb` (from 2009 or even before).

**Comment by ccordoba12** [comment]
There's nothing we can do in our side. You would need to update your distribution. However, we understand that couldn't be possible.
