### ISSUE TITLE
Anaconda Command Prompt in Windows starts in Anaconda directory

### ISSUE THREAD

**Issue by mpmanti** [ContinuumIO/anaconda-issues#180]
I created an environment for Python 2.7 using Anaconda 3. The IPython interpreter correctly uses Python 2.7, but the Python interpreter uses Python 3.4.

```
C:\Users\me\AppData\Local\Continuum\Anaconda3>conda info
Current conda install:

             platform : win-64
        conda version : 3.6.4
  conda-build version : 1.8.0
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : C:\Users\me\AppData\Local\Continuum\Anaconda3  (writable)
  default environment : C:\Users\me\AppData\Local\Continuum\Anaconda3
     envs directories : C:\Users\me\AppData\Local\Continuum\Anaconda3\envs
        package cache : C:\Users\me\AppData\Local\Continuum\Anaconda3\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\Users\me\.condarc
    is foreign system : False


C:\Users\me\AppData\Local\Continuum\Anaconda3>activate py27
Activating environment "py27"...

[py27] C:\Users\me\AppData\Local\Continuum\Anaconda3>conda list
# packages in environment at C:\Users\f245355\AppData\Local\Continuum\Anaconda3\envs\py27:
#
ipython                   2.2.0                    py27_0
menuinst                  1.0.3                    py27_0
pyreadline                2.0                      py27_0
python                    2.7.8                         0

[py27] C:\Users\me\AppData\Local\Continuum\Anaconda3>python -c "import sys; print sys.version"
  File "<string>", line 1
    import sys; print sys.version
                        ^
SyntaxError: invalid syntax

[py27] C:\Users\me\AppData\Local\Continuum\Anaconda3>python
Python 3.4.1 |Anaconda 2.0.1 (64-bit)| (default, Jun 11 2014, 17:27:11) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

[py27] C:\Users\me\AppData\Local\Continuum\Anaconda3>ipython
Python 2.7.8 |Continuum Analytics, Inc.| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit()
```

**Comment by edullum** [comment]
Hopefully everyone is still around, as I am seeing this thread is dated from 2014!!
If I have installed the Anaconda software in C:\Anaconda instead of C:\Program Files (x86) where Python is installed, could this be the reason why certain packages are not seen when  using a Jupyter notebook? 
 
I am running into an issue where default site packages are no longer working in a jupyter notebook. However, when I send a script to the computer via windows cmd to install pip "package name", the package works again. Site Packages were working properly prior to yesterday. As a side note, when I launch the Jupyter notebook, I am launching it from a script:
rem -- start_ipython_notebook_here.bat ---
ipython notebook 
pause

This is what changed:

Yesterday, I ran a script via windows cmd to install a few packages and to activate a few widget extension in the jupyter notebook. Because I ran the script within windows cmd, could windows shell be taking precedence over the anaconda shell?

Troubleshooting: For the default packages that were note working, I reran the install pip "package name" in a windows shell and the package started working again, along with the new packages I installed yesterday with windows cmd.

When I look in c:\Anaconda3\Lib\site-packages the modified date for the "reinstalled" packages shows the original date that I installed the software.

This software is very new to me and I am still trying to learn the logic of it along with the process. Any help or recommendations would be greatly appreciated!

OS: Windows 7 64-bit Software: Python 3.5.2 (Anaconda3 4.1.1 64-Bit)

**Comment by mingwandroid** [comment]
The Pythons you have in `C:\Anaconda` and `C:\Program Files (x86)` are entirely independent. Anaconda's Python knows nothing of your other Python and that's good because chances are they're incompatible and would break each other.

When using `Anaconda` I recommend you always launch from the `Anaconda Prompt` or from the `Anaconda Navigator`, I also recommend that you do not let the installer add `Anaconda` to your `PATH` since it puts it at the end of `PATH` (so other things already installed take precedence) and even if it did add to the front of `PATH` that can break the already installed stuff.

I also recommend not using `pip` when using `Anaconda` Python, unless the thing you need to install is not available via `conda`.

**Comment by edullum** [comment]
Here is my concern.  I need to be able to install packages/modules on demand to 30+ computers.  I currently use Ghost Solutions Suite to distribute software.  Since there is no time to create a .msi of the module, I am sending the module out via script to each computer with the following commands:
For Anaconda package:
`conda install -c anaconda package name`
For Pythong package:
`pip install package name`

I think I know what is happening....please correct me and enlighten me if I am wrong.
I have two teachers using the same lab.  One teacher is creating a Jupyter notebook with the modules installed to the Anaconda directory and the notebook is being launched through anaconda cmd prompt.  Her notebook worked fine for the students.
The other teacher is creating a Jupyter notebook with modules installed to the python directory and the notebook is being launched through anaconda cmd prompt.  This notebook did not work fine for the students.  When the cells were run, the notebook returned an error stating that it couldn't find the modules.  This makes sense, because I was only installing the modules to the Anaconda directory.  The modules were not working, because the notebook didn't see them in the python directory, because they modules were not installed there.  Once I installed the said modules to the python directory, the notebook started working again.

Can you explain a little more detail about your second paragraph about the "PATH"?
I'm trying to understand this as best as possible.  Maybe refer me to a video that explains the difference between anaconda and python, or just the basics?

I greatly appreciate your response and guide!

**Comment by mingwandroid** [comment]
You need to simplify things here. You need to decide if you want to use normal Python or Anaconda Python and not try to use both.

I can't locate a video for you, sorry. Here someone explains a bit about `PATH` https://john-dugan.com/path-variable-in-windows/.

For the difference between Anaconda Python and Python, well, Anaconda Python is just Python but it lives in its own installation folder, usually in a subfolder called Anaconda2 or Anaconda3 in Users directory. Normal Python is often installed into `C:\Program Files`, having both can lead to trouble mostly caused by the `PATH` variable (if you google DLL hell you may find some references).

The big difference is that Normal Python uses pip to install packages, while Anaconda Python uses conda (which installs software that is part of the Anaconda Distribution). Conda is much more powerful than pip (it can install software that is exclusively Python software for example, and it has its own concept of environments which are better than virtualenv's environments). http://stackoverflow.com/a/21008900/3257826

To keep things simple, where you can you should use Anaconda Python and conda exclusively and not even install Normal Python since everything it can do, Anaconda Python can also do (though someone who doesn't work on Anaconda might have a different opinion).

**Comment by edullum** [comment]
Thank you for the information!
I found this blerb that might help me in this situation:

**Comment by edullum** [comment]
Thank you again for the clarification!

I revisited how I installed Anaconda3 4.3.0 and during the installation I enabled both options:
Add Anaconda to the system PATH environment variable and
Register Anaconda as the system Python 3.6

I checked the environment variable on my image station and lab computers and found that both python and anaconda are in there (I removed the other variables due to their irrelevance on this topic):
C:\Program Files (x86)\Python35-32\Scripts\;C:\Program Files (x86)\Python35-32\;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin

Could the issue be occurring because the one teacher created a Jupyter notebook using normal Python and the computers that are trying to work in the notebook have Anaconda’s python as the default?  What I see happening in the notebook, is that when the notebook calls for a package it is pointing to the package library where normal Python is installed.  Because of this, is it possible that now the normal python is taking precedence over Anaconda’s Python?

**Comment by mingwandroid** [comment]
You need to uninstall your normal Python and remove it from your `PATH`.

I would also recommend (and have already recommended: https://github.com/ContinuumIO/anaconda-issues/issues/180#issuecomment-283043773) you *not* to add Anaconda to your PATH for the reasons I stated earlier (DLL hell, breaking other software). Instead, from the `Start Menu` use the `Anaconda Prompt` or `Anaconda Navigator`.

VS and PTVS are fine, no need to do anything with them.

**Comment by ChrisBarker-NOAA** [comment]
KInd of off-topic, but I happened to notice this (looking for an answer to another question):

> The other teacher is creating a Jupyter notebook with modules installed to the python directory 

REgardless of Anaconda vs system Python, etc, this is not a good way to manage shared code. RAther than trying to put the modules (packages) in a particular dir, and have the notebooks run from there, you should make a proper python package of teh code, so it can be imported from everywhere.

See: http://pythonchb.github.io/PythonTopics/where_to_put_your_code.html

for some thoughts on the easiest way to do that.
