### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by lonelylingoes** [ContinuumIO/anaconda-issues#1932]
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),),)

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment]
Transient error

`HTTP errors are often intermittent, and a simple retry will get you on your way.`

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Comment by Thinker2011** [comment]
it is not work at all！ ‘’conda update anaconda-navigator‘ itself return the same connection error. No button to update the anaconda-navigator!

**Comment by seagu11** [comment]
I'm having the same issue as Thinker2011. Does anyone have a fix or update as `conda update anaconda-navigator` is not working for me.

**Comment by licrystal** [comment]
it is not work at all！ ‘’conda update anaconda-navigator‘  returns the same connection error. No button to update the anaconda-navigator!

**Comment by PhilippeRaemy** [comment]
I had a similar issue and found out that it was caused by a network connectivity error. Adding the right proxy on .condarc file solved it.
please see https://stackoverflow.com/questions/31099279/running-conda-with-proxy

**Comment by fonnesbeck** [comment]
Trying to update anaconda-navigator failed:

```
conda update anaconda-navigator

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/fonnescj/anaconda3/envs/dev
  package name: anaconda-navigator
```

I am able to run anaconda-navigator, so it is installed. However, trying `install` rather than `update` results in:

```
Fetching package metadata .......
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103eabe48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)
```

**Comment by fonnesbeck** [comment]
Note that even creating a new environment fails, for the same reason:

```
conda create -n foo python=3.6  
Fetching package metadata .......
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1092a0ba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)
```

**Comment by louispotok** [comment]
FWIW, I am experiencing the same problem running miniconda on a Linux terminal. I don't think I even have Navigator installed. (Trying to `conda update anaconda-navigator` gives the same error as @fonnesbeck reported).

**Comment by fonnesbeck** [comment]
Yes, my issue was due to the .io nameservers incident. Just happened to coincide with a OS update!

**Comment by sowmiyanm** [comment]
`conda update navigator-updater `
is also not working and failing with condaHTTP error

I am not able to update any packages, this is happening after upgrading to Mac High Sierra

**Comment by adithyaonline** [comment]
I tried to update conda navigator as suggested above 
``` 
~ $ conda update anaconda-navigator
Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/osx-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)
```

any suggestions on how to fix this ?

**Comment by kleinash** [comment]
> I tried to update conda navigator as suggested above
> 
> ```
> ~ $ conda update anaconda-navigator
> Fetching package metadata ...
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/osx-64/repodata.json.bz2>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)
> ```
> any suggestions on how to fix this ?

Have you set your proxy on your system?

**Comment by adithyaonline** [comment]
it got resolved... not sure what was wrong though
it threw this error when I was connected on work wifi
but it ran without errors when I tried at home wifi.. something ISP specific I think.. weird

**Comment by liutianchen** [comment]
**Most people agree with that the reason why conda cannot download anything or connect to pycharm is the MISSING OF SSL MODULE of python, because conda use it's own ssl module rather than system ssl, which never happens to mac. From my point of view, it's not a good design because there is not enough evidence but convenient enough for the developers from conda that independent ssl module is better, software shouldn't step over the operating system**

**Comment by mingwandroid** [comment]
> Most people agree

Please show evidence of this claim.

> with that the reason why conda cannot download anything or connect to pycharm is the MISSING OF SSL MODULE of python, 

I am sorry but computers are, to a reasonable level of abstraction, predictable machines. There is no election or referendum to be had to determine the reason for a given failure, only investigation and debugging. In other words this is in the domain of facts not that of opinions.

Conda can both download software and interact with pycharm just fine. 

> because conda use it's own ssl module rather than system ssl, which never happens to mac.

Sorry this is incorrect. Software is software. You have created an artificial distinction between system and non system software, why? In other words, why should python be considered non-system and ask considered system? And would that categorization be globally applicable or just an opinion? I believe it is just the latter.

Are you aware that you can also install openssl via homebrew?

**Comment by liutianchen** [comment]
I am talking about the SSL problem, conda itself definitely can both download and interact with pycharm, but with SSL problem, it cannot. Sorry for my shallow knowledge about the design of the SSL module in conda.
First, I meet the SSL problem when I try to connect with PyCharm or try to download some package like numpy in Anaconda Prompt. Why it report that python cannot load SSL module？From the structure point of view, python installed by conda definitely is compiled with SSL enable option, if it cannot find SSL module but python is SSL-enabled, where is the SSL module?
Second, because of the feature of the system structure, in *nix system, SSL module is an soft link lib, as long as the lib is specified and conda could find the path from sys environ variable or some circumstance temp environ. That is clear in any *nix, but in windows, I have no idea how could conda cannot find SSL module when windows support SSL.

**Comment by liutianchen** [comment]
I have been tired about debug conda with the SSL problem. The reason why I said conda use itself's SSL module rather than system module is I have found many documents with the same description. Maybe those documents are unreliable and I trust them without practical evidence. If there isn't the problem then I am wrong.But I think to solve the problem exceeds my ability, so I will continue with other python framework.

**Comment by liutianchen** [comment]
OMG. I mistake

**Comment by liutianchen** [comment]
OMG, I use the word 'agree' by mistake, I mean "many people meet the problem that they cannot download or connect to pycharm, and it reports the ssl module is missing so download or connect failed."

**Comment by liutianchen** [comment]
And many people agree with that conda use it's own ssl module rather than system ssl on windows, which never happens on mac. Because I found many people said the same version of conda installed on windows and mac under same network condition. windows meet ssl problem, mac does not.
Sorry for my expression, poor English.

**Comment by Isaac-Zarspada** [comment]
having same issue -- tried updating navigator
`C:\Users\<USER>conda update anaconda-navigator
Collecting package metadata (current_repodata.json): failed

CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.

Exception: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))`

**Comment by Gelesh** [comment]
2/25/2023 Stilll Issue !!

**Comment by Gelesh** [comment]
Tried .. Anaconda Navigator Update, and then _conda update anaconda-navigator_ Now, I see progress in Conda Updates .Thanks !!
