### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by inthiyan** [ContinuumIO/anaconda-issues#1981]
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "//anaconda/bin/spyder", line 4, in <module>
    import spyder.app.start
ImportError: No module named 'spyder.app'; 'spyder' is not a package

```
## System information
```
platform: osx-64
pyqt: 5.6.0
conda: 4.3.21
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
python: 3.5.3
version: 1.6.2
qt: 5.6.2
```

**Comment by goanpeca** [comment]
IGNORE THIS

**Comment by inthiyan** [comment]
Hi Gonzalo,

Any help with this?

**Comment by goanpeca** [comment]
@inthiyan it seems spyder was not correctly install, unistall and reinstall on Navigator or try in the terminal to run

```
$ conda install spyder
$ conda install spyder -f
```

**Comment by JBauerKogentix** [comment]
Uninstalled, reinstalled, both from Navigator and conda; tried 3.2.7 instead of 3.2.8, also tried to launch Spyder from Terminal:

Traceback (most recent call last):
  File "/Users/JohnBauer/anaconda3/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/JohnBauer/anaconda3/bin/spyder.py", line 7, in <module>
    from spyder.app.start import main
ModuleNotFoundError: No module named 'spyder.app'; 'spyder' is not a package

Clearly more needs to be done than uninstalling and reinstalling.  Also Spyder was working until Navigator updated itself (twice).

**Comment by JBauerKogentix** [comment]
Also tried ```conda update python.app``` from #8103 with no success.

**Comment by JBauerKogentix** [comment]
happened again.  Updated Navigator to 1.8.7; updated Spyder to 3.3.0, still doing it.

**Comment by wickedlester** [comment]
I also have this problem with anaconda 1.8.7 and spyder 3.3.0. It was working before the 1.8.7 update.

**Comment by gerroon** [comment]
Same problem, I installed it using pip install spyder

**Comment by tankxie** [comment]
run 

`conda update --all`

can solve this problem！

**Comment by gerroon** [comment]
thanks, I do not use conda myself

**Comment by YuehLinChung** [comment]
I do have this issue, too.
And I found that there are many spyder packages in my system

First, I run `ipython` in anaconda-prompt with env (base).
Then I `import spyder`, and type `spyder`
And it said that the spyder module is in the path `C:\Users\user\AppData\Roaming\Python\Python37\site-packages\spyder`
Then I found that there is no `app` module in this directory!
So I delete the whole `spyder` folder then the import path redirect to my anaconda path.
And the issue was solved.
Hope this helps.
