### ISSUE TITLE
Add %LIBRARY_BIN% to PATH on windows

### ISSUE THREAD

**Issue by ddale** [ContinuumIO/anaconda-issues#233]
Some anaconda windows packages, for example zlib and libpng, install dlls in `%PREFIX%\Library\bin`. This directory must be included on the `%PATH%`, or Windows will be unable to load the dlls. However, the [ana|mini]conda installers do not add this directory to the `%PATH%`, nor does the `activate` command.

**Comment by ilanschnell** [comment]
Here is my email response regarding this issue for reference:

I want to give some background on why LIBRARY_PREFIX exists and why LIBRARY_BIN is not currently added to the PATH.  We noticed that there where certain packages on Windows which needed to be created using Unix tools, and followed the include/bin/lib directory structure.  Because there are already all sorts of files in the regular prefix, we decided to add <prefix>\Library for those types of things, and the name 'Library' comes from the fact that the packages installed into this location are usually libraries, which are only used to support other packages.  It was decided that this would be a standard location, but only for the purpose of build dependency packages.  That means, whenever a (user) package requires a 'Library', it would either statically link or copy files from the "Library" package.  If you install Anaconda on Windows, you might have noticed that there isn't even a <prefix>\Library directory, because its purpose was merely for those build dependencies.

**Comment by tadeu** [comment]
The binaries from `hdf5` package (1.8.15.1 build 2) are installed into LIBRARY_BIN, is the package wrong?

**Comment by tadeu** [comment]
@ilanschnell The [documentation](http://conda.pydata.org/docs/building/environment-vars.html#environment-variables-set-during-the-build-process) seems to be confusing, could you please clarify it?

It says

> When building “Unix-style” packages on Windows, which are then usually statically linked to executables, we do this in a special _Library_ directory under the build prefix.

but according to your reply, this is not about unix-style packages, but about static libraries (or even header-only libraries) that are _build_ dependencies _only_.

**Comment by ChrisBarker-NOAA** [comment]
This is all well and good -- Library is supposed to be where bulid-time dependencies are put, And a number of libs create both libs and .dlls when built, so dlls end up there, even when not intended.

But I thought the whole point of conda was, to well, manage pacakges -- so it SHOULD be abel to support providing dlls for stuff (like libpng, etc,) that multipel other pacakges might want to use -- why have them all statically lnk?

So where should dlls that are intended to be shared by other conda-managed packages go??

( and #509 seems to indicate that Library/lib (or bin or ???) will be used that way now -- but I lost track of the discussion)

**Comment by msarahan** [comment]
Currently, here is the scheme (mostly the library folder mimics Unix):

Library/bin: executables and dlls
Library/lib: import libraries and static libs (both are .lib)
Library/include: headers

Note that there is no lib32/lib64 - that is determined by the root installation.

We anticipate conflicts at some point. When that starts to become an issue, we will embed paths in executables, either by patching source code, or by emerging manifests.

**Comment by jrovegno** [comment]
Only for reference purpose I leave the code of one batch file saved in Scripts/ to add LIBRARY_BIN to PATH. In my case with this I can use some useful tools installed in Library/bin like sqlite3.

```
@echo off

for %%i in ("%~dp0..") do (
    set ANACONDA=%%~fi
    )

set LIBRARY_BIN=%ANACONDA%\Library\bin
set "PATH=%LIBRARY_BIN%;%PATH%"

echo Added %LIBRARY_BIN% to PATH.

```
