### ISSUE TITLE
Change IPython start directory

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#239]
I was talking with @ellisonbg and he really wants to change the default directory that the notebook starts in in Windows, to either the My Documents directory or the home directory.

**Comment by ellisonbg** [comment]
The notebook now has a file browser and a text editor, so most users are
starting the notebook server in their home directory.

On Sat, Jan 10, 2015 at 11:27 AM, Aaron Meurer <notifications@github.com>
wrote:

> I was talking with @ellisonbg <https://github.com/ellisonbg> and he
> really wants to change the default directory that the notebook starts in in
> Windows, to either the My Documents directory or the home directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuumIO/anaconda-issues/issues/239>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by asmeurer** [comment]
My biggest concern here is for the very low tech user who updates this and can no longer find his notebooks, because the starting directory changed.

**Comment by sclarke** [comment]
I like the idea of moving the default directory also. Starting in the `%USERPROFILE%\.ipython` directory is counter-intuitive; users I encounter usually prefer for their ipynb files to be stored with the rest of their documents. A separate, but related issue is how to control which environment the notebook is run under. I'm not sure the best practice I'm not sure the best practice, but I've put a shortcut in my startup folder with *Target* == `%LOCALAPPDATA%\Continuum\Anaconda3\Scripts\activate.bat scipy34 && ipython notebook --no-browser` and *Start In* == `%HOME%\Documents`.

**Comment by ellisonbg** [comment]
We have long been recommending that no one ever uses the Anaconda Launcher
because of this problem.

Yes, I agree that for existing users that already have notebooks in this
directory, there will be a period of transition, but users being addicted
to something broken should not ever be a reason to not fix it.

Our request to change this to the home directory comes directly from
working with new users and doing informal usability testing with these
users.

* When we are working with new users, one of this big ideas we want them to
understand is that "notebooks are just files". We encourage students to
treat them as files, organize them into directories, put them in their
Dropbox folder, save them in git repos, etc. Having a special directory
where all of their notebooks goes violates this abstraction and confuses
them - "if they are files, why can't I put them in my Dropbox folder" "Why
can't I use the notebooks that I just downloaded and put on my Desktop"
* Inconsistency. This choice of the Launcher is only made on Windows. On
Mac the notebook starts in their home directory. When you have a large
group of new users, it is horribly confusing to the Windows users that they
can't see their files, but everyone on Mac, Linux or those who don't use
the Launcher can.
* Prototypicality. Usability research has shown that prototypicality is an
important aspect of building pleasant and easy to use software. By this, I
mean that a document based system should behave like other document based
systems. A website for commerce, should behave like other commerce
websites. All document based systems (Word, Excel, Pages, Keynote, Adobe
Illustrator, etc.) give the user full freedom to store documents in any
directory they have permissions to access. Diverging from that is horribly
confusing to users.

If this isn't fixed in the Launcher, we will simply continue to tell all
IPython users to never use the Launcher.




On Sat, Jan 10, 2015 at 8:36 PM, Aaron Meurer <notifications@github.com>
wrote:

> My biggest concern here is for the very low tech user who updates this and
> can no longer find his notebooks, because the starting directory changed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuumIO/anaconda-issues/issues/239#issuecomment-69483416>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by tswicegood** [comment]
@ellisonbg -- thanks for the feedback.  I'm working on a pretty big iteration of the Launcher and I'll definitely take this into account.

**Comment by ellisonbg** [comment]
Thanks!

**Comment by srdawes** [comment]
How do you start iPython on a PC where the Documents folder is on the D drive? iPython complains about C:\Users\<my name>\My Documents and says it doesn't exist. I'm starting it from the Launcher.

**Comment by srdawes** [comment]
How do you start iPython on a PC where the Documents folder is on the D drive? iPython complains about C:\Users<my name>\My Documents and says it doesn't exist. I'm starting it from the Launcher.

**Comment by srdawes** [comment]
I found the solution was to edit the IPython Notebook shortcut start in location and forget using the launcher. That seems to be broken for non-standard installations.
