### ISSUE TITLE
Add Qt Designer on Anaconda

### ISSUE THREAD

**Issue by cdpango** [ContinuumIO/anaconda-issues#251]
Hi, could anyone tell me whether the Qt Designer is installed with the Anaconda 2.1 for mac? I can not find it anywhere. And if not installed, how to install it?
Thanks in advance!

**Comment by ccordoba12** [comment]
To answer your questions:

> could anyone tell me whether the Qt Designer is installed with the Anaconda 2.1 for mac?

No, it's not installed along with Qt for any platform. I'm not entirely sure why that's the case, but it's most probably done to save compile time and to avoid creating a bigger package.

> how to install it?

There is no way no install through Anaconda, sorry. Also, it's not possible to use it from another Qt installation because Qt crashes when mixing libraries of different versions.

**Comment by ccordoba12** [comment]
I'll see if there is a way to improve this for the next Anaconda release

**Comment by Nodd** [comment]
QtDesigner is present in `Library\bin\designer.exe` when qt is installed, but there is no shortcut created so it's a bit hidden. There are other very useful executables here, such as `pyuic5` to compile `.ui` files to `.py`.

**Comment by mingwandroid** [comment]
The issue reported here is closed. If you want to requires QtCreator please open another issue.

**Comment by melMass** [comment]
It does not compile the pyqt Designer plugin to allow custom pyqt widgets in Designer
