### ISSUE TITLE
Can't launch the Spyder on Windows if other scientific distributions (WinPython, PythonXY) are installed

### ISSUE THREAD

**Issue by koreantramp** [ContinuumIO/anaconda-issues#264]
Hi~

As you seen on the title,
I've got a problem to open a Spyder app on Windows 8.1.
The system features are
- Windows 8.1 x64
- RAM: 4GB

I installed Anaconda(Anaconda-2.1.0-Windows-x86_64.exe) on the system.
And I excuted a Spyder.exe then nothing happened on the system.
What the problem is?

**Comment by ccordoba12** [comment]
Could you explain a bit further how you tried to execute spyder? For example, where did you find `spyder.exe`?

If you can't start Spyder using the Anaconda launcher (something that it's a known problem, soon to be fixed), you need to open a terminal (i.e. `cmd.exe`) and write this commands:

    spyder

Then it should start normally.

**Comment by mountaindust** [comment]
I've been hunting this bug all day on a similar system - Windows 8.1 x64, Anaconda was recently installed for all users at C:\Anaconda - and I have found a different issue and (finally) a corresponding solution.

Symptoms:
-- Start menu shortcut for spyder -> nothing happens. (this is because pythonw.exe runs in the background, so you don't see the traceback.

-- Running spyder.exe by double clicking in Windows explorer at C:\Anaconda\Scripts does nothing either.

-- If you open a terminal (cmd.exe) and try running spyder, NOT NECESSARILY as per ccordoba12 above, but via typing in the full path of spyder.exe (i.e. C:\Anaconda\Scripts\spyder.exe) you finally get an error message:
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 91, in main
    from spyderlib import spyder
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 101, in <module
>
    from spyderlib.qt.QtGui import (QApplication, QMainWindow, QSplashScreen,
  File "C:\Anaconda\lib\site-packages\spyderlib\qt\QtGui.py", line 10, in <modul
e>
    from PyQt4.Qt import QKeySequence, QTextCursor  # analysis:ignore
ImportError: cannot import name QKeySequence

-- You previously or currently have another Python distribution on your computer. In my case, it was a WinPython distribution that I had once registered with the system. This meant that opening up cmd.exe and just typing spyder actually worked... it launched spyder from the portable WinPython distribution sitting somewhere else on my computer, not from Anaconda.

Solution:
If another python distribution is registered with the system, its directories are listed in the system variables Path, likely in an order so that the system searches there before in the Anaconda folders. You can verify this by going to Advanced system settings in PC Info or Control Panel->System, Environment Variables, and look under System Variables for Path. Click and hit Edit. You get a possibly long semi-colon list of directories. Look for those belonging to another python distribution and delete only those, so that everything else including the Anaconda folders remain. It might also be possible to just reorder so that the Anaconda folders are first. I haven't tried this.

Now restart your computer to reload the Path variable and check that everything works.

**Comment by koreantramp** [comment]
I typed a command on cmd.exe like 'spyder.exe' and then
below comments shows up.

--------------
C:\>spyder
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 1, in <module>
    from spyderlib import start_app
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 14, in <modu
le>
    from spyderlib.config import CONF
  File "C:\Anaconda\lib\site-packages\spyderlib\config.py", line 22, in <module>

    from spyderlib.utils import iofuncs, codeanalysis
  File "C:\Anaconda\lib\site-packages\spyderlib\utils\iofuncs.py", line 26, in <
module>
    import pandas as pd
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 41, in <module>
    from pandas.core.api import *
  File "C:\Anaconda\lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "C:\Anaconda\lib\site-packages\pandas\core\groupby.py", line 15, in <modu
le>
    from pandas.core.frame import DataFrame
  File "C:\Anaconda\lib\site-packages\pandas\core\frame.py", line 38, in <module
>
    from pandas.core.series import Series
  File "C:\Anaconda\lib\site-packages\pandas\core\series.py", line 2524, in <mod
ule>
    import pandas.tools.plotting as _gfx
  File "C:\Anaconda\lib\site-packages\pandas\tools\plotting.py", line 26, in <mo
dule>
    import pandas.tseries.converter as conv
  File "C:\Anaconda\lib\site-packages\pandas\tseries\converter.py", line 7, in <
module>
    import matplotlib.units as units
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 1048, in <mo
dule>
    rcParams = rc_params()
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 897, in rc_p
arams
    fname = matplotlib_fname()
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 759, in matp
lotlib_fname
    configdir = _get_configdir()
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 630, in _get
_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 555, in _get
_xdg_config_dir
    path = get_home()
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 323, in wrap
per
    ret = func(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\matplotlib\__init__.py", line 509, in _get
_home
    path = os.path.expanduser("~")
  File "C:\Anaconda\lib\ntpath.py", line 310, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 9: ordinal
not in range(128)
---------------------
"UnicodeDecodeError~~~"
What is this?  -_-;

**Comment by ccordoba12** [comment]
@koreantramp Just run

    conda install matplotlib

to fix this problem

**Comment by ccordoba12** [comment]
Our docs should mention that :-)

**Comment by tswicegood** [comment]
@ccordoba12 is this a case of a missing dependency in the package?  /cc @ilanschnell

**Comment by ccordoba12** [comment]
@tswicegood nop, according to @mountaindust, the problem was he had WinPython before installing Anaconda, so Anaconda put itself *after* WinPython in `PATH`.

That messed libraries from both distros and led Spyder to crash. So I think the solution is to mention in our docs that users need to uninstall other scientific distributions before installing Anaconda.

**Comment by tswicegood** [comment]
Gotcha, @ccordoba12!  I was confused by the `conda install matplotlib` line above.

**Comment by ccordoba12** [comment]
That's another error reported by @koreantramp, solved by updating matplotlib

**Comment by mountaindust** [comment]
As a side note, it might be worth testing that unregistering WinPython clears it from PATH. I have a nagging feeling that I did unregister the distribution from windows before installing Anaconda, as evidenced by the fact that context menu entries such as 'Edit with IDLE' are gone. These are added when you register WinPython, and are supposed to disappear upon unregistration.

I can't be 100% sure however, because I have both a 32bit and 64bit WinPython sitting on my hard drive. So I could have performed the incredibly unintelligent act of registering one and unregistering the other?

Also interesting: in the "Do you want to continue?" dialogue for registering a WinPython distribution, it says:
Warning: the only way to undo this change is to register another Python distribution to the Windows registry.

I'm not sure what exactly this refers to, since of course you have the option to unregister from the WinPython Control Panel as well. Maybe it speaks of the sentence "If pywin32 is installed (it should be on any WinPython distribution), the Python ActiveX Scripting client will also be registered."?

**Comment by ccordoba12** [comment]
Another one for you @kerrywatsonking. Of course, when you have some time :-)

**Comment by ccordoba12** [comment]
@kerrywatson1, what about this one?

**Comment by kerrywatson1** [comment]
@ccordoba12 let me summarize and see if I have this right: 

For -- Anaconda Troubleshooting page.
Problem: Can't launch X scientific package on Windows if other scientific distributions (WinPython, PythonXY) are installed first. 
Solution: run conda install [packagename] to change the install path to the correct location. The previous installation likely is going to the wrong path. 

Please confirm or edit and I'll take care of this.

**Comment by kerrywatson1** [comment]
@asmeurer will you add this (edit if needed) to the Anaconda Troubleshooting page?
Problem: 
Can't launch X scientific package on Windows if other scientific distributions (WinPython, PythonXY) are installed first. 

Solution: 
Run conda install [package1 package2] to change the install paths to the correct location. Install all packages at the same time to avoid this issue.

Please confirm or edit and I'll take care of this.

**Comment by ccordoba12** [comment]
@kerrywatson1, I think the recommendation should be:

*Please uninstall other Pyhton scientific distributions on Windows (like WinPython and PythonXY), before installing Anaconda or Miniconda. Several unexpected problems can arise if you don't follow this advice.*

I think conda can't fix installation paths by itself :-) So people needs to uninstall other distributions first. IMO that's the best recommendation in this case.

**Comment by kerrywatson1** [comment]
See my reply sent at same time. I am already adding to docs minimum disk
space recommendations with new "Before you start" sections, and we can
expand the internal help (which also goes to website reference) on conda
clean. But prevention is most important with adequate warning and error
messages.

**Comment by ccordoba12** [comment]
I think you answered to the issue about `conda clean` ;-)

**Comment by yzy123456** [comment]
My Anaconda Spyder can not use, I have seen your explanation above, it also try to install the Matplotlib, but still can not use, I enter the Spyder in the CMD, there will be the following error：
![image](https://cloud.githubusercontent.com/assets/11597156/7507008/5c9d9f72-f49b-11e4-8c8f-e066b720cbd9.png)

**Comment by yzy123456** [comment]
can you help me？thanks@ccordoba12

**Comment by yzy123456** [comment]
![Uploading image.png…]()

**Comment by yzy123456** [comment]
![image](https://cloud.githubusercontent.com/assets/11597156/7507044/02c76e1e-f49c-11e4-8f59-3640b1bc2448.png)

**Comment by stephenshank** [comment]
In case this might help to anyone in the future reading this, I was running into the same error message on OS X and
`conda install pyqt`
fixed it for me.

**Comment by BigdataHelwan** [comment]
@ccordoba12 I 've been using Spyder for over 3 months. but suddenly and from nowhere it's not working anymore. I tried `spyder `command at the `cmd.exe` and that what I get. Please help!

```
C:\Users\Eng.Adel>spyder
Traceback (most recent call last):
  File "C:\Users\Eng.Adel\Anaconda2\Scripts\spyder-script.py", line 1, in <module>
    from spyderlib import start_app
  File "C:\Users\Eng.Adel\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 13, in <module>
    from spyderlib.config import CONF
  File "C:\Users\Eng.Adel\Anaconda2\lib\site-packages\spyderlib\config.py", line 736, in <module>
    subfolder=SUBFOLDER, backup=True, raw_mode=True)
  File "C:\Users\Eng.Adel\Anaconda2\lib\site-packages\spyderlib\userconfig.py", line 215, in __init__
    self.load_from_ini()
  File "C:\Users\Eng.Adel\Anaconda2\lib\site-packages\spyderlib\userconfig.py", line 260, in load_from_ini
    self.readfp(configfile)
  File "C:\Users\Eng.Adel\Anaconda2\lib\ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "C:\Users\Eng.Adel\Anaconda2\lib\ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: C:\Users\Eng.Adel\.spyder2\spyder.ini
        [line 19]: u'window/pre'



```

I am using Windows 8.1 64-bit machine

**Comment by ccordoba12** [comment]
@BigdataHelwan, I still don't understand why our config files end up corrupted, which is what's happening in your case.

Please run

    spyder --reset

to fix your problem :-)

**Comment by BigdataHelwan** [comment]
@ccordoba12 , It's giving me the same error again.

**Comment by ccordoba12** [comment]
Please remove manually this directory then

    C:\Users\Eng.Adel\.spyder2

and try again

**Comment by BigdataHelwan** [comment]
I've made an edit in `spyder.ini` deleting `window/pre` and it worked!

**Comment by pinedoj** [comment]
I follow instructions and not worked
try conda install spyder-app
this works for me I also had the same problem on a Win10 64 bit system and fixed as well

**Comment by prachiprakash26** [comment]
Hi,
Recently downloaded Anaconda from  http://continuum.io/downloads. My PC is Windows 8.1 64 bit. On opening Spyder, when I click on File -> Open File or try to save the .py file created, Spyder crashes. In short, File explorer in Spyder is not working.

Please help.
Thanks.

**Comment by pinedoj** [comment]
Hi prachiprakash26  try opening a conda prompt and then type conda install spyder-app

**Comment by prachiprakash26** [comment]
Hi,
Thanks so much for the help. I was stuck with this issue for quite a long
time. Finally, got the accurate help. Really appreciate your help.

Thanks.

**Comment by growNeha** [comment]
I am not able to launch spyder, neither navigator. 
when i try to open through cmd it says the following:

![image](https://cloud.githubusercontent.com/assets/19632369/21448483/292cd0d8-c909-11e6-9e1c-e90027db65c3.png)

**Comment by ccordoba12** [comment]
Please install Anaconda for your user instead of for all users and try again.

**Comment by growNeha** [comment]
I have installed anaconda for all users.

**Comment by ccordoba12** [comment]
That's what I could guess, but I'm asking you to uninstall Anaconda and re-install it only for your user and try again.

**Comment by lightbearer88** [comment]
Hi,

I just downloaded Anaconda3-4.3.0.1 for Windows x86 64-bit. I installed it but when I try to launch Spyder (from Navigator or from cmd.exe) it doesn't launch.

I have been reading over this post as well as a google groups post and tried many things but they are not working. So I uninstalled Anaconda as well as any other python on my computer, and reinstalled Anaconda.

Same problem. I did spyder --reset and it gave me the error shown in sc1.png.


![sc1](https://cloud.githubusercontent.com/assets/7364673/23009303/30c45b22-f3e3-11e6-87cd-ae02c934c71f.PNG)



I then tried conda install spyder-app and I got the error shown in sc2.png


![sc2](https://cloud.githubusercontent.com/assets/7364673/23009308/355d2dee-f3e3-11e6-8f33-02b8467b1e6b.PNG)



I also tried deleting the entire spyder.lock folder under .spyder-py3 and it also does not work.

I think I more or less exhausted my options. Any advice on what to do next is appreciated.

**Comment by ccordoba12** [comment]
I think the problem is the apostrophe in your user name. So please change it from Ian's to simply Ian

**Comment by lightbearer88** [comment]
Yeap, that did the trick, thanks! It is quite a weird bug.

**Comment by ccordoba12** [comment]
Thanks for letting know about it.

**Comment by WFathy** [comment]
I tried to run it through cmd but it gave message "python stopped working"
I removed ./python-py3

and typed conda install spyder-app
it gives a message:
UnsatisfibleError: The following specifications were found to be in conflict:
seaborn
spyder-app
tenserflow-base
