### ISSUE TITLE
Spyder and pythonw.exe not work under Windows7 Professional

### ISSUE THREAD

**Issue by halleygithub** [ContinuumIO/anaconda-issues#318]
Anaconda 2.0.0 (64-bit),  

double click "pythonw.exe" no response. 

Type "python", console shows this :

E:\>python
Python 2.7.6 |Anaconda 2.0.0 (64-bit)| (default, May 27 2014, 15:00:33) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io and https://binstar.org

Type "spyder" or "spyder --show-console" or " spyder --defaults", something is running behind , after a while, the console is ready to accept new command again, nothing happen,  spyder window not appear.

The spyder works well before, but after I uninstall Annaconda (antivirus software suggestion) and reinstall again, I meet above problem. Please help .

**Comment by ccordoba12** [comment]
Try to run

    spyder --reset

and run spyder again to see if that helps

**Comment by halleygithub** [comment]
I try "spyder --reset", computer runs for a while before the console response. But after that,  spyder still fail to pop up the window.

**Comment by ccordoba12** [comment]
Ok, then please run in terminal this command

    spyder --show-console

and if an error message is generated, please copy and paste it here :-)

**Comment by halleygithub** [comment]
E:\App\FinReporter>spyder --show-console

E:\App\FinReporter>spyder --show -console
Usage: spyder [options] files

spyder-script.py: error: no such option: -c

**Comment by ccordoba12** [comment]
`--show-console` doesn't have any space between the words. That's why you're getting the second error.

I assume you're not seeing any error in the terminal after running

    E:\App\FinReporter>spyder --show-console

Then I don't know how I can help you :-(

**Comment by PertuyF** [comment]
Hello,

I have the exact same issue using Anaconda with python 3.4 and spyder 2.3.8 under windows 10.
It appeared suddenly after I used "conda update conda" and "conda update anaconda" and then installed a package using pip.

When launching spyder windows pops an error message saying "python.exe has stopped working" or "pythonw.exe has stopped working". It always happens when spyder splash displays "loading online help".

I restarted the computer twice when trying to restore spyder.

I tried:
- unistalling/reinstalling spyder
- downgrading to spyder 2.3.6
- running "spyder --reset" or "spyder --defaults" commands
- starting with "spyder --new-instance" command
- starting with "spyder --show-console" command

None will change anything.
Any idea ?

**Comment by msarahan** [comment]
Please post the output of ```conda list``` so we can see if anything might be causing issues.

**Comment by PertuyF** [comment]
Hi,
Sorry for the delay.
I finally uninstalled and reinstalled Anaconda to get it working.
That's dirty, but it worked.

Anyway, thanks for your interest!
Happy new year 2016!

**Comment by ccordoba12** [comment]
Thanks for letting us know about it :-)
