### ISSUE TITLE
Failed to create anaconda menus

### ISSUE THREAD

**Issue by jrogerio69** [ContinuumIO/anaconda-issues#3488]
I downloaded the file Anaconda3-4.4.0-Windows-x86_64 to install python in my notebook. At the end of installation I received the message "failed to create anaconda menus", with the options "abort", "retry" and "ignore", a tried retry option, without any success, so a choose the option "ignore" and the installation finished. The problem is that when I starting Anaconda Navi I got a error message "This application failed do start because it could not find or load the Qt platform plugin "windows" in "". Reinstalling the application my fix the problem".

I already had tried to reinstall Anaconda many times, without any success.  

I'm using Windows 10 64-bit.
 
Does anybody can help me?

Thanks!

**Comment by mingwandroid** [comment]
Please run the `Anaconda Prompt` from the `Start Menu` and show the result of each of the following:

```
where Qt5Core.dll
where Qt5Gui.dll
echo %PATH%
dir %SYSTEMROOT%\System32\*.dll
```

**Comment by jrogerio69** [comment]
Thank you for the help.
I have created four files. One for each command. See then attached please
[result1.txt](https://github.com/ContinuumIO/anaconda-issues/files/1171539/result1.txt)
[result2.txt](https://github.com/ContinuumIO/anaconda-issues/files/1171540/result2.txt)
[result3.txt](https://github.com/ContinuumIO/anaconda-issues/files/1171541/result3.txt)
[result4.txt](https://github.com/ContinuumIO/anaconda-issues/files/1171542/result4.txt)

**Comment by bigdavek** [comment]
I am extremely new to all of this (Github, Python, Anoconda, etc).  I've looked through all these articles about the "Failed to create Anaconda menus" issue.  I've uninstalled/reinstalled, uninstalled other programs, and been working on it a while.  Just tried installing it for all users and it worked!!!  Hope that helps someone.  THANK YOU so much to everyone who's posted stuff to help out on this!

**Comment by jrogerio69** [comment]
Hello guys, any help with this?

**Comment by bigdavek** [comment]
Wish I could.  I was able to install it only by finally installing it for
"all users".  I'm not nearly qualified to be able to tell you where to put
those .dll files.  I'm really new to this.  Good luck though!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by otbu** [comment]
**Possible solution found**

I had the same problem. I would get "failed to create anaconda menus" in a dialog box. This is also just happened with the latest miniconda3 4.3.30.2 x64 installer. It might be some collision with already existing .dll-files. I have development files for Qt 5.9.x installed with the path to the msvc2015_x64 build available in PATH for my windows user. There is also a Qt5Core.dll in my cmake-installation which is also in PATH.

I got it working though - by opening up cmd and using `set path=` before anything else. This clears all paths for this session of the command prompt. After this you call the installer directly from the command line. The installation (local user, not all users) finished with no problem this time. Seems to be working fine.

**Comment by ldbader** [comment]
On one laptop, we had the "Failed to create menus" dialog box while running Anaconda3-5.0.1-Windows-x86_64.exe.  Using the Windows 10 command prompt, entering **set path=**, and then running Anaconda3-5.0.1-Windows-x86_64.exe at the prompt fixed our problem.  Thanks for the tip otbu.

**Comment by jpsacha** [comment]
Same problem here with Windows 10 and Anaconda3-5.0.1-Windows-x86_64.exe. Using **set path=**, as described above, enabled installation.

**Comment by aldimus** [comment]
I was trying to install Anaconda on Windows 10 after uninstalling Python and getting this error, and otbu's solution worked for me.

**Comment by OrenNormand** [comment]
hi, im trying to install Anaconda2 on windows 10 64 and getting a similar error too, tried to install the "only me" option and tried "all users" option and tried to install in C and in a few other places, nothing worked. anyone knows? thank you very much. the error is attached(after this error, it writes he cant create menus)
![20180104_221314](https://user-images.githubusercontent.com/35134899/34604066-30aee6a4-f20f-11e7-92ad-333a9f2ed79e.jpg)

**Comment by stufim** [comment]
The workaround as otb already mention. Thank you for that.
1. type "cmd" in Run and run it as Administrator
2.  SET $PATH=
3. change your directory where you have installation anaconda file "Anaconda3-5.0.1-Windows-x86_64.exe"
4. Run the installation file

**Comment by tsaulic** [comment]
**otbu's** solution worked! thanks 

> Possible solution found

I had the same problem. I would get "failed to create anaconda menus" in a dialog box. This is also just happened with the latest miniconda3 4.3.30.2 x64 installer. It might be some collision with already existing .dll-files. I have development files for Qt 5.9.x installed with the path to the msvc2015_x64 build available in PATH for my windows user. There is also a Qt5Core.dll in my cmake-installation which is also in PATH.

I got it working though - by opening up cmd and using set path= before anything else. This clears all paths for this session of the command prompt. After this you call the installer directly from the command line. The installation (local user, not all users) finished with no problem this time. Seems to be working fine.

**Comment by Sabrout** [comment]
After following otbu's solution and successfully installed Anaconda, I have the Anaconda Prompt but I don't have the Anaconda Navigator GUI. How can I run it ?

**Comment by ismanidar** [comment]
Had the same issue when isntalling Anaconda 3 on my Win 7.
I think problem was because I already have Python installed on my computer.
Solved by deleting the whole path, and then I put them back after successfully install Anaconda.

Everything is installed, __Anaconda Prompt__ as well as **Anaconda Navigator UI.**

deleting path and re-installing anaconda is done manually (by click) and not from command prompt.

I think this is just a workaround, issue still exist, need to be solved though :)

**Comment by fudonglai** [comment]
## I solved this problem just now, actually it's very easy and speechless.

My condition is: windows 10 the latest version; Anaconda 3 5.1.0 , also the latest version, and no Java path in my computer.

My problem is: "Failed to created menus", and only these folders 'Lib', 'Packages' and some Uninstaller execution are in my Anaconda 3 content.

I tried most methods but they didn't work out, including uninstall the existed Python, execute the package with admin and try it in command.

Finally I found :
## DON'T CHANGE THE DEFAULT PATH, and there is no such annoying things! 

For instance, my default is "C:/user/admin/Anaconda3"

If you really want to change the path, you can use the default path when installing, and move the folder after installing successfully, and remember to change the shortcuts' path.

**Comment by gmencoff** [comment]
I was having the same problem described on Windows 10. I followed the advice of stufim and still had the same problem, I am not sure why. I then followed the next series of steps and my installation was finally successful! Here is the exact steps that I took which led to this installation working, I don't know which are necessary and which aren't but happy to have Anaconda successfully installed on my machine:

1) Uninstalled Anaconda
2) Restarted my computer
3) Instead of setting the path file to null in the command prompt, I manually deleted all user variables in system settings as well as the system path variable
4) Executed the installer as an administrator from the command prompt
5) Installed anaconda for all users
6) Did not change the default path (I previously had done so with a very similar set of steps and the installation was unsuccessful)
7) Left "Add Anaconda to my PATH Environment Variable Unchecked"
8) Checked "Register Anaconda as my default Python"

I am sure some of these steps are superfluous, but all I know is that I tried installing Anaconda maybe 25 times unsuccessfully and this is the series of steps that finally worked so I wanted to leave as much detail as possible for anyone else experiencing this annoying problem

**Comment by Sch4ck** [comment]
I am running into this issue.  
I installed Anaconda onto an incorrect drive, then manually deleted out the files from the anaconda directory instead of running the uninstaller (stupid, I know).  

I can't re-install Anaconda now,  as the 'Failed to create menus' error always pops up.
I've tried all the fixes here, but nothing seems to be working.

**Comment by deepakjhic** [comment]
oh c'mon, you can remove this bug. I tried everything and no luck. 


Anyone with more info?

**Comment by ImperatorsBlack** [comment]
> Hello guys, any help with this?

help me to fix this issue.

**Comment by cpmoliveira** [comment]
Same issue with new version:

Windows 10 64bits
Miniconda3-4.7.12-Windows-x86_64.exe

![image](https://user-images.githubusercontent.com/8579942/67118043-79bab100-f1ba-11e9-97bc-26ccacda1a0f.png)

**Comment by csoja** [comment]
Please see the Troubleshooting section of the docs for tips on resolving this: https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path

**Comment by cpmoliveira** [comment]
All the procedures listed were followed, yet the failure occurs during the installation:
- Do not install on a PATH longer than 1024 characters.
- Turn off anti-virus programs during install, then turn back on.
- Uninstall all previous Python installations.
- Clear all PATHs related to Python in sysdm.cpl file.
- Delete any previously set up Java PATHs.
- If JDK is installed, uninstall it.

**Comment by hasham426** [comment]
> I downloaded the file Anaconda3-4.4.0-Windows-x86_64 to install python in my notebook. At the end of installation I received the message "failed to create anaconda menus", with the options "abort", "retry" and "ignore", a tried retry option, without any success, so a choose the option "ignore" and the installation finished. The problem is that when I starting Anaconda Navi I got a error message "This application failed do start because it could not find or load the Qt platform plugin "windows" in "". Reinstalling the application my fix the problem".
> 
> I already had tried to reinstall Anaconda many times, without any success.
> 
> I'm using Windows 10 64-bit.
> 
> Does anybody can help me?
> 
> Thanks!

**Comment by cs-sharjeel** [comment]
@hasham426 "Failed to create menus" this error arises due to version controlling, faced the same issue on my Windows 7. Tried all possible solutions like Run as an Administrator, cleared the path `Set_path=`, changed the installation directory even fresh windows installation not gonna work.

**`Solution:`**
just installed the previous version from [archive](https://repo.continuum.io/archive/) Anaconda3-**2019.03**-Windows-x86_64.exe and do the simple installation (your user only).
I just Hope it resolved your issue.!
:)

**Comment by neoraj3-github** [comment]
> @hasham426 "Failed to create menus" this error arises due to version controlling, faced the same issue on my Windows 7. Tried all possible solutions like Run as an Administrator, cleared the path `Set path=`, changed the installation directory even fresh windows installation not gonna work.
> 
> **`Solution:`**
> just installed the previous version from [archive](https://repo.continuum.io/archive/) Anaconda3-**2019.03**-Windows-x86_64.exe and do the simple installation (your user only).
> I just Hope it resolved your issue.!
> :)

definitely the fastest solution!  I spent hours with this

**Comment by dfkettle** [comment]
You need to sacrifice a rooster on the night of a full moon.
