### ISSUE TITLE
Mismatch between matplotlib and libpng

### ISSUE THREAD

**Issue by Nodd** [ContinuumIO/anaconda-issues#363]
Whan upadting to the last anaconda version, matplotlib can't be loaded anymore because of a mismatch with libpng. I encountered the problem myself and a user reported it in https://github.com/spyder-ide/spyder/issues/2500#issuecomment-114518710
I don't remember if the fix is to update matplotlib or libpng however.

**Comment by Nodd** [comment]
It is the same kind of problem as #357, just with different versions.

**Comment by gregnordin** [comment]
Has there been any progress on this? I've run into the same problem after upgrading ipython to version 3.2.0 from 3.1.0 using conda. I was running the latest version of Anaconda on Mac OS X 10.9.4. I've had to delete my Anaconda installation and re-install it to recover from the problem and am now running ipython 3.0 (I can't seem to find how to do a conda update to ipython 3.1 since "conda update ipython=3.1" doesn't work).

**Comment by ccordoba12** [comment]
You need to run

    conda update qt
    conda update matplotlib

to fix it.

**Comment by gregnordin** [comment]
Thanks--that worked great! To re-cap, here is what I ended up doing:

1. Re-install Anaconda
2. Do the following conda updates:
conda update conda
conda update ipython ipython-notebook ipython-qtconsole  #(this includes an update to qt so there's no need to do a separate qt update)
conda update matplotlib
