### ISSUE TITLE
astroid update error

### ISSUE THREAD

**Issue by xweipbcsf** [ContinuumIO/anaconda-issues#3843]
UnsatisfiableError: The following specifications were found to be in conflict:
  - astroid ==1.5.3
  - pylint -> astroid 1.0.1
Use "conda info <package>" to see the dependencies for each package.

**Comment by csoja** [comment]
This is conda telling you that pylint and astroid conflict.   In other words, as the conda solver tries to find a set of packages that will all work together based on their dependency and version pinning - it has found a conflict it cannot by itself overcome.  You'll need to dig into it further and determine what you want/need to update/remove in order to update astroid.
