### ISSUE TITLE
sphinx / babel dependencies lead to downgrade

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#402]
I doubt this is intended:

```
Warning: 2 possible package resolutions (only showing differing packages):
    ['babel-2.0-py34_0.tar.bz2', 'sphinx-1.2.3-py34_0.tar.bz2'],
    ['babel-1.3-py34_0.tar.bz2', 'sphinx-1.3.1-py34_0.tar.bz2'],
```

**Comment by msarahan** [comment]
I might be in the process of fixing this, but need to discuss with Ilan.  The problem with babel 2.0 is that it has a major problem: https://github.com/mitsuhiko/babel/issues/174

This has been fixed in Babel, but we need a new release from Babel, and unfortunately their primary maintainer is not active.  For now in my development, I have the package tracking the 2.x-maintenance branch, and sphinx 1.3.1 has built fine.  Otherwise, sphinx 1.3.x requires the lower version of babel. =(

**Comment by pitrou** [comment]
You could also apply the patch in Anaconda. This sounds a reasonable policy in a software distribution.

**Comment by msarahan** [comment]
That's a better idea.  I will put that patch together.

**Comment by jakirkham** [comment]
Also, suffering from this problem and eager to see a fix. Patching sounds great.

**Comment by jakirkham** [comment]
It appears there was a release 7 days ago. ( https://github.com/python-babel/babel/releases/tag/2.1.1 )
