### ISSUE TITLE
Forum is absolutely useless

### ISSUE THREAD

**Issue by nevadarain** [ContinuumIO/anaconda-issues#4028]
As the title suggest this forum is absolutely useless.  Ive posted issues and they get closed without a resolution.  Other issues i post get reponses with link that reference the supposed problem, yet those links dont have solutions LMAO. THis is a total joke.

**Comment by msarahan** [comment]
Sorry for your frustration.  You are asking for people's time.  Time is not free.  We do the best we can, and we ask that community members both help each other and also seek answers to questions that already exist, rather than demanding our time to answer them again.  I wish you luck and patience in your quest to learn.
