### ISSUE TITLE
Using Conda for C++-only packages on Windows

### ISSUE THREAD

**Issue by tadeu** [ContinuumIO/anaconda-issues#440]
I'd like to use Conda to support mixed C++ and Python development projects (using Boost.Python to make bindings), and I found that it already has some packages that are C++ only, such as Boost and HDF5, and others that are mixed Python + C++, such as VTK. It would be interesting to use Conda for everything, and, according to the documentation,

> It works on Linux, OS X and Windows, and was created for Python programs but can package and distribute any software.

I'd like to also create my own C++-only and Python + C++ conda packages, so I need to know what are the standard installation paths on Windows.

I've seen three different layouts:

* `hdf5` and `libpng` install `lib`s in `Library\lib`, `dll`s in `Library\bin`
* `boost` install both `lib`s and `dll`s in `Library\lib`
* `vtk` and `pyqt` install everything in `Lib\site-packages\<package-name>`, including `pyd`s, `dll`s and `py` files. Unfortunatelly they don't install static `lib`s or headers :/

Note that neither `Library\bin` nor `Library\lib` are added to the `PATH` by `activate` scripts (see issue #233).

What would be the standard?

My first suggestion is that `Library\bin` should be added to the `PATH`, and that the layout for mixed Python + C++ packages (such as VTK) should be:

* `.py` files go to  `Lib\site-packages\<package-name>`
* `.pyd` files go together with the `.py` files
* `.dll` files that are shared by Python modules and by C++ code go to `Library\bin`
* `.lib` files go to `Library\lib`
* headers go to `Library\include`
* Cmake "find" modules and related files go to `Library\cmake`

**Comment by ccordoba12** [comment]
We were discussing precisely this last week within the Anaconda team. Our take is that we're going to add `Library\bin` to `PATH`.

Also, our VTK version is going to be installed in `Library`, with its Python bindings in `site-packages`.

Pinging also @groutr and @msarahan in case they have something else to add.

**Comment by nicoddemus** [comment]
@ccordoba12 nice to know, thanks for answering so quickly! 

Your take is exactly how we figure things could work regarding how files should be stored in the conda environment and how `PATH` should be setup. :smile:

**Comment by ccordoba12** [comment]
I forgot to say that I'm going to update PyQt to fix the problems mentioned by @tadeu (and some others) in a couple of weeks.

**Comment by tadeu** [comment]
Thanks for the answer and for the fixes, @ccordoba12 :)

**Comment by nicoddemus** [comment]
Pinging @campos-ddc

**Comment by groutr** [comment]
Yes, Library\bin should be on the path.  You're pretty much spot on with everything else though.  That would provide a nice, natural home for many unix-like tools.  I like the idea about cmake files going in Library\cmake.  I've not really paid attention to those.

When I compile things for windows, I try to link dynamically where I can.  Hence, most windows (at least the ones I maintain) ship without static libs.

**Comment by msarahan** [comment]
+1, especially for the forethought about cmake resources.  My only issue is that sometimes different packages can use different versions of a given compiled dll.  With all DLLs going into a central location, there will likely be conflicts & confusion at some point.  Not a show stopper, just something to be careful about.

**Comment by msarahan** [comment]
I think this mostly address this issue: https://github.com/conda/conda-build/pull/601

For CMake, it seemed to have its own desires of where to place things so that they get automatically found.  This was Library\shared or something.  The CMake recipe has been updated for this.

If this is addressed to your satisfaction, please close this issue.

**Comment by cfobel** [comment]
I have tried searching around quite a bit, but still haven't been able to find an answer to the following question...

**Is there any particular reason why `bin`, `lib`, `include`, etc., are installed under the `Library` whereas they are located directly under the Conda prefix on Linux and MacOS?**  It seems to complicate things when trying to build cross-platform packages.  Particularly when trying to build `noarch` packages containing only C++ `include` headers.

Perhaps someone here might be able to provide some insight?  Any help would be greatly appreciated!

**Comment by msarahan** [comment]
Because ultimately python on windows doesn't follow unix conventions.  The Library folder is our way of establishing a place of sanity, where those conventions are followed.

Noarch stuff can be improved if necessary.  We can make a specific noarch type that understands this delineation.  Say, ``noarch: includes`` or something like that.

**Comment by msarahan** [comment]
PS: if you want that feature, please open issues on the conda and conda-build repos.  It'll take work on both.  It might be a while before we get to it, but I think it's worth doing.

**Comment by cfobel** [comment]
@msarahan Thanks so much for responding so quickly!

> Because ultimately python on windows doesn't follow unix conventions. The Library folder is our way of establishing a place of sanity, where those conventions are followed.

Please note with the following questions that I mean no disrespect and I am not trying to be argumentative, but am truly trying to get a better understanding of the design choices.  Is the `Library` folder a _Python_ convention?  Or is it strictly used in _Conda_?  Notwithstanding backwards-compatibility (e.g., all the existing Windows packages using the `Library` prefix for `Library/bin`, etc.), would there be any technical reason that `bin`, `include`, etc., could not be located directly under the Conda environment prefix?  I understand completely if the main reason the "Unix-y" directories are currently stored under `Library` is historical and is unlikely to change since it would break compatibility, but I would just like to know whether that is the reason.

Thanks again for your time.  Also, thanks for you suggestion.  I will open a issues on the `conda` and `conda-build` repos.

**Comment by msarahan** [comment]
To the best of my knowledge, the Library folder is a conda convention, not a Python convention.  It predates me.  I don't know its origin story.  When I came in, some binary stuff was getting installed into Library/bin, and other stuff was going into Scripts.  I helped push that all binary stuff (aside from entry points) goes into Library/bin, and only entry points go into Scripts.  The Scripts folder is a Python convention on Windows.

Other than that, sorry.  I can ask @ilanschnell or perhaps @asmeurer if you really want to know.  I think the ship has definitely sailed on changing this, though.

**Comment by ilanschnell** [comment]
Correct the Library/bin convention is not a Python convention (not even a
conda convention technically).  It was introduced by Mark Wiebe when we
first ran across none-Python related package on Windows over 5 years ago.

Ilan

**Comment by cfobel** [comment]
Thank you very much @msarahan and @ilanschnell for the historical perspective.  I really appreciate you taking the time to respond.

I have created two new issues related to building cross-platform header-only packages, as suggested by @msarahan :

 - conda/conda#6978
 - conda/conda-build#2725

I am willing to dedicate some time to either or both of these issues, but would require/appreciate some guidance on how this can be best implemented.

**Comment by mingwandroid** [comment]
> Correct the Library/bin convention is not a Python convention (not even a conda convention technically).  It was introduced by Mark Wiebe when we first ran across none-Python related package on Windows over 5 years ago.

It's certainly an Anaconda Distribution convention, in-fact more than a convention, it is a rule. I would love to know why Mark decided to add all those extra characters on the one platform with serious path length issues.
