### ISSUE TITLE
Can not install gcc-5 with binutils

### ISSUE THREAD

**Issue by jbrezmorf** [ContinuumIO/anaconda-issues#4615]
running simply:
```
conda install -c salford_systems binutils gcc-5
```
results in:
```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'salford_systems::gcc-5-5.3.0-0'.
LinkError: post-link script failed for package salford_systems::gcc-5-5.3.0-0
running your command again with `-v` will provide additional information
location of failed script: /home/jb/miniconda3/envs/test/bin/.gcc-5-post-link.sh
```
Using '-vv' it turnd out, that gcc can not link hallo world test binary, reporting:
```
/home/jb/miniconda3/envs/test/bin/ld: cannot find crt1.o: No such file or directory
/home/jb/miniconda3/envs/test/bin/ld: cannot find crti.o: No such file or directory
/home/jb/miniconda3/envs/test/bin/ld: cannot find -lc
/home/jb/miniconda3/envs/test/bin/ld: cannot find crtn.o: No such file or directory 
```
Side note: can you provide some sort of log with readable stdout of executed commands?
It tooks me a day before I dig it out.

Further observations:
- Installing 'gcc-5' into clear environment works fine.
- Installing 'gcc-5' after 'binutils', even if they were removed fails. Very confusing!!!
- Same issue for 'binutils' from the 'conda-forge' channel and for 'gcc' (4.x) from default.

My problem was that both 'gcc-5' and 'binutils' are required by a 'netgen' build recipe, and 'conda build' have no way to install first 'gcc-5' and then 'binutils'. Fortunatelly I was able to build the package even without 'binutils' at all.

**Comment by mingwandroid** [comment]
We do not provide this package. You need to take this up with `salford_systems` and/or `conda-forge`. It is not an `Anaconda Distribution` issue.

If you want to use compilers that we do provide, you can get them from `c3i_test` via:

`conda install -c c3i_test compilers_linux-64`

This will get you GCC 7.1.0. They are pseudo-cross compilers so there are a few things to note:

1. The executable names are all prefixed with a machine name. The activate script sets `CC` and `CXX` to make this not matter too much. It also sets `HOST` to the machine name.
2. They do not look in `/usr` nor `/usr/local` because they have their own `sysroot` folder (this is done to achieve build isolation).

**Comment by jbrezmorf** [comment]
Fine, but how can I figure that out? For 'anaconda gcc-5' google gives me:
[](https://anaconda.org/salford_systems/gcc-5). I have tried also some other channels. 

Why the 'binutils' are not in 'default'?  For builds this is an important package.

**Comment by mingwandroid** [comment]
Many things on `anaconda.org` are user- or customer-curated, so it is *not* the canonical channel. A top hit on a search engine does not correlate to being canonical. `salford_systems` are not `Continuum Analytics`.

I have also told you how to install a GCC package that you can consider somewhat canonical. It's just not GCC 5, it's more modern than that (and comes with a working binutils).

**Comment by jbrezmorf** [comment]
Thank you for leading me to the right channel as well as for the further explanation.

**Comment by mingwandroid** [comment]
No problem!
