### ISSUE TITLE
ImportError in xray and pandas

### ISSUE THREAD

**Issue by Xunius** [ContinuumIO/anaconda-issues#474]
When I was trying to install xray via miniconda, the installation went on Ok but importing the xray module gave an ImportError:
```
>>> import xray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../miniconda/envs/xray/lib/python2.7/site-packages/xray/__init__.py", line 4, in <module>
    from .core.dataset import Dataset
  File "/.../envs/xray/lib/python2.7/site-packages/xray/core/dataset.py", line 16, in <module>
    from .. import conventions
  File "/.../miniconda/envs/xray/lib/python2.7/site-packages/xray/conventions.py", line 9, in <module>
    from pandas.tslib import OutOfBoundsDatetime
ImportError: cannot import name OutOfBoundsDatetime
```

I've posted this to the xray repository and was suggested to do the same here, as it seems like the pandas build may be broken, because `from pandas.tslib import OutOfBoundsDatetime` gives the same error. I've tried downgrade the pandas from 0.17 to 0.16, 0.15 and 0.14, downgrade the numpy from 1.10 to 1.9 but didnt help.

Finally some version info:
conda: 3.16.0
xray:    0.6.0
numpy: 1.10 or 1.9
pandas: 0.14 - 0.17
python: 2.7.10
OS: Ubuntu 12.04 64-bit.

Please help

**Comment by Xunius** [comment]
Update:
problem solved. It seems that some modules hidden in $HOME/.local/ is messing it up. The venv created by conda can still be affected by these, can't it? 
Anyway, issue can close now.

**Comment by msarahan** [comment]
PATH and PYTHONPATH can always mess things up.  As much as possible, conda tries to prepend itself to your PATH so that its installed files get found first.  You should avoid PYTHONPATH when you can, and understand its potential for confusion where you can't avoid it.  Ultimately though, there's nothing conda can do to completely prevent your system from going looking for modules and finding the wrong one.
