### ISSUE TITLE
update xray version

### ISSUE THREAD

**Issue by shoyer** [ContinuumIO/anaconda-issues#476]
Anaconda has xray version 0.5.1, but the latest released version is 0.6.

It is possible to setup anaconda to automatically build released versions of xray when I upload them to pypi?

**Comment by shoyer** [comment]
We just released v0.6.1. A lot of our users so conda, so it would indeed be great if we could get this updated.

**Comment by msarahan** [comment]
Automatic build would be awesome.  This is somewhat possible with anaconda.org, I believe.  I think we'll keep it somewhat manual for the official repository, though, for the sake of security review.  It is better if the anaconda build team is forced to consciously review updates before making them available to everyone.

If you have auditability ideas that would make it more feasible to have end-users confident in the security of their automatically-built packages, please talk with us.

**Comment by shoyer** [comment]
Fair enough. That said, PyPI does have some authentication built in. In any case, thanks for your help here!

**Comment by msarahan** [comment]
Yes, authentication is a good start, but PyPI is not a very good starting place when it comes to security.  For example, if people are using the default tools for package uploading, they are susceptible to a man in the middle attacks and password thievery because uploads are not done over https.  The Twine package fixes this: https://pypi.python.org/pypi/twine

It's a question of how easy it is for anyone to compromise any package at ANY stage of the process.  Since Continuum is producing a product here, in terms of a package ecosystem that is tested to some extent, we would be at least somewhat on the hook if a conda-installed package led to a security disaster.

**Comment by msarahan** [comment]
caveat: I think conda-installed packages from non-official channels would be OK - then the producer of that package is responsible for its integrity.  If it's official, then it's our responsibility.

**Comment by richardotis** [comment]
@msarahan What about having maintainers keep GPG key IDs + a security POC on file with you? It's pretty easy to sign and upload packages with `twine`, and while AFAIK PyPI isn't doing anything to verify them at the moment, the signature files are still there and easily checked, e.g., https://pypi.python.org/packages/py2.py3/p/pycalphad/pycalphad-0.2.2-py2.py3-none-any.whl.asc

So if you know the key ID from which the signature was made (0161A98D), you can pull the public key from the PGP public keyserver and check it against the uploaded package file.

You're probably already aware of this document but I want to mention PEP 458 because it may be interesting to other people who come across this issue, though it goes into far more detail than what we're talking about here: https://www.python.org/dev/peps/pep-0458/

I think everything about securing PyPI goes double for Anaconda, precisely because of the scientific audience of the distribution. If I'm a malicious or sophisticated attacker, compromising a popular package in an Anaconda repository (especially an official one) could be very valuable to me. I think Continuum is right to be wary from a security perspective, but I hope they can find a solution that helps maintainers get package updates to users in a timely manner without too much overhead on their end.

**Comment by msarahan** [comment]
These are very good ideas, and I will raise them internally.  It may take
us some time to get the implementation and social logistics right, but I
think this certainly belongs on the near-term roadmap.  More soon.

**Comment by csoja** [comment]
Closing as the original post requested xray be updated - and it was.  xarray (which is the current name for xray) is current at 0.9.6 in the repo.
