### ISSUE TITLE
Qt dll dups

### ISSUE THREAD

**Issue by tico-tico** [ContinuumIO/anaconda-issues#510]
Hi, guys.

I see that in qt-4.8.7-vc9_2 you added same Qt dlls both in the **lib** and in the **bin** folder. Not a big deal for me, just pointing out in case it wasn't your intention to make such duplicates. You know, waste of space, traffic and so on.. :-)

**Comment by ccordoba12** [comment]
@msarahan, this seems to be true. Any thoughts about it?

**Comment by msarahan** [comment]
I have nothing really good to say.  It might have been a packaging mistake, but I just run nmake install.  If I extract the tarball itself, those files are only in Library\bin.

I am worried that the files in Scripts\ are a previous Qt version, and that having files in both Scripts\ and Library\bin will cause ambiguity (depending on the value of PATH) as to which ones will get picked up, with a pretty high likelihood that things will break.  If anything, I think this might be the old Qt package not being removed cleanly.  Please delete the Qt dll's from Scripts.

Pinging @ilanschnell about why the old Qt dll's are still around - they should have been removed when the package was updated, right?  Or is this an issue because the previous package was (probably) a different version of qt?  Or does it have anything to do with the new features?

**Comment by tico-tico** [comment]
>  If I extract the tarball itself, those files are only in Library\bin.

that's weird. if i extract *https://repo.continuum.io/pkgs/free/win-64/qt-4.8.7-vc9_4.tar.bz2* i see Qt dll's in the *bin* and *lib* folders. both v. 4.8.7.0.

Oh! I get it. I mean **Library/bin** and **Library/lib**, maybe you are looking in the others *bins* and *libs*.

BTW my Script dir doesn't contain any  Qt stuff, i'm using Miniconda + packets from your rep + updates.

**Comment by msarahan** [comment]
Thanks for the clarification.  Yes, that is a Qt installation default.  I think they just take the safe side to cover their bases: some people go looking for dlls in lib (more the *nix paradigm), but on Windows, the import library (.lib) goes in lib, and dlls go in bin.

For the sake of saving a bit of space, I'll try removing dlls from lib, and test as much as possible to ensure that things still work.
