### ISSUE TITLE
Setuptools 36.4.0 certifi broken

### ISSUE THREAD

**Issue by rendinam** [ContinuumIO/anaconda-issues#5219]
This issue was reported on the google groups forum mailing list [https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/4ji0e1-YoLg]. I am reproducing it here for greater visibility.

I also notice that the https://github.com/conda-forge/setuptools-feedstock doesn't reflect the recipe used to provide setuptools 36.4.0 that appears in the anaconda defaults channel. Where is the recipe for setuptools 36.4.0 kept?

Thanks.

------------------ (snip) ------------------

Please rebuild the setuptools package with the correct version of cerifi:

from setuptools-36.4.0 setup.py:

extras_require={
  "ssl:sys_platform=='win32'": "wincertstore==0.2",
  "certs": "certifi==2016.9.26",
},

From Continuum's setuptools-36.4.0 recipe:

requirements:
    build:
	[...]
        - certifi 2016.2.28 py36_0
	[...]

From the installed setuptools-36.4.0 EGG (requires.txt):

certifi==2016.9.26

Anyway -- certifi-2016.2.28 needs to become certifi-2.9.26

**Comment by jhunkeler** [comment]
@nehaljwani I saw were name-dropped on the Conda Gitter as the person that built this package, so I'm tagging you in hopes you'll get a chance to fix the issue above introduced on 09/05.

**Comment by jjhelmus** [comment]
The `setuptools-36.4.0` packages in the `defaults` channel contain the recipe used to create the package.  Because a different build system was used to build this package the recipe is stored in the `recipe.tar` file in the info directory rather than being unpacked. This recipe differs from the `conda-forge` version in that the version number was updated from 36.3.0 to 36.4.0.

The various versions of `certifi` mentioned in the package come from the mixture of conda build rendering the recipe and setuptools bootstrapping process.

The certifi 2016.2.28 in the `meta.yaml` file is a result of conda-build rendering the meta.yaml file with the package versions installed in the build environment.  These packages come from the `defaults` channel and at the time the package was created the newest version of certifi in the channel was 2016.2.28.  To rebuild the package from scratch use the `meta.yaml.template` file rather than the `meta.yaml` file.

The `certifi==2016.9.26` entry in the requires.txt file in the `egg.info` directory is an artifact from running [bootstrap.py](https://github.com/pypa/setuptools/blob/v36.4.0/bootstrap.py) when building setuptools.  This file has no effect on conda, nor as far as I know, pip or other packaging tools.

If you examine the `conda-forge` packages you will find it too contains two different `certifi` versions.

**Comment by jhunkeler** [comment]
Hi @jjhelmus,

The difference in `requires.txt` matters quite a bit.

As stated before `setuptools-36.4.0` requires `certifi-2016.9.26` internally. This is a hard dependency imposed by `setuptools`'s `setup.py` at build-time. It reads `certifi==2016.9.26` under `extras_require` beneath the `34.4.0` Git tag:

```python
extras_require={
  "ssl:sys_platform=='win32'": "wincertstore==0.2",
  "certs": "certifi==2016.9.26",
},
```

This explicitly defines the version(s) of software it requires at run-time and it is not negotiable. If it had read, `certifi<=2016.9.26` it might be a different story, however that's not the case here. 

If you run `diff -u -p working.txt broken.txt` (attached) or `diff -y working.txt broken.txt` (`sbs.txt` below) you will see what I'm talking about.

**Here's a generic setup.py we're going to compile:**
https://github.com/spacetelescope/jwst_gtvt/blob/master/setup.py

**Here's a generic recipe:**
https://github.com/astroconda/astroconda-dev/blob/master/jwst_gtvt/meta.yaml

**Here's a generic conda-build line:**
```
$ conda build jwst_gtvt
```

**"Broken" was built with build-time dependencies as-is:**
```yaml
requirements:
    build:
    - astropy
    - matplotlib
    - numpy
    - setuptools
    - python
```

**"Working" prevents the current version of setuptools from getting used:**
```yaml
requirements:
    build:
    - astropy
    - matplotlib
    - numpy
    - setuptools <36.4.0
    - python
```

------
The breakdown occurs during *.egg resolution. Setuptools' own egg requires `certifi-2016.9.26`. As expected, a pass is made at the end of the build to ensure the environment contains the correct versions required by `requires.txt`. However as also seen in the diff, the `defaults` channel conveniently provided the environment with `2016.2.28` and that's not what setuptools _needs_, so therefore it attempts to download the required version, and thus halts the package building process with an error.

And no, this event does not occur with every Python package in the wild, but it does happen with seemingly benign setup.py implementations, so it should be considered a bug. I'm frustrated that we've been forced to use `conda build --bootstrap` against an environment with `setuptools-27.2.0` pre-installed in order to circumvent the issue. The only other way to fix this prior to `conda-build 3.x` would be to manually pin every recipe in our arsenal like how I did for this example. 

Please fix this.

## Attachments
[broken.txt](https://github.com/ContinuumIO/anaconda-issues/files/1315332/broken.txt)
[sbs.txt](https://github.com/ContinuumIO/anaconda-issues/files/1315334/sbs.txt)
[working.txt](https://github.com/ContinuumIO/anaconda-issues/files/1315333/working.txt)

**Comment by jjhelmus** [comment]
@jhunkeler The setuptools package in `defaults` channel has been updated to not include the `requirements.txt` file in the egg-info directory via a [patch](https://github.com/AnacondaRecipes/setuptools-feedstock/blob/master/recipe/0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch) to the source code.  This modification was present in the `setuptools 27.2.0` packages which I believe is why the `jwst_gtvt` builds were working with that version.

I was able to build `jwst_gtvt` using the recipe you linked using the new `setuptools` packages.  Let me know if you still are seeing issues.
