### ISSUE TITLE
Trouble Opening Navigator

### ISSUE THREAD

**Issue by kbeicker** [ContinuumIO/anaconda-issues#5488]
I am having trouble opening the Anaconda-Navigator on Windows 8.  Here are the things I have tried, but I remain unable to open the program:

- Uninstalling & Reinstalling Anaconda
- Installing for Just Me and All Users
- Ensuring no spaces in the destination folder path
- Adding Anaconda to my PATH environment
- Opening Navigator from Start Menu and directly from the destination folder
- Starting from command line
- Anaconda 2 & 3

I would appreciate any assistance. Thank you!

**Comment by goanpeca** [comment]
@kbeicker first of all please open a terminal or anaconda prompt (on windows) and paste the output of running

```
$ conda info
$ conda list
```

Secondly, if you try to run `$ anaconda-navigator` from the termina/prompt, could you paste any error traceback?

Cheers

**Comment by kbeicker** [comment]
Well this is quite the problem:
'$' is not recognized as an internal or external command, operable program or batch file.

**Comment by goanpeca** [comment]
@kbeicker $ denotes that you need to type the command in the prompt, so you need to paste everything after the `$` sign.

**Comment by kbeicker** [comment]
Sorry, new to this process:
'conda' is not recognized as an internal or external command, operable program or batch file.

**Comment by goanpeca** [comment]
@kbeicker is there a program called `Anaconda Prompt`?, it should have been installed with Anaconda, could you open that Prompt (Should have a similar icon to the Windows Command Prompt)

**Comment by kbeicker** [comment]
I am using Anaconda Prompt.  However, there is an error when initially opening Anaconda Prompt.  
Attribute Error: module 'enum' has no attribute 'IntFlag'

**Comment by goanpeca** [comment]
@kalefranz, @mingwandroid thoughts?

**Comment by mingwandroid** [comment]
Well, we can see that the *system* `Python 2.7` is being run instead of `Python 3` from `Anaconda`.

This is probably down to one or more of the following:
1. Having `Python 2.7` installed for all users and `Anaconda` installed for just me.
   => Fix here it to remove `Python 2.7` from your system, or only launch `Anaconda` software from the `Anaconda Prompt`.
2. Having the `%PYTHONPATH%` env. var set.
  => Fix here is to remove that env. var.

Overall, following the advice of not adding anything to `%PATH%` ever (when you are given the choice) works best, and then, for `Anaconda`, using the `Anaconda Prompt` or our other `Start Menu` shortcuts instead to launch things.

**Comment by kbeicker** [comment]
I removed the %PYTHONPATH% and things are working.
Thank you all for your help and patience.
