### ISSUE TITLE
ImportError: No module named essentia

### ISSUE THREAD

**Issue by yyf** [ContinuumIO/anaconda-issues#55]
>>> import essentia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named essentia

I saw similar issues about importError from previous posts, any pointer to fix this? 
I tried copying the module to site-package folder manually and export path but no luck, maybe I missed something? thanks.

**Comment by Jose-Coursera** [comment]
I had this problem because i use Anaconda so on ubuntu the solution was:

Add a .pth file to the directory $HOME/path/to/anaconda/lib/pythonX.X/site-packages. This can be named anything (it just must end with .pth). A .pth file is just a newline-separated listing of the full path-names of directories that will be added to your path on Python startup.

in the .ph file i wrote this:
/usr/local/lib/python2.7/site-packages/

and it works on linux ubuntu 14.04

**Comment by msarahan** [comment]
Please do not do this. You are intentionally mixing anaconda with the system install. You are on a bullet train to pain and confusion. 

The essentia module appears to be a third party library for audio extraction. Perhaps the easiest way to get things right is to submit a build recipe to conda forge: http://conda-forge. Github.io

The are some build directions at http://chrisstrelioff.ws/sandbox/2014/12/10/installing_essentia_for_audio_feature_extraction.html - you need not get into conda-forge stuff to try the build. As long as anaconda is first on your PATH, I think those build directions will install essentia into anaconda,  avoiding the confusion with system.
