### ISSUE TITLE
Error: URI line 372. Anaconda Navigator Crashes immediately

### ISSUE THREAD

**Issue by Kayleah** [ContinuumIO/anaconda-issues#5553]
Hello, I installed Ananconda on Tuesday, 9/12, and cannot get Anaconda Navigator to open. 

When I type 'anaconda-navigator' into Command Prompt: I get the following issue:

`C:\Users\Kayleah>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\Kayleah\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'

C:\Users\Kayleah>`

**Comment by goanpeca** [comment]
@Kayleah it seems you did not install the latest anaconda (Because that error is from an old navigator version 1.3.x not found in the latest installer 1.6.2). So you need to update to the latest Navigator (1.6.4).

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```
