### ISSUE TITLE
activate.bat in mininconda fails

### ISSUE THREAD

**Issue by swingfield** [ContinuumIO/anaconda-issues#581]
Hi, I'm trying out miniconda on windows, and got some errors running activate.bat.  

The errors are 

```
c:\Miniconda3\Scripts>.\activate
files\curl\bin";C:\Program Files (x86)\CloudFoundry;C:\Program Files (x86)\Brackets\command;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\cygwin64\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\apache-ant-1.9.3\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\Docker Toolbox;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\swingfield\AppData\Roaming\npm" was unexpected at this time.
```

Background: I installed via the installer but chose not to have my PATH env altered.

Here's the steps I took

1. Opened a new console window
2. cd c:\miniconda3\scripts
3. .\activate

The issue might be on lines 50 and 87:

``` dos
50: CALL SET "PATH_NO_ROOT=%%PATH:%ROOT_PATH%;=%%"
```
``` dos
87: CALL SET "PATH_NO_SCRIPTS=%%PATH:%SCRIPT_PATH%=%%"
```

I found that if i changed the ":" to a ";" then activate worked.

**Comment by msarahan** [comment]
That ":" is Windows batch file syntax for search and replace.  Those lines are basically testing to see if things are on PATH, with the basic idea of "remove this thing I want you to find - if the string stays the same, then it wasn't there."

The changes you've made will be benign, but the script will not function as intended.  It will always add its contents to PATH, and will probably do so twice.  The exact behavior is somewhat undefined, but probably not completely working.

Your PATH seems to be dumped in your traceback above.  It is extremely long.  I'm not surprised that activate.bat is having issues.  There is a limit of 1024 characters.  activate.bat sets PATH so that programs in your environment work.  It is sometimes, but not always, sufficient to call programs with their full path, and not modify PATH at all.  Programs still sometimes need to find DLLs, and PATH is (mostly) how that happens.

There are some strategies for shortening it here: http://stackoverflow.com/questions/4405091/how-do-you-avoid-over-populating-the-path-environment-variable-in-windows - see especially the tip about symlinking the Program Files directories.  You also have some duplicates in there that can be cleared out.

**Comment by msarahan** [comment]
One further note: it is OK for spaces to be in PATH, but you should not have quotes.  You have at least one pair showing at the beginning of your traceback.

**Comment by swingfield** [comment]
Thank you, sorry for the bother.  Coming in with a more reasonable PATH did indeed fix it.
