### ISSUE TITLE
(Anaconda3-4.4.0-Windows) Anaconda3 installer has stopped working

### ISSUE THREAD

**Issue by KevinJDurant** [ContinuumIO/anaconda-issues#5985]
**This is what I got:**

![image](https://images.imgbox.com/cc/34/8RtG3456_o.png)

**When debugging with VS17:**

![image](https://images.imgbox.com/64/03/ndRqQhGZ_o.png)

**Data in event viewer:**
> Faulting application name: Anaconda3-4.4.0-Windows-x86_64.exe, version: 4.4.0.0, time stamp: 0x584dca3f
> Faulting module name: System.dll, version: 0.0.0.0, time stamp: 0x584dca1a
> Exception code: 0xc0000005
> Fault offset: 0x000025de
> Faulting process ID: 0x25a8
> Faulting application start time: 0x01d33470232d09d5
> Faulting application path: F:\Downloads\Anaconda3-4.4.0-Windows-x86_64.exe
> Faulting module path: C:\Users\Student\AppData\Local\Temp\nsg4645.tmp\System.dll
> Report ID: cc649d9e-1f16-4a4c-9d47-9fb4f3ef750c
> Faulting package full name: 

**Info:**
- Windows 10 Professional x64, fully updated and the OS integrity was verified using an SFC scan.
- Ran the installer as Admin, ran it without Admin.
- Installed on different locations.
- Tried installing on a different user profile.
- Unchecking one or both of the checkboxes.
- No Python is installed.
- Download the installer again, both passed file verification.
- Visual Studio 2017 is installed but does not have the Anaconda3 module.

Noticed some other users also had the same issue. Any idea on how I can fix this?

**Comment by samvanbrussel** [comment]
I'm having the issue when the installer starts installing the vs2015_runtime-14.x. I assume it has been updated by the latest VS2017 updates. Since then, even my old 5.0.0 installer doesn't work any more.

![installer issues](https://user-images.githubusercontent.com/2074393/32616077-bf6202c0-c571-11e7-968c-68f8a3feafef.png)

My system is now Anaconda-less and I'm having a presentation next Wednesday. Fun! Better left 5.0.0 installed... but the 5.0.1 installer made me do it.

**Comment by mingwandroid** [comment]
Can you click `show details` and copy the text (as text, not as a screenshot) here please? The UCRT should not work as you have described.

**Comment by mingwandroid** [comment]
It is more likely you have some badly written virus scanner running.

**Comment by mingwandroid** [comment]
Two other possibilities:
1. You installed some other Python into `C:\Windows\System32`. Please look in there to see if you have any `python*.dll` files.
2. You have set the `PYTHONHOME` or `PYTHONPATH` environment variables.

**Comment by samvanbrussel** [comment]
Cannot show details because a Close Program or Debug Program window is on top. If I open it upfront, before it crashes, you have the following content.

![installer issues](https://user-images.githubusercontent.com/2074393/32649231-911150fa-c5f9-11e7-8f42-6526574133a4.png)

I've also been able to install it on another system with the same corporate virus scanner, but without VS2017.

**Comment by samvanbrussel** [comment]
Unhandled exception at 0x0047005C in Anaconda3-5.0.1-Windows-x86_64.exe: 0xC00001A5: An invalid exception handler routine has been detected (parameters: 0x00000001).

**Comment by samvanbrussel** [comment]
The exception is thrown from C:\Users\SAM~1.VAN\AppData\Local\Temp\nsj2834.tmp\untgz.dll version 1.00.21.0

**Comment by samvanbrussel** [comment]
The 4.4.0 also won't install any more, I think indeed it is my virus scanner (unpacking the archives). Have asked my company to disable it, but have to wait. Will give feedback afterwards.

**Comment by samvanbrussel** [comment]
Ok, disabling the stupid McAfee VirusScan Enterprise solved the issue. Thx @mingwandroid  for the tips.

**Comment by mingwandroid** [comment]
No problem!
