### ISSUE TITLE
Gael would like to have joblib included in Anaconda by default

### ISSUE THREAD

**Issue by pzwang** [ContinuumIO/anaconda-issues#599]
Per https://twitter.com/GaelVaroquaux/status/679726388027494400, Gael says it's super lightweight and super useful.

@GaelVaroquaux

**Comment by GaelVaroquaux** [comment]
To give some background:

1. I am the original author of joblib, thus biased. Don't trust my judgment.

2. Joblib has been described as very useful by others, such as http://blog.rtwilson.com/my-top-5-new-python-modules-of-2015/ (which prompted the tweet discussion linked by @pzwang above). I came back from the NIPS conference a few days ago, where I met a lot of people using it.

3. It's massively installed on eg Debian (one of the few environment where it is possible to have reliable stats https://qa.debian.org/popcon.php?package=joblib), more than eg Cython, biopython, networkx, statsmodels, numexpr, all shipped with anaconda.

The packaging should be trivial. It's pure Python, no dependencies.

**Comment by ccordoba12** [comment]
I'll create a recipe for it (or move it from conda-recipes, if it's already there) in our internal repo.

**Comment by ericmjl** [comment]
:+1:! I have found it quite useful - using both Mac OS X and Debian/Ubuntu/Fedora.

**Comment by lesteve** [comment]
joblib is available through conda already so I am guessing it shouldn't be too much work to add it to Anaconda by default.

Also I was wondering the joblib version available through conda is a bit old (0.8.4) and there has been a few major improvements since. Is there something we can do to help getting newer versions available through conda? Getting 0.9.4 in would be good enough, we don't really need intermediary versions.

**Comment by ilanschnell** [comment]
I just updated joblib to version 0.9.4 should be available soon.

**Comment by lesteve** [comment]
> I just updated joblib to version 0.9.4 should be available soon.

Great thanks.

**Comment by GaelVaroquaux** [comment]
> I just updated joblib to version 0.9.4 should be available soon.

Thanks Ilan!
