### ISSUE TITLE
the cudatoolkit package is missing libnvToolsExt.so*

### ISSUE THREAD

**Issue by soumith** [ContinuumIO/anaconda-issues#6075]
libnvToolsExt.so is a library that is shipped as part of the CUDA toolkit. It's quite small (37K) and our package (pytorch) relies on it for doing NVTX coloring.

**Comment by nehaljwani** [comment]
CC @jjhelmus

**Comment by jjhelmus** [comment]
Last I checked (more than a month ago) we were not able to distribute libnvToolsExt.so because it was not included in NVIDIA's list of redistributed portions of the CUDA toolkit.  A talked to a few co-workers who were going to check with NVIDIA to see if this library could be added to the list.  Let me see if this situation has changed since that time.

**Comment by jjhelmus** [comment]
After checking with some co-workers and the toolkit EULA I found that libnvToolsExt.so is include in the redistributable list of files for CUDA 8.0 and 9.0.  I'll work on getting the cudatoolkit 8.0 package updated with this library.

The CUDA 7.5 EULA does not include this file so we are not able to include it in our package for that version.

**Comment by jjhelmus** [comment]
The [cudatoolkit-8.0-3 packages in the numba channel](https://anaconda.org/numba/cudatoolkit) includes the libnvToolsExt.so library.  I'm working on getting these included in `defaults`

**Comment by jjhelmus** [comment]
The cudatoolkit-8.0-3.tar.bz2 packages are now in the default repository.  These include the `libnvToolsExt.so` library.

**Comment by soumith** [comment]
awesome. thanks a lot Jonathan!
