### ISSUE TITLE
Anaconda installer does not create Start Menu entries

### ISSUE THREAD

**Issue by ciupicri** [ContinuumIO/anaconda-issues#633]
I run `Anaconda3-2.4.1-Windows-x86_64.exe` as __Administrator__ on a Windows 7 64-bit machine and chose to install it for all users.  The installer didn't complain about anything, but "Anaconda" is missing from the Start Menu.

I didn't have any problems with the `Anaconda3-2.4.0-Windows-x86_64.exe` installer.

I've also noticed that if I modify `E:\Anaconda3\Lib\_nsis.py` and add a small delay in the BAT generated by `elevated_install`, and re-run `"E:\Anaconda3\python.exew" -E "E:\Anaconda3\Lib\_nsis.py" mkmenus` the entries are added to the Start Menu. This snippet works for me:

            "%SystemRoot%\System32\WScript.exe" "%temp%\getadmin.vbs"
            del "%temp%\getadmin.vbs"
            timeout /t 1 /nobreak
        ) ELSE (

You might find helpful the answers to ["Sleeping in a batch file"](http://stackoverflow.com/q/166044/12892) from Stack Overflow.

**Comment by msarahan** [comment]
Thanks for this report, especially for the workaround.  Please see https://groups.google.com/a/continuum.io/forum/m/#!topic/anaconda/NuDydW1d7wg

And https://groups.google.com/a/continuum.io/forum/m/#!topic/anaconda/snjfn-ih81I

The fix is manual right now, but will be incorporated in the next release.

Closing this issue. Please reopen if you have further issues.

**Comment by Vivek9876** [comment]
This is complete process. With this step you cat install your Anaconda of any version(not need to download miniconda).

If you are window user or any OS you are using first download Anacond.

first you need to delete all language(java,python etc) variable path which is set via environment variable.

If you are window user then need to off window defender.

After that uninstall all antivirus software(If you using antivirus software you will not get menu ).

And install Anacoda you can install perfectly.100% working
You will get Anconda navigator

**Comment by maneesh25** [comment]
One of the method to solve this problem is follow below steps:
1. Remove all instances of anaconda, python from Windows PC.
2. Install Miniconda.
3. run conda from command line.
    conda install -c anaconda anaconda-navigator
4.  if some library/package you don't find then use pip command to download,
   pip install <package name>
  pip can be found in Miniconda3's Scripts folder.
Hope this solve your problem.
