### ISSUE TITLE
Cannot mix incompatible Qt library 

### ISSUE THREAD

**Issue by zelite** [ContinuumIO/anaconda-issues#676]
I'm on windows 10, with anaconda 2.5.0 64 bits.

I get the message when trying to launch jupyter qt console:

    Cannot mix incompatible Qt library (version 0x40807) with this library (version 0x40804)

I've seen the problem described before but did not see any fix for it.

**Comment by zelite** [comment]
Found some dlls in the windows/sytem32 folder: QtCore4.dll, QtGui4.dll, QtNetwork4.dll. I don't know which program put them there. I moved them out of that folder and now I could start up the qtconsole. Now if only I knew which program put those files there.

Anyway, why can't anaconda handle the qt libraries without caring about these other dlls?

**Comment by ccordoba12** [comment]
This issue is about other Qt installations having more components than our Qt. I mentioned @msarahan about it, since he's the one in charge of Qt on Windows.

I think the only solution is to compile all Qt components, else this problem will continue to show up (at least that's how I fixed this problem on Linux)

**Comment by msarahan** [comment]
I disagree.  I think this is a misunderstanding of how Windows finds DLLs.  The relevant microscoft documentation is at https://msdn.microsoft.com/en-us/library/7d83bc18.aspx

Specifically: things in Windows\System32 will always be found before entries on PATH.

Whoever put 3rd party DLLs into Windows\System32 was being very naughty.  There is no way that we can have Qt as a shared DLL being found before some other Qt in Windows\System32.  In order to do so, we would instead have to copy our Qt DLLs adjacent to any arbitrary thing that uses it (PyQt, PySide, and any other executable installed by Anaconda that uses Qt directly).

The best we can do here is try to put our PATH first (we do this when you activate an environment).  Doing that for the root environment is not advisable, because then we may shadow other libraries.

Closing this issue.  If you have further questions, please reopen or open a new issue.

**Comment by ccordoba12** [comment]
Thanks for the clarification @msarahan!
