### ISSUE TITLE
Cannot create virtualenv with venv module

### ISSUE THREAD

**Issue by fortran-favors-the-old** [ContinuumIO/anaconda-issues#6917]
I receive the following error after attempting to create a virtualenv with the [`venv` module, which is part of the standard library](https://docs.python.org/dev/library/venv.html):

```
[fortran-favors-the-old@mbp] ~ % python -m venv test
Error: Command '['/Users/fortran-favors-the-old/test/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

This happens because the [`ensurepip` module, which is also part of the standard library](https://docs.python.org/dev/library/ensurepip.html), is not included with Anaconda:

```
[fortran-favors-the-old@mbp] ~ % python -m ensurepip
/Users/fortran-favors-the-old/anaconda3/bin/python: No module named ensurepip
```

Please fix this for Python ≥ 3.4 (`ensurepip` was introduced in Python 3.4).  By fixing this, `python -m venv` will be a useful Python-distribution-agnostic way to create virtualenvs, especially on hosts where the `virtualenv` module is unavailable.

For more information, you may be interested in reading [PEP 453 -- Explicit bootstrapping of pip in Python installations](https://www.python.org/dev/peps/pep-0453/), especially the [Recommendations for Downstream Distributors](https://www.python.org/dev/peps/pep-0453/#recommendations-for-downstream-distributors) section.

I'm running macOS 10.11.6 and Anaconda3 5.0.1 (installed from [here](https://repo.continuum.io/archive/Anaconda3-5.0.1-MacOSX-x86_64.sh)).  I didn't modify the environment at all using `conda` or `pip`.

```
[fortran-favors-the-old@mbp] ~ % python --version
Python 3.6.3 :: Anaconda, Inc.
```

**Comment by msarahan** [comment]
We'll see about adding that in somehow.  I think we stripped it out because we do not bundle pip with python (unlike upstream).  Pip is a separate package from Python.  Historically, pip has been automatically added as a dependency (not bundled), but it is important to maintain the ability to install python without pip (so that we can build pip, for example).  What we're not sure about is any dependency ``ensurepip`` might create between python and pip - perhaps ensurepip should actually be installed by the pip package, rather than bundled with python.

I also think you might be missing the key reason why venv/virtualenv/pip and conda environemtns don't play nicely together.  At their cores, there is a fundamental disagreement:

* wheels must contain their compiled shared library dependencies, or be statically linked to them.  They must be self-contained.  I haven't been able to find exact docs specifying this (it's not in the wheel spec), but it is how it plays out in practice.  Auditwheel includes specific tools for this (auditwheel repair).  
* Including shared libraries for dependencies is a total anti-pattern in conda.  Reusing some other package containing those shared libraries is preferred.  This depends much more on the dependency solver (and accurate dependency metadata).  Pip currently lacks the dependency solver.

The pip route leads to the vendoring mentality, and I'm honestly not even sure how well it plays out with shared libraries.  If an incompatible shared library is already loaded by one python extension, it can break another, because Linux at least loads shared libraries by name, not by anything more specific.  Conda prevents this incompatibility at install time.  If things are incompatible, you simply cannot install them together (assuming accurate dependency metadata).

Since you're creating envs, I think the other dangers of mixing conda and virtualenv don't really apply (clobbering files, leaving crap around when stuff is removed).

I feel your pain, trust me.  I wish conda and virtualenv played more nicely together, and this is a long-term goal of ours.  In my opinion, what is fundamentally needed is unification on handling of shared libraries.  The venv/pip/virtualenv world must grow both the ability to have external dependencies for shared libraries, and also a dependency solver to keep things sane.  I believe both projects have been proposed, but I have no idea what the state of either is.  On the conda side, we need to be able to strip shared libraries out of wheels, and replace them instead with metadata pointing at packages to provide those dependencies.

If you deal only with virtualenv/venv for your envs, and you do not mix conda packages and wheels in a single env, you *should* be OK, but there might be some really subtle details that mess things up.

**Comment by fortran-favors-the-old** [comment]
Hi @msarahan , thanks for commenting.

Given that the `ensurepip` module bundles its own copy of `pip` and its dependencies (see [PEP 453's "Implementation strategy" section](https://www.python.org/dev/peps/pep-0453/#implementation-strategy)), compiling Python using `--with-ensurepip=yes` (or whatever this flag should be) shouldn't break anything, introduce any new dependencies, or modify existing functionality in any way.

People who wish to use `conda` can use `conda` as before, people who wish to use `pip` can use `pip` as before.  All this change should do is fix `python -m venv foo`.  I appreciate the information you provided regarding conda envs vs. virtualenvs, but I think this particular issue is orthogonal to that discussion.

**Comment by msarahan** [comment]
Thanks.  That's some nice peace of mind.  Would you be willing to help us test packages?  I can't promise an exact timeline, but we can try to do this by the end of next week.

**Comment by fortran-favors-the-old** [comment]
Sure, happy to help.  When it gets to that point, please feel free to reach out to me here in the comments, or via the email address listed on my GitHub profile.

Thanks for your quick response and willingness to address this.

**Comment by jjhelmus** [comment]
One workaround is to create a venv without pip and then install pip+setuptools via get-pip.py:

```
python -m venv test --without-pip
source test/bin/activate
curl https://bootstrap.pypa.io/get-pip.py | python
```

Not ideal but works with the current version of Python in Anaconda.

**Comment by fortran-favors-the-old** [comment]
Thanks, but that only works if the host has Internet access, which mine does not.  It's common in many industries (such as mine) for production hosts to not have access the public Internet, and just some subset of the corporate intranet.

My goal is to be able to, given any Python distribution (provided by either the system package manager or Anaconda), create a virtualenv and `pip install` wheels or sdists into it from our internal artifact repository (such as [Artifactory](https://www.jfrog.com/confluence/display/RTF/PyPI+Repositories) and [Nexus](https://help.sonatype.com/display/NXRM3/PyPI+Repositories)).  We would prefer to not have to make any assumptions about `pip` or `virtualenv` being available on these systems, especially since `ensurepip` obviates the need to make any such assumption.  ([One of the design goals of `ensurepip` was that it work without Internet access.](https://www.python.org/dev/peps/pep-0453/#security-considerations))

In my case, the system package manager providing Python does not provide the `virtualenv` package, but despite this I can still create a virtualenv via `python -m venv foo`.  I would like to be able to do the same with Anaconda as well so, from a configuration management standpoint, I can just assume that `python -m venv foo` will work, and not have to check if I'm working with system Python or Anaconda Python.

**Comment by fortran-favors-the-old** [comment]
Hi @msarahan , just wanted to follow up and see if you'd still like my help with testing this.

**Comment by msarahan** [comment]
ensurepip has been restored in the packages on defaults:

https://github.com/AnacondaRecipes/python-feedstock/commit/57adaad35f1a97fe818840f8e1d85007e0d1031a

**Comment by fortran-favors-the-old** [comment]
Thanks!

**Comment by ks7000** [comment]
Reading and reading I found this:

> «Conda manages python itself as a package, so that conda update python is possible, in contrast to pip, which only manages Python packages. Conda is available in Anaconda and Miniconda (an easy-to-install download with just Python and conda).»

[https://packaging.python.org/guides/installing-scientific-packages/#the-conda-cross-platform-package-manager](url)
«CONDA MANAGES PYTHON ITSELF AS A PACKAGE...»
_very disturbing for me but well, hands to the keyboard in a terminal window:_

`conda update python`

My result:
![jimmy kevin _2390](https://user-images.githubusercontent.com/9118575/33225946-e4ba25ce-d157-11e7-9cf1-0917bc6b3e4e.jpg)

### Thanks for your attention, have a nice day!

**Comment by mingwandroid** [comment]
@ks7000, the point of your comment is entirely lost on me, can you explain it?

I do not understand why python as a conda package is disturbing, then I see an attempt to use `ensurepip --root` incorrectly, in the form of a screenshot when text would do just as well (actually it would do much better).

**Comment by ks7000** [comment]
Oh, yeah, that's the point:
I am using _ensurepip --root_ without parameters
for denote the complete sintaxis of command,
**you are right**: it does not help, it complicates the thing!

Good suggestion for use only text,
that is a good idea for the search engines,
at this point you are right too, thanks a lot!

**Comment by npandey2385** [comment]
I was also facing the same issue.

[niraj@abc ~]$/python/v3.7.0/bin/python3 -m venv avd
Error: Command '['/home/niraj/avd/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

After adding libffi3.3 on my LD_LIBRARY path it works

setenv LD_LIBRARY_PATH /libffi/v3.3/lib64

**Comment by mingwandroid** [comment]
Please use our virtualenv package instead.
