### ISSUE TITLE
Matplotlib Text Wrap is Broken in Spyder

### ISSUE THREAD

**Issue by nitrocalcite** [ContinuumIO/anaconda-issues#705]
Text wrap doesn't work inside Spyder for some reason.  If you try to run `matplotlib.pyplot.text(x,y,"long string",wrap=True)`, it will run but the wrap doesn't take effect.  If you run the same file from the Anaconda command line, text wrap works fine.  

I've updated all my packages and Spyder as well. 

EDIT:
Spyder also displays matplotlib images different than the command line.  For example, font size 12 is smaller from the command line relative to the image than in Spyder.  Do I have a graphical backend issue?

**Comment by ccordoba12** [comment]
Could you post screenshots to see the differences between in and outside Spyder? Thanks :-)

**Comment by nitrocalcite** [comment]
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/13782231/13799101/b06cfcb2-eaf2-11e5-81c0-4c2a0585d8e7.png)

**Comment by Manyak872** [comment]
Hello, the problem is still actual.
OS - Windows 7. Python version 3.6.1. Matplotlib version 2.1.1. Spyder 3.1.4.
[Source code](https://matplotlib.org/2.0.0/examples/text_labels_and_annotations/autowrap_demo.html).
Text wrap works fine when running through cmd and didn't work correctly when using Spyder.
Screenshot is attached.
Thank you.
![default](https://user-images.githubusercontent.com/11950122/34528863-e913b28c-f0b2-11e7-81fd-268080390497.png)

**Comment by ccordoba12** [comment]
Please report this problem with IPython:

https://github.com/ipython/ipython

This looks like a problem with the inline backend.

**Comment by Daniel-Lopez-Aires** [comment]
Well, sadly this issue is still happening apparently :/ So need to break it manually by putting \n
