### ISSUE TITLE
Suggestions for openblas recipe

### ISSUE THREAD

**Issue by sdrobert** [ContinuumIO/anaconda-issues#7104]
Hi,

This is in response to my [PR](https://github.com/conda/conda-recipes/pull/737) back in the (defunct) conda-recipes repo. The [latest openblas recipe](https://github.com/AnacondaRecipes/openblas-feedstock) does not take into account the following two points. I'm not an expert, so please excuse me if these are foolish.

- As per #739, OSX linking using ``DYLD_*`` is out the window with System Integrity Protection. Under the new toolkit, you can either modify the linkage after the build using ``otool``, or set the RPATH as a linker flag. The former option doesn't really work, however, since the OpenBLAS Makefile implicitly runs the test suite when calling ``make``. I get this wonderful error:
```
dyld: Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/cl_mac/ExternalRepositories/miniconda3/conda-bld/openblas_multipkg_1509754919019/work/test/./sblat2
  Reason: image not found
```
This can be solved by replacing that library block with:
``` bash
export LDFLAGS="-Wl,-rpath,${CONDA_PREFIX}/lib -L${CONDA_PREFIX}/lib ${LDFLAGS}"
```
I think this'll work with older toolchains, too, but it needs testing.

- AFAICT, Jinja templates for versions are useless when the file hash is fixed. However, the hash and the version number can be zipped together in ``conda_build_config.yaml``

Anywho, let me know if anything needs clarification. 

Best,
Sean

**Comment by jjhelmus** [comment]
@sdrobert The improper linking to libgfortran was caused by an incorrect directory being added to `DYLD_FALLBACK_LIBRARY_PATH`.  Previous versions of conda-build would combine the build and host prefixes so that the library could be found in `${PREFIX}/lib`.  With the current conda-build versionthe library is placed in only the build environment so `${BUILD_PREFIX}/lib` needed to be added to the search path.  This has been updated in [1f43cb82](https://github.com/AnacondaRecipes/openblas-feedstock/blob/1f43cb82883f5eb447f5de97b15fdf28e0161160).  

This should work for other toolchains although I have not tested this.

The activation script for the gcc 7.2.0 compilers does add an rpath to argument to `LDFLAGS`. 

I don't understand your comment about adding the hash and version numbers to `conda_build_config.yaml`.  

The version string is templated in the recipe to save space an easy updated.    The hash should not be added to the configuration file, the hash provides information about the tarball and is best associated with the recipe not the configuration file.
