### ISSUE TITLE
'xterm-termite': unknown terminal type after adding Anaconda to PATH

### ISSUE THREAD

**Issue by Drakota** [ContinuumIO/anaconda-issues#7148]
I modified my .zshrc and included PATH=/opt/anaconda/bin:$PATH.
This works, I can use conda commands, but when I'm trying to clear my terminal I get this error 
`'xterm-termite': unknown terminal type`
When I comment the PATH line it works again. 

Why?

**Comment by berndstelzl** [comment]
Good to know i am not the only one... Same on bash.

**Comment by krishnakumarg1984** [comment]
Yes. I am affected by exactly the same issue.

**Comment by Rikorose** [comment]
Same here, I linked xterm-termite as a workaround:
```bash
ln -s /usr/share/terminfo/x/xterm-termite ~/miniconda3/share/terminfo/x/
```

**Comment by jeherr** [comment]
I've been having this same problem on Manjaro i3. From what I have figured out, ncurses is what searches for terminfo on your system. There is a particular order of locations ncurses checks for terminfo, but by default in most linux distros the location should fall back to `/usr/share/terminfo` though on some distros, like solus, this differs a little bit. You can check where your system is searching for terminfo with the command `infocmp -D`. 

When installing anaconda, it seems like it comes with its own ncurses which searches in `~/.terminfo` and `~/anaconda3/share/terminfo` (or whatever your anaconda install directory is). My first solution was to softlink the correct terminfo to `~/.terminfo` but this still left a problem when I ran certain commands with sudo. So I ran `sudo infocmp -D` and noticed that the only search location was `~/anaconda3/share/terminfo`. @Rikorose is correct that making a softlink of the correct terminfo from `/usr/share/terminfo` to `~/anaconda3/share/terminfo` will fix the issue.

I think longer term though, a better solution would be for anaconda to at least fall back on the system default locations of terminfo instead of wiping them out from where ncurses searches for terminfo all together. That way, at least if anaconda does not provide the terminfo for something, at least it can still be found instead of just breaking the behavior of some terminals. I don't really know why anaconda can't rely on the system location terminfo that comes with any distro, I'm sure they had their reasons for deciding to provide their own ncurses and terminfo files, but wouldn't it make more sense to rely on the system terminfo as a fallback at least?

**Comment by mingwandroid** [comment]
> I think longer term though, a better solution would be for anaconda to at
least fall back on the system default locations of terminfo instead of
wiping them out from where ncurses searches for terminfo all togethe

Isn't there a high possibility that the database format will differ on the
end-user's machine though, causing crashes? Are they fully
backwards-compatible?

**Comment by jeherr** [comment]
Compatibility is already broken when anaconda doesn't provide terminfo for a terminal on an end-users system. I don't know enough about ncurses to know whether they are fully backwards-compatible or not. My suspicion is that mostly they would be, but they could have some small breaking changes. I don't know how ncurses handles breaking changes between versions. I guess it depends whether a breaking change would totally crash, or cause some minor broken behavior. My guess is minor broken behavior, since what happened to me and others seems to mostly be things like `clear` not working when the correct terminfo wasn't even found.

I guess my thought was that falling back to the system version of terminfo if anaconda does not come with the correct one, was better than than simply not having the terminfo at all. There's probably an even better solution, but I don't know enough about why anaconda even comes with ncurses in the first place.

**Comment by mingwandroid** [comment]
No it isn't. You are free to change TERM when you need to so please avoid hyperbole.

This 'incompatibility' you speak of is not the hard crashes (potentially exploitable ones too( that I am worried about.

You are not the first person to say recently something along the lines of 'I don't know why anaconda provides X, I want it to use my system one', well this is simply essential. It is due to API and ABI compatibility issues.

To be clear, if we built anaconda against CentOS6's ncurses it *will not work*. ok anything but CentOS6 reliably so we build our own.

We also compile or libs with really good security and performance characteristics that the distros tend to do less well.

This kind of backseat distro engineering is a bit much to be honest.

**Comment by mingwandroid** [comment]
And for further information we actually attempted to use the system database a few years back and it resulted in a huge number of warnings being printed to the console in some distros, again highlighting that things aren't as simple as 'use system stuff', nor as simple as 'mix with system stuff'.

**Comment by jeherr** [comment]
I don't see where this hostility is coming from. Sorry if I "offended" you by asking questions and making suggestions.

> 'I don't know why anaconda provides X, I want it to use my system one'

What I said was

>  I don't really know why anaconda can't rely on the system location terminfo that comes with any distro, I'm sure they had their reasons for deciding to provide their own ncurses and terminfo

No where did I state that anaconda should just use ncurses provided by the distro, I stated that I do not know why it doesn't, and suggested that there was likely a reason why. If you read into that thinking I was bashing ContinuumIO for this choice, then I don't know what to tell you. Maybe try not to assume the tone of internet comments.

> And for further information we actually attempted to use the system database a few years back and it resulted in a huge number of warnings being printed to the console in some distros

Again I never suggested anaconda just use the system database, I suggested that it keep the system database as a fallback.

I also mentioned several times how little I knew about ncurses, in case you didn't catch that, I was showing my hand, that I'm really no expert here. If you thought I was telling you what to do instead of coming here and trying to help other users who faced the same issue as me maybe understand the problem if even just a little bit more, in a thread where nobody from ContinuumIO even bothered to provide a simple answer which they apparently knew off hand, and would have taken you a matter of a minute to answer 9 months ago when the thread was opened, or even 3 months ago when the last user before me posted about their possible solution. I get it, you're probably slammed with all kinds of other work which takes higher priority than coming here and answering issue threads about small things like this. 

Instead you decide it's worth your time when someone comes in to help other users of your product and says "Hey, here's a little help on how you can figure out what is going on and where the terminfo databases are even being searched for." God forbid I pose a suggestion as to a possible alternative, which worked for me and others, being the default without one of ContinuumIO's employees coming here to chastise me for daring to open my mouth.

In spite of all of this, you actually did help me learn more about it. Sincerely, thanks for taking the time to provide some more info.

**Comment by mingwandroid** [comment]
> In spite of all of this, you actually did help me learn more about it. Sincerely, thanks for taking the time to provide some more info.

No problem. You sort of did ask why we bother with ncurses albeit in a inquisitive and polite way but I feel you were still asking basically "why do you provide ncurses at all?". Apologies if I can across a bit sharp. Yesterday someone asked the same regarding Qt and/or GTK. A few issues recently have implied we are doing dumb stuff when in fact that's very far from the truth, I may have been over-sensitized to this general question because of that.

As for why I didn't answer earlier, we have a lot of work to do and issues come in frequently so things will always fall through the cracks, and when deciding what to respond to (as opposed to spending time engineering) personally I'll tend not to answer problems the solution to which seems obvious to me (such as this one; set TERM) or could be solved by using Google Search.

IMHO my time is best spend engineering or answering genuinely tricky (from my perspective) and issues that are unique to AD (because we *are* doing somewhat unusual stuff in order to support a vast range of systems).

**Comment by mingwandroid** [comment]
I explained that we can't use the system terminal info db already though. Even as fallback.

**Comment by j3r1ch0** [comment]
This is probably no longer an issue but I figured I post this here in case anyone else comes across this. First you'll need to run 'infocmp >termite.terminfo' (don't use the quotes). Then you'll need to run 'tic -x termite.terminfo' (again no quotes). People have this problem with termite and ssh all of the time. In that scenario you would also need to copy the termite.terminfo file to the remote host and it would need to be added every time you ssh in. So just like in that scenario, but for different reasons (won't persist across reboots in this case, or other shells), you're going to need to add 'tic -x /path/to/the/termite.terminfo' to your .bashrc/.zshrc/.fishrc, etc., and don't use the quotes. Also, obviously, you're going to want to add the real path to the termite.terminfo file as well.

**Comment by yvan674** [comment]
In case anyone is looking at doing this in Ubuntu 18.04 and termite, the terminfo to link to is at a different location (at least for me) and the command is:

```bash
ln -s /usr/local/share/terminfo/x/xterm-termite ~/miniconda3/share/terminfo/x/
```
