### ISSUE TITLE
R fails on Mac OS X after installing additional libraries

### ISSUE THREAD

**Issue by AntonioJBT** [ContinuumIO/anaconda-issues#7243]
Hi,
Installing R by itself works fine but adding R libraries breaks it with the error:

> dyld: Library not loaded: @rpath/libreadline.6.2.dylib
>   Referenced from: /Users/antoniob/anaconda/envs/r_test/lib/R/lib/libR.dylib
>   Reason: image not found
> Trace/BPT trap: 5`

Similar issues have been raised recently.
(https://github.com/conda/conda/issues/6183) 
(https://github.com/ContinuumIO/anaconda-issues/issues/6312)
(https://github.com/conda/conda/issues/3113)

The solutions seem temporary workarounds or don't work for me.

Running the following recreates my problem on Mac OS X 10.11.6:

```
conda create -n r_test
source activate r_test
conda install -y r
R #works
```

Error:

```
conda install -y r-MatrixEQTL=2.1.1 r-data.table=1.10.4 r-ggplot2=2.2.1
R # errors
```

See conda info and list before and after:

[conda_info_1.txt](https://github.com/ContinuumIO/anaconda-issues/files/1462281/conda_info_1.txt)
[conda_info_2.txt](https://github.com/ContinuumIO/anaconda-issues/files/1462282/conda_info_2.txt)
[conda_list_1.txt](https://github.com/ContinuumIO/anaconda-issues/files/1462283/conda_list_1.txt)
[conda_list_2.txt](https://github.com/ContinuumIO/anaconda-issues/files/1462284/conda_list_2.txt)

I'm not using conda-forge.
Is there a clean fix?
I don't understand the inner workings of conda so any help is appreciated.
Thanks,
Antonio

**Comment by mingwandroid** [comment]
You are not using `conda-forge` but you are using `bioconda` and `cgat`. I guess you added those because you wanted `r-matrixeqtl` or maybe you read somewhere that this was a good idea.

The same as with `conda-forge` you *cannot* mix packages from `defaults` with packages from `bioconda` in the same environment (I don't know what `cgat` is).

`conda list` isn't so useful as a debugging tool, much better is `conda list --show-channel-urls`. If you compare the output before and after you will see that the `defaults` `r-base` got replaced by one from `bioconda` and that's why things do not work for you.

You need to use conda environments instead here to maintain isolation. You can read more at: https://conda.io/docs/user-guide/tasks/manage-environments.html

It is our hope that one day we will be able to reach a state of compatibility with these external endeavours.

**Comment by AntonioJBT** [comment]
Of course, thanks. Some of the packages I need aren't in the `defaults` unfortunately. Sticking to `bioconda` and `conda-forge` avoids this issue.  Thanks for the explanation.
