### ISSUE TITLE
orange version in Navigator is wrong and package version is 18 months old

### ISSUE THREAD

**Issue by ijstokes** [ContinuumIO/anaconda-issues#735]
I am pretty sure that this is with the latest Anaconda

<img width="252" alt="screenshot 2016-04-05 14 12 36" src="https://cloud.githubusercontent.com/assets/293525/14293234/b948210c-fb39-11e5-8690-f60ea505544f.png">

This shows the Orange version as 1.0.  When I start it I can see that it is actually 2.7.8.  When I look here: https://docs.continuum.io/anaconda/pkg-docs I can see that "orange" is 2.7.8 and "orange-app" is 1.0, which seems strange to have orange-app have a different version.

Furthermore, Orange is now at release 3.3, and I think the version we are packaging in Anaconda is 1+ years old (2.7.x).  Is there a reason not to include the more recent version?

**Comment by csoja** [comment]
Thanks for submitting the issue.  Orange is a strange one - it has a
package that works on Python 2.x and a different package that works on
Python 3.5.  The Orange.app is something we created, so that when a user
installed the app using Laucnher - they would get the correct version for
their version of Python (and would not have the confusion of both a Python
2.7 and Python 3.5 Orange showing up in Launcher).  I expect if you are
getting Orange v2.7.8, you have a Python 2.7 root environment. Is this the
case? If you have a Python 3.5 root environment, you should get a more
recent version of Orange (v3.2).

On Tue, Apr 5, 2016 at 1:50 PM, Ian Stokes-Rees <notifications@github.com>
wrote:

> I am pretty sure that this is with the latest Anaconda
>
> [image: screenshot 2016-04-05 14 12 36]
> <https://cloud.githubusercontent.com/assets/293525/14293234/b948210c-fb39-11e5-8690-f60ea505544f.png>
>
> This shows the Orange version as 1.0. When I start it I can see that it is
> actually 2.7.8. When I look here:
> https://docs.continuum.io/anaconda/pkg-docs I can see that "orange" is
> 2.7.8 and "orange-app" is 1.0, which seems strange to have orange-app have
> a different version.
>
> Furthermore, Orange is now at release 3.3, and I think the version we are
> packaging in Anaconda is 1+ years old (2.7.x). Is there a reason not to
> include the more recent version?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuumIO/anaconda-issues/issues/735>
>



-- 
*Crystal Soja*
*Anaconda Distribution Product Manager*

**Comment by goanpeca** [comment]
@ijstokes can we close this after @csoja explanation?
