### ISSUE TITLE
Linker error in root environment but not other environments?

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#7627]
When trying to compile/run scikit-learn with the new compiler packages, I get `` undefined symbol: __cxa_throw_bad_array_new_length`` when I try to do it in my root environment, but it works when I'm doing it in a clean new environment.
That seems somewhat strange to me. I checked that all the packages in the "clean" environment are also available in my root environment.
conda list in my root environment: https://pastebin.com/mgqhH8pL
conda list in an environment in which there is no linking issues: https://pastebin.com/tuST9MS4

conda info:
```
               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.30
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/andy/anaconda3  (writable)
    default environment : /home/andy/anaconda3
       envs directories : /home/andy/anaconda3/envs
                          /home/andy/.conda/envs
          package cache : /home/andy/anaconda3/pkgs
                          /home/andy/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/andy/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.10.0-40-generic debian/stretch/sid glibc/2.24    
                UID:GID : 1000:1000
```

**Comment by mingwandroid** [comment]
I am guessing you did not activate your root environment?

**Comment by amueller** [comment]
I did (otherwise it doesn't compile). I just realized the root environment contains an old "gcc" package which might be the issue?

**Comment by mingwandroid** [comment]
You need to throw away that root env and install something without such legacy cruft.

**Comment by amueller** [comment]
So you're basically saying that there is no way to update an environment that was created before you introduced the new compiler packages? Couldn't you just create conflicts between the new packages and the "legacy cruft" so that updating cleans the environment?

**Comment by mingwandroid** [comment]
We don't have the ability to create 'conflicts' and I am in a position where I cannot remove the old GCC package since people still use it.

**Comment by amueller** [comment]
Removing gcc actually did the trick. It would seem pretty natural to me to uninstall that if someone installs the new compilers.

**Comment by amueller** [comment]
You can't? hm ... I guess you can only create requirements. You could create a new version of the package that is empty and require that. That would break the env of people that rely on it if they update, though... though that's not much worse of breaking people's environment if they try to install a new package....

**Comment by mingwandroid** [comment]
I think it's much worse. Please use envs as they're meant to be used, for the isolation they provide. This is a breaking event we will not have to repeat. Also, we didn't break your environment here, you just ended up in a situation where you cannot compile scipy in your root env because you have old deprecated stuff that I cannot mark as conflicting.

When compiling software you need to be very careful about what compilers are getting used and what shared libraries are getting linked to.

**Comment by amueller** [comment]
ok, thanks. I thought marking something as conflicting is standard in dependency resolution, but maybe it's not. I guess apt has a mechanism of "provides X" that allows for that, but no explicit conflict mechanism.

**Comment by amueller** [comment]
> Please use envs as they're meant to be used, for the isolation they provide.

Can you please elaborate on that? How am I using an env not in the way they are meant to be used? I feel like I'm missing something.

**Comment by mingwandroid** [comment]
When compiling software it is important to have very tight control of:

1. The tools (compilers etc) that are used.
2. The headers that those compilers will find.
3. The libraries that the linker will link to.
4. The libraries that the OS loader will link to when it loads your software (both during your build and finally).

Doing anything else just leaves the end results to chance.

This need for isolation and control has spawned a whole sub-industry (docker/containers), but there are other more primitive ways (e.g. chroot). Conda environments are our way if providing this isolation.

I recommend you use conda-build for any software compilation you need to do as it will manage all this for you. Failing that you could write a simple script to create and activate a conda environment and perform your build in that environment.

**Comment by amueller** [comment]
I understand your points about controlling the environment, but I feel that largely ignores how python environments are used right now. Everybody I know uses pip, and pip doesn't have a clear separation between installing and building. So people end up building in all their environments.

I have not heard of any of the package developers using either workflow you describe to install development packages. I think the standard way to do this is to do ``pip install -e .``, which is I think is incompatible with the workflow you describe.

Is there a write-up of your suggested process somewhere so we can discuss it more widely? This seems like a pretty big disconnect between how you imagine conda environments being used and how they are used in practice, both by users and by developers.

**Comment by mingwandroid** [comment]
I will advise against anything that's harmful to reproducible package and software development and encourage better practices. That some in the python world have a poor grasp of binary compatibility and have spread that to others in bundled up recommended workflows and oblige managers is unfortunate but it doesn't stop it from mattering.

Generally speaking anything that doesn't involve compilation can (by luck rather than design) safely ignore this stuff and not run into serious issues but when compilers are involved it's a different story.

As for how conda should be driven, I think the fact that conda-build exists and is used to build the entire ecosystem is evidence enough that this is how it should be done with conda.

Also, as it stands pip breaks conda environments when it touches any files hardlinked between then and should only be used as a last resort when conda packages are not available (and really in that case developing a recipe and submitting it to conda-forge is the best course of action).

As for the specific thing you have run into I will as GCC Oakland to main and it will be empty with just a warning that you should use the new compilers instead. This would at least have prevented what you ran into (but everything I said about binary compatibility and isolation still stands).

**Comment by amueller** [comment]
I don't think the fact that conda-build exists is evidence enough that that's how it should be done. I think explicitly documenting the issues that arise when combining pip an conda and explaining best practices would be very valuable to the community. You're telling me a lot of things that don't seem to be written down somewhere and that you take for granted, but that I don't think most people are aware of.
