### ISSUE TITLE
Conda upgrade doesn't upgrade legacy environments

### ISSUE THREAD

**Issue by amueller** [ContinuumIO/anaconda-issues#7631]
People report that they can't install the current version of scikit-learn because ``conda upgrade`` doesn't install it: https://github.com/scikit-learn/scikit-learn/issues/10237#issuecomment-349028188

I assume that's because there are no 0.19.1 packages using the old compiler setup. I ran into this issue when trying to upgrade matplotlib.

What's the workaround for this? Are there instructions? It's pretty surprising behavior that ``conda upgrade scikit-learn`` does not upgrade scikit-learn to the newest version.

**Comment by amueller** [comment]
Would it be possible to throw a warning if there's a newer version available as a "new" package with instructions on how to migrate to new packages (basically creating a new environment)? That would encourage users to upgrade their environment. Otherwise they might be tempted (as I was) to do ``conda  install scikit-learn=0.19.1`` and get a mixture of old and new packages.

**Comment by jnothman** [comment]
I think it's very unfortunate that bug fix releases are not propagated to legacy environments too.

**Comment by mingwandroid** [comment]
I told you that you should trash your root env. given what you had in it and how you were trying to use it, that is far from a global statement for what everyone should do.

**Comment by mingwandroid** [comment]
Conda can absolutely have a mix of old and new packages, but when you have a mix of old and new tools and libraries and you then try to use that mix to build software, that's when you should expect problems.

**Comment by mingwandroid** [comment]
to upgrade your `scikit-learn`:

```
conda update conda
conda update scikit-learn
```

**Comment by amueller** [comment]
So upgrading conda should always allow users to upgrade to the new packages?

**Comment by amueller** [comment]
But older versions of conda will not allow installing new packages?

**Comment by msarahan** [comment]
technically, old versions of conda are fine.  With conda version 4.3.27 and up, the new software is automatically made available.  Before that, you'd need to modify condarc's default_channels setting to include https://repo.continuum.io/pkgs/main

but yeah, ``conda update conda`` is a lot easier than telling people to modify condarc.

**Comment by amueller** [comment]
ok, so if that's the recommended solution then that's fine. Though it is a bit unfortunate that that means that some people will be stuck on 0.19.0 until they upgrade conda as @jnothman points out.

**Comment by amueller** [comment]
Are there docs that explain this and best practices of new vs old packages? I'm not sure I understand @mingwandroid's position re mixing old and new. I usually *need* to compile for each conda environment I'm using.

**Comment by msarahan** [comment]
I'm not sure what you mean.  A bug fix release was made to conda, 4.3.27.  We can't and shouldn't modify people's condarc's if they are using older versions of conda.  That's asking for mayhem.

Old stuff was compiled with gcc 4.4, or *maybe* 4.8.  It was built using non-prefixed compilers.  New stuff was built with newer prefixed compilers and more security compiler flags.  It's sometimes possible to mix old software with new stuff, but it's pretty likely to fail for any number of annoying binary incompatibility reasons.  If any shared library in your environment is built with the newer compilers, it's best to have all of the shared libraries in your environment built with the newer compilers.

If you compile with our compilers, your software should be portable across envs, so long as your collection of software is all binary compatible.

**Comment by amueller** [comment]
> I'm not sure what you mean.  A bug fix release was  made to conda, 4.3.27.  We can't and shouldn't modify people's condarc's  if they are using older versions of conda.  That's asking for mayhem.

I understand that. The effect is just unfortunate, given that it means way more people will probably install scikit-learn 0.19.0 instead of scikit-learn 0.19.1 than if the switch didn't happen between these two releases.

And thanks for the input. It would be great to have a somewhere to point people to that run into these problems.

**Comment by rth** [comment]
> technically, old versions of conda are fine. With conda version 4.3.27 and up, the new software is automatically made available. Before that, you'd need to modify condarc's default_channels setting to include https://repo.continuum.io/pkgs/main

I have a very limited understanding of what went into switching from old to new build system, but from a user / package maintainer perspective, it is indeed a bit unfortunate that such a major change takes effect between 4.3.25 and 4.3.27. Most of the software out there currently just has installation instructions with `conda install something`. This means that there is no way of knowing which versions of the software is going to be installed by the user, and that all of these instructions now need to be updated with a `conda update conda`. 

When running conda there is also no warning whatsoever that this is going to happen. Or at least warning that there is a new version of conda available and that users should update on a general basis.

**Comment by mingwandroid** [comment]
Conda auto update itself unless you disable that.

IMHO it should auto update itself before doing any other install or update commands but it doesn't at present.

**Comment by rth** [comment]
For an update, yes, but that doesn't work for a new install...

> IMHO it should auto update itself before doing any other install or update commands but it doesn't at present.

+1

**Comment by mingwandroid** [comment]
> For an update, yes, but that doesn't work for a new install..

Anaconda 5 and above includes conda 4.3.27 or above and Miniconda 4.3.30 includes, err, conda 4.3.30 so new installs are just fine.

Unless you mean a new install using an old installer? That's kind of pointless though.

**Comment by rth** [comment]
> Unless you mean a new install using an old installer? That's kind of pointless though.

Yes, I mean an install of a new package into an environment that uses  conda <4.3.27. For instance,  any system where conda was installed  before 4.3.27 was released  (Sept 2017). 

In the workflow, where you setup conda and then create/delete new envs as needed, the `conda update` is never run, and so conda is never updated, unless manually.

**Comment by mingwandroid** [comment]
Well, not updating your root environment every so often is a very bad idea. You do not get any fixes to the most critical software that is powering your entire `conda` installation.

**Comment by msarahan** [comment]
There is information at https://www.anaconda.com/blog/developer-blog/announcing-the-release-of-anaconda-distribution-5-0/

If there's more specific information you think we should publish, please suggest it.

Keep in mind that we cannot retroactively modify old conda versions to tell people to update them.  If they have an old conda version, and they don't think to update it or don't want to update it, there's really nothing we can do to help them.  This is where you can help us.  Please encourage people to update conda.

**Comment by amueller** [comment]
The document doesn't say that you won't get the newest version of a package unless you update conda. That's a pretty thing imho. Basically when explaining the new channel, it should say in giant red letters

"New packages will only be build in the new channel and the old channel will not be updated any more. You can only install packages from the new channel after updating conda. Consequently, no updated packages will be available to you unless you do so."

The information "we're not building in the old channel any more" is completely missing from the document from what I can see.

Maybe I would also add that it's not recommended to mix old an new packages in the same environment? I'm not entirely sure what the best recommendation here is. From my experience, users use *all* environments to build packages, so saying "it's ok unless you try to build in it" will be confusing to most.

**Comment by amueller** [comment]
I meant environments. I understood your previous advice as "mixing packages is ok unless you use that environment to build things". But maybe I misunderstood.

My question was whether you should advise people to update all packages in an environment once they install one from the new channel or not. They will not install new software from the old channels but they will have environment with packages from old channels in which they want to upgrade some packages.

**Comment by mingwandroid** [comment]
The old stuff and the new stuff are largely compatible, I did fairly extensive tests to make sure I could mix things fairly freely on all OSes and mostly it worked. The times it didn't where more down to switching the recipes to be based on conda-forge's than to do with the new compilers.

However, using the `gcc` package is a special case of badness because it exhibits what we call `stomping` behaviour where it overwrites the newer libstdc++ library with an older one. That's the thing I'll probably fix by making it an empty package in the new `main` channel.

Problem is, I'll doubtless get people complain about that and explaining the very good reasons for any changes that cause people any inconvenience does not seem to work.

**Comment by amueller** [comment]
Ok, so maybe then say that using the old gcc package together with new packages is not a good idea? I mean you're the expert, not me. I just think it would be great if there was concrete suggestions and caveats that were mentioned.

**Comment by mingwandroid** [comment]
OK, see what you think of these recommendations:

1. Do not use any of the old software unless you need to. The new stuff is much faster, more secure and better built. They also aim for compatibility with conda-forge. Reinstall from the latest installers to get a nice clean environment containing only new software.
2. Do not build software in the presence of software that does not need to be there. conda-build makes this happen automatically and is the best way to build (any) software when using the Anaconda distribution. If you really want to use pip instead to build software, create a new conda env. with just what you need with `--copy` to avoid pip breaking conda's hardlinks.
3. Do not use the old GCC package anymore (though if I add an empty one to `main` this advice is not necessary). Use the new ones: `gxx_linux-64` or `gcc_linux-32` or `clangxx_osx-64`, again, conda-build will automate all of this for you and there you can use `{{ compiler('c') }}` when you need a C compiler, `{{ compiler('cxx') }}` when you need a C++ compiler and `{{ compiler('fortran') }}` when you need a fortran compiler.

**Comment by amueller** [comment]
" If you really want to use pip instead to build software, create a new conda env. with just what you need with --copy to avoid pip breaking conda's hardlinks" can you elaborate on that? I'm not sure I follow.

The rest sounds good to me. If possible I would add either to the post about the compilers or any new write-up that you need to update your environment / conda to install new packages and that the old channel is not updated any more.

**Comment by mingwandroid** [comment]
conda's environments are superior to virtualenvs (which are far from virtual) and most other systems' whatever-envs because they use hardlinks. This gives some advantanges:

1. Very fast creation
2. Very good space efficiency as the files are only stored once on your disc (in the package cache).
3. A better level of virtualisation than other ways of doing it because it's harder for code to determine they are being used as they look more like normal files than symlinks (for example).

The 'copies' of all the files from all the packages in all your envs (including the root env) are not actually copies at all, they are directory entries with the same inode value (and inodes are reference counted). Full disclosure: some files need to be modified per-env and we mark those as not being hardlink-able, but they are by far in the minority.

The works great until you use PIP to install a package in such an env that causes it to overwrite one of these hardlinks with a version of that file from the PIP package. When it does that, it does not de-duplicated the inode (by copying it) and instead blindly overwrites the package cache and *all* copies of that file (potentially breaking all of your envs).

This is the single biggest cause of incompatibility between conda and PIP and it's subtle but disastrous (but I think I know how to fix it).

In the meantime, if you are going to use PIP in any conda env. you should create that conda env with `--copy` which prevents it from using hardlinks. But really, you should use conda packages when you can.

**Comment by amueller** [comment]
Wow, I did not realize that was the case. Is that documented somewhere? That seems like a big issue. And for a lot of packages I use there's no conda packages available. I'm pretty sure I don't know of anyone not using conda together with pip for that reason, and I would be surprised if they are aware of that issue.

**Comment by mingwandroid** [comment]
Well, it's been mentioned in various places. Thing is, it *only* matters when there is file clobbering / overlap and that is actually quite rare.

Still I am not trying to downplay it and I have a WIP patch (for PIP) to fix it.

**Comment by amueller** [comment]
I'm also not trying to say the fault is on your side, it's seems just tricky to get the important information out :-/

**Comment by szeitlin** [comment]
I realize this is an old issue but I ran into something stupid on my computer at home, because I hadn't been using it much. 

I recently installed anaconda 5 with the intention of removing my old conda 4.3 after testing if the update would fix the problem I was having. Now I'm noticing that I have old envs under the old path, and the new version of conda does not recognize them, e.g.

```
                         /Users/szeitlin/anaconda/envs/pytorch
                         /Users/szeitlin/anaconda/envs/rosalind
                         /Users/szeitlin/anaconda/envs/tensorflow
                         /Users/szeitlin/anaconda/envs/testenv
                         /Users/szeitlin/anaconda/envs/wandb
base                  *  /Users/szeitlin/anaconda3
keras                    /Users/szeitlin/anaconda3/envs/keras
```

The last 2 are from the new conda install, the ones above are from the old one. 

I don't remember having this problem in the past when I upgraded/reinstalled, presumably because the paths to the envs still had the same names, even if the version of conda changed-? 

What I'd like to do, ideally, is update the old envs, but so far I haven't figured out how to do that, because the current version of conda on my path won't admit they exist. 

My next thought was to export the requirements from one of the older ones, create a new env with the new conda, and delete the old stuff that I don't need anymore. It's not entirely obvious to me what's the best way to do this, given that the new conda doesn't recognize the old envs, so I can't just use the shortname for the env. 

If I'm just not googling correctly for the right fix here, please tell me what to search for-?

**Comment by msarahan** [comment]
You can activate by path:

`conda activate /Users/szeitlin/anaconda/envs/pytorch`

Conda knows about environments using a file in your home folder: ~/.conda/environments.txt

I think your old installation predates that file.

You could hack that file to make your other environments show up. Exporting and creating them again is probably best. Just remember that any conda command usually takes a -n or -p argument for the name or the path, respectively. Specifying the path should help you do whatever you need to do.

**Comment by msarahan** [comment]
Closing issue as sorted. Please open new issues if there are further problems like this.
