### ISSUE TITLE
about anaconda2

### ISSUE THREAD

**Issue by milkpeanut** [ContinuumIO/anaconda-issues#773]
My laptop's system is windows 8.1Pro 64-bit,after I install anaconda2 the begin menu onliy have three choice ,anaconda3 is normal.I also tried 64bit but it just like the picture followed
![qq 20160430232321](https://cloud.githubusercontent.com/assets/18752014/14936905/9c6954de-0f2a-11e6-94dd-ebb1607a69b2.png)
when I open Spyder,it cann't connect to ipython kernel,python work well.
![qq 20160430232647](https://cloud.githubusercontent.com/assets/18752014/14936926/185dc2c8-0f2b-11e6-90d0-ff6254d0b3b8.png)
I install anaconda2 in another laptop with the same syetem but i work normaly.So I guess imaybe the CPU's problem,my laptop is I7-5700HQ,and I try install anaconda2 in  win10(my laptop has two system) has the same problem. I'm sorry my English is not well.QAQ   But I'll be very grateful if someone can solve this problem.thanks!

**Comment by msarahan** [comment]
Python 2, on which Anaconda 2 is based, takes a lot more work to get
unicode right.  Unfortunately, we have not had the time or resources to
make that work.  Please use Anaconda 3, or use a system locale that has
only ASCII characters.

**Comment by milkpeanut** [comment]
@msarahan But I tred in my friend's computer with the same system(windows 8.1Pro 64-bit),anaconda2 work well and the begin menu is the same to anaconda3.

**Comment by milkpeanut** [comment]
python2 can be used in anaconda2,only the ipython kernel cann't connect to anaconda2.

**Comment by milkpeanut** [comment]
[IPKernelApp] CRITICAL | Bad config encountered during initialization:
[IPKernelApp] CRITICAL | Could not decode 'C:\\Users\\\xcb\xd5\xd2\xbb\xc8\xbb\\AppData\\Roaming\\jupyter\\runtime' for unicode trait 'connection_dir' of an IPKernelApp instance.

**Comment by msarahan** [comment]
Yes, that's what a Unicode error looks like.  You can try to raise this
issue with the Jupyter team. Anaconda is only a collection of packages, and
while some of the anaconda maintainers submit small fixes upstream, we are
not often core maintainers of these projects.  Unicode errors like this one
are out of the scope of the anaconda distribution.  The start menu
shortcuts are something we'll try to fix.

Really, though, it will make your life much easier to create a different
user account with only ASCII characters, or switch to python 3.  Otherwise,
you will keep running into this wall with python 2.x.

**Comment by milkpeanut** [comment]
@msarahan thank you very much,I have solved this problem,because I creat a user by chinese when I install the system,after I creat a user only have English letters the anaconda2 is OK.But the anaconda3 is powerful than anaconda2.
