### ISSUE TITLE
Update glueviz package to 0.7.3

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#785]
glueviz 0.7.3 was released last week: https://pypi.python.org/pypi/glueviz - would it be possible to update the conda package?

(side question - is there a repo where I could make pull requests to bump the version myself, to save you time in future? I found https://github.com/ContinuumIO/anaconda-recipes, but I don't see glueviz there?)

**Comment by ccordoba12** [comment]
You should open a pull request for GlueViz in

https://github.com/conda-forge/staged-recipes

That way it'll be quite easy for you to have updated conda packages for the latest version of GlueViz at any time :-)

**Comment by astrofrog** [comment]
@ccordoba12 - great, thanks! Is there a way for me to see the existing recipe that Continuum use for glueviz, or should I start from a blank slate?

**Comment by astrofrog** [comment]
@ccordoba12 - so just to be clear (I was reading up about conda-forge), will glueviz still be available in the default conda channel if we create a feedstock on conda-forge? How will I be able to set up the tokens appropriately? Once the feedstock repo exists, do I then open pull requests directly to that to update versions? (or do I have commit rights to the repo?)

**Comment by astrofrog** [comment]
@ccordoba12 - just for info, I opened a PR here: https://github.com/conda-forge/staged-recipes/pull/592

**Comment by msarahan** [comment]
> will glueviz still be available in the default conda channel?

Yes. Conda forge does not supersede the default channel (but may be configured by users to be higher priority than defaults.)

What is happening is that we are centralizing recipes to conda forge as the canonical recipe host.  Defaults will (over time) use these recipes, but may alter them (to support mkl, for instance), and may build on a different platform (centos 5, rather than conda forge's centos 6) for customer compatibility reasons.

Note that we have posted all current conda recipes for anaconda at HTTPS://github.com/continuumIO/anaconda-recipes. This does not include legacy recipes that have not been converted to conda recipes (about 400 out of about 600 total).

**Comment by astrofrog** [comment]
@msarahan thanks for your reply! So one last question - now that there is for example a glueviz 0.7.3 package in conda-forge, does that mean that you will automatically pick this up soon and update glueviz to 0.7.3 in the default channel too? Do you need to be notified of updates, or do you have an automated workflow?

**Comment by msarahan** [comment]
There is no automation right now.  We are in the process of creating scripts that will automate pulling recipes from conda-forge.  However, the running of those scripts will likely always be a manual task, because we need to maintain some opportunity for review in the update process.

What potentially might achieve the same end for you is that we are working towards the free edition of Anaconda shipping with the conda-forge channel enabled in the next release.  You will not need to depend strictly on defaults.  Defaults will still provide an important role to people who need builds compatible with CentOS 5, or other corporate guarantees.  It is also important in filling gaps until the community effort builds out the ecosystem.

**Comment by astrofrog** [comment]
@msarahan - ah, great to know that you will be defaulting to including the ``conda-forge`` channel! That would indeed essentially solve my problem. Just out of curiosity, will this be the case for Miniconda too, or just Anaconda?

**Comment by msarahan** [comment]
Both - it may be implemented in conda, rather than in the installer itself.  That remains to be seen.  Conda currently has defaults for channels when no such setting exists in .condarc.  The change would either be to add to that behavior (change conda), or create a default condarc (installer).

CC @kalefranz

**Comment by csoja** [comment]
Closing as glueviz is at 0.10.4 in the repo at this point.  Also, as to the side question - we are now (as of Anaconda 5.0) forking the conda-forge recipes directly as the base for the recipes we use to build our packages for Anaconda.

**Comment by astrofrog** [comment]
@csoja - just to check, does this mean that you will automatically update versions when conda-forge is updated?
