### ISSUE TITLE
ImportError: No module named sip

### ISSUE THREAD

**Issue by alefnula** [ContinuumIO/anaconda-issues#8]
Installation: Anaconda-1.6.1-MacOSX-x86_64.pkg

Apparently `sip` is not packaged with `pyside` package, so when I run `ipython qtconsole` and try `%pylab qt` or just run the full command line: `ipython qtconsole --pylab=qt` I get the following exception:

```python
/Users/viktor/anaconda/lib/python2.7/site-packages/matplotlib/backends/qt4_compat.py in <module>()
     34 # Now perform the imports.
     35 if QT_API in (QT_API_PYQT, QT_API_PYQTv2):
---> 36     import sip
     37     if QT_API == QT_API_PYQTv2:
     38         if QT_API_ENV == 'pyqt':

ImportError: No module named sip
```

**Comment by drevicko** [comment]
I just encountered this issue on osx with anaconda3 2.4.1. 
anaconda didn't install pyside, but it's specified in ~/.matplotlib/.matplotlibrc, so matplotlib fails to import.
One solution would be to include pyside in anaconda?

**Comment by msarahan** [comment]
Pyside is not nearly as well-developed as PyQt.  Unless you are constrained by license requirements and are unable to use PyQt, we strongly recommend PyQt.  PyQt is included with Anaconda.  PySide is available as an add-on package:

    conda install pyside

**Comment by drevicko** [comment]
I don't think you should close this issue, as it affects people with a default anaconda install: matplotlib doesn't work, which is pretty fundamental. The beauty and attraction of anaconda is that it "just works" - but in this case it doesn't...

I'm not sure what can/should be done, but at least some sort of warning would be in order. Or perhaps matplotlib for anaconda could be coerced into looking in the anaconda folder somewhere to find it's matplotlibrc, and build a new one there fitting the anaconda install.

**Comment by msarahan** [comment]
Thanks for your concern.  Anaconda "just works" much of the time because it controls much of the system.  Your issue gets into config files that are created by packages.  These are just hard to keep track of in the general case.  I feel like documenting the solution in several easy to find places is a better solution than trying to detect all possible problems across all possible upgrade paths.  This particular issue with matplotlib might be relatively easy, but I don't want to commit anyone to expanding this over time.

What we might reasonably support would be a quick and easy way to clear config files to restore systems to a clean state, with a backup feature so that we aren't just blowing away everyone's stuff.  If you agree with this approach, please create a new issue.
