### ISSUE TITLE
Include python-dbg in Anaconda distribution

### ISSUE THREAD

**Issue by parautenbach** [ContinuumIO/anaconda-issues#80]
We are trying to debug a segmentation fault while running unit tests with nosetests on Anaconda. For that, we require python-dbg. This is available to the system Python (for us, under Ubuntu 12.04). One can compile this python-dbg yourself with the correct flags, but we deem it an error-prone and large task to compile Anaconda and all its dependencies ourself. Would it be possible to include this executable in the Anaconda distribution?

We'd be willing to try any suggestions, if any.

**Comment by csoja** [comment]
@ilanschnell I believe this has been done for some time and we can close this issue?

**Comment by ilanschnell** [comment]
No, this has not been done, I don't consider it an issue either.

**Comment by leifwalsh** [comment]
I do consider this an issue, not being able to use gdb on python programs significantly hampers usability from a developer perspective.  Will you consider reopening it, or justify why you don't consider it an issue?

**Comment by mcgibbon** [comment]
Somewhat related to this issue: https://github.com/conda/conda/issues/5780

**Comment by msarahan** [comment]
This is available if you conda-install it as an add-on after installing Anaconda.  We can't include it in the primary Anaconda installer for space reasons.  You do need network access to conda-install python-dbg, or you need some scheme for a locally-hosted channel.

**Comment by msarahan** [comment]
PS: there are two very different things here (on windows):

1. .pdb files, which provide debugging capability.  We can, and do ship these on Windows.  We can think about not stripping binaries on other platforms so that these might be available.
2. debug builds, which do not do any optimization.

The latter is a much bigger thing to ask for.  It may be possible in the future with coming conda and conda-build features (building package variants and the ability to select variants at install time) to build debug versions of many programs and libraries.  This also depends on a much more automated system than we have right now, to deal with the additional builds required.  We're working on that.

**Comment by mcgibbon** [comment]
When you say "provide debugging capability", do you mean as in [this guide](http://cython.readthedocs.io/en/latest/src/userguide/debugging.html)?

**Comment by msarahan** [comment]
Sorry, I have no idea exactly what this requires (perhaps our own gdb build?) and also no time to investigate this with any depth.  If anyone is willing to figure out exactly what we need to do to support this, I'd gladly investigate and work on integrating it into our provided packages.

**Comment by mcgibbon** [comment]
I'm also not entirely sure what it requires, but it seems to have been implemented already in the "debug" package. However, it is broken, resulting in [this issue](https://github.com/conda/conda/issues/5780). At the least I know it breaks numpy and conda. It seems to completely replace "python" with "python-dbg", rather than give a python-dbg binary, based on the behavior I got (no python-dbg and the behavior of python and ipython changed), but I'm not entirely sure.

**Comment by rainwoodman** [comment]
a full python debug build is binary incompatible because two additional fields are added to PyObject. But what about a partial debug build (e.g. a debug-info builde) that includes all of the symbols and disable the optimizations? From the discussion here it appears the debug-info is really the most relevant issue.

**Comment by rainwoodman** [comment]
@mcgibbon : why do you say the `debug` package is relevant to python-debug / python-dbg?

**Comment by mcgibbon** [comment]
@rainwoodman I don't really know what I'm talking about, but as far as I could tell the "debug" package was supposed to install python-debug. I could be wrong. All it seems to do is replace the Python binary, but with what I can't say for sure (I guess it could be something other than python-debug).

**Comment by mcgibbon** [comment]
@rainwoodman the `debug` package also broke many other packages for me, to the point that "conda" couldn't run, so the idea that `debug` is putting in python-debug and the idea that python-debug is binary incompatible might not be mutually exclusive.

**Comment by mingwandroid** [comment]
You can of course build your own debug-symbol-containing Python using our recipes (minor modifications will be needed). If you do those modifications cleanly in a way that is easy to disable I would have no issue with merging them. You could even use split packages so the debug symbols get put in a separate package, and I would definitely support releasing that on the default channel.

Full Py_DEBUG builds of all Python packages are not something we can handle at present due to the combinatorial explosion due to binary incompatibility. Maybe in future we'll be able to go there.

**Comment by rainwoodman** [comment]
I think this file may have killed all debugging information in the current python package from anaconda. Currently I only see function names when python is loaded in gdb.

https://github.com/AnacondaRecipes/python-feedstock/blob/bdee59bab73daeb7fa284a94f23ad64f46e4ea52/recipe/0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch#L1

On Linux can we achieve a similar file size reduction with -g build + strip?

**Comment by bombs-kim** [comment]
I succeed to install python-dbg in my conda environment. Here is how I did it.
https://gist.github.com/bombs-kim/c9848c2b09962f2fd753b48b6d2cd87f

**Comment by nikhilweee** [comment]
@bombs-kim has the process changed in 4 years? I would really like if there were an easier way to install python-dbg with conda.
