### ISSUE TITLE
Failed to create ( add ) Anaconda menus (to the system)

### ISSUE THREAD

**Issue by danielraz3** [ContinuumIO/anaconda-issues#8112]
Hey, 
i'm trying to install anaconda2 python 2.7 but towards the end of the process, I get a failure message.

I tried changing the path, installing as admin and uninstalling again and again but nothing seems to work!

Any thoughts? 

![image](https://user-images.githubusercontent.com/16850674/34870593-3fa82394-f793-11e7-85a7-49ce9e93524b.png)

**Comment by v-zhuravlev** [comment]
same problem. Win 7 x64:

![image](https://user-images.githubusercontent.com/14870891/35781801-e44ddf32-09ff-11e8-87e4-c94bbb751975.png)

**Comment by v-zhuravlev** [comment]
it was cyrilic in the Path. (C:\users\zhuravlev\Рабочий стол) I had to to rename that to `Desktop` via regedit.
Mind though that since it's a localized windows version - this was named like that (Рабочий стол) automatically by OS, it wasn't my intention :)
Once I've done that - I reinstalled Anaconda2-5.0.1-Windows-x86_64 and everything went smooth after few days.

**Comment by msarahan** [comment]
please see #3488 for more discussion and some workarounds that other users have found.  The conflicting DLLs in PATH or cyrillic/non-ascii characters in install paths definitely seem to be the culprits, and we're working on addressing that for the next release.

Closing as duplicate.
