### ISSUE TITLE
Please update git

### ISSUE THREAD

**Issue by dhirschfeld** [ContinuumIO/anaconda-issues#9125]
...as the latest version has an important (for me) bug-fix!

Just posting here as I'm not sure if AnacondaRecipes is being actively monitored?

https://github.com/AnacondaRecipes/git-feedstock/pull/3

**Comment by msarahan** [comment]
Thanks @dhirschfeld.  We realized that we were not being automatically subscribed to the feedstock repos.  We have addressed that, and should be more responsive in the future.  We'll incorporate your PR and have new git out soon.  Thanks.

**Comment by msarahan** [comment]
There's been a problem building this on our build system.  It may take some time before I can debug it.  It is linking to the system Tk on OSX, even though the conda one is available.  There's suspicious log message that indicate link library locations are going wrong:

```
ld: warning: directory not found for option '-L/opt/concourse/worker/volumes/live/e53ad1a1-d29d-4c82-7216-2611a9f2aa91/volume/git_1523306801822/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/lib'
```

lib is getting doubled up somehow.

**Comment by mingwandroid** [comment]
I'm looking at it now.

**Comment by mingwandroid** [comment]
The system TK gets dragged in due to: https://github.com/git/git/blob/master/git-gui/Makefile#L106-L115, yes, it really does just copy Wish from the sysroot.

We either need to whitelist this DSO, disable git-gui or ensure we always build on the lowest version of macOS we support (and potentially suffer future binary incompat. when Apple changes their TK).

The lib/lib thing looks like a bug in Git's make stuff, but not one that's causing us trouble here.

**Comment by dhirschfeld** [comment]
Thanks for taking a look @msarahan & @mingwandroid!

Sounds like a bit of a nasty dilemma :| I'll let you decide the best way forward. I'm happy enough to wait - I just thought I'd put in a PR on the off-chance that everything Just Worked.

**Comment by msarahan** [comment]
Done, thanks @dhirschfeld and @mingwandroid
