### ISSUE TITLE
Keras depends on tensorflow, rather than tensorflow-base

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#9483]
The `keras` package has a dependency on `tensorflow`. Tensorflow has been refactored into `tensorflow-base` and `tensorflow-tensorboard` some time ago (version 1.3, iirc). The dependency on the full `tensorflow` package pulls in Tensorboard, which depends on backlevel versions of `bleach` and `html5lib`.

Would it be possible to switch the `keras` dependency from `tensorflow` to `tensorflow-base`? Or to introduce a new package `keras-base` that depends on `tensorflow-base` instead? The latter would avoid compatibility issues if somebody still wants to use Keras with Tensorflow < 1.3.

The same problem and request applies to `keras-gpu`, which depends on `tensorflow-gpu` rather than `tensorflow-gpu-base`.

**Comment by jjhelmus** [comment]
Although `tensorboard` or `tensorflow-tensoboard` are not required for `keras` I would prefer to keep the `tensorflow` requirement rather than changing to `tensorflow-base`.  I expect some (most?) users will want `tensorboard` installed whenever `tensorflow-base` is installed as this is the behavior when pip installing tensorflow.

Keras can use a number of backends and does not strictly **require** Tensorflow at all.  Would providing a `keras-base` package with no requirement on `tensorflow` be reasonable?  With this package you would be able to install `tensorflow-base` or a different backend.

**Comment by rolweber** [comment]
Yes, a `keras-base` without any `tensorflow` dependency would also address my issue :-)

**Comment by rolweber** [comment]
When `keras-base` does not depend on any backend, there is no need for a `keras-gpu-base` either. And both `keras` and `keras-gpu` can depend on `keras-base`. The more I think about it, the more I like it :-)

**Comment by jjhelmus** [comment]
keras 2.2.0 was released yesterday, I'll create `keras-base` and `keras` packages for this release early next week.

**Comment by jjhelmus** [comment]
`keras-base` version 2.2.0 packages are now available which allow keras to the installed without tensorboard (or any backend).  The `keras` package will still pull in `tensorflow` and in turn `tensorboard` as will `keras-gpu`.

**Comment by rolweber** [comment]
Thanks a lot!
