### ISSUE TITLE
asn1crypto-0.24.0-py_1 not indexed

### ISSUE THREAD

**Issue by Bezier89** [ContinuumIO/anaconda-issues#9940]
Note: this is on the conda-forge channel.

You can see that [the noarch repodata](https://conda.anaconda.org/conda-forge/noarch/repodata.json) does not contain asn1crypto, even though there is a noarch package listed [here](https://anaconda.org/conda-forge/asn1crypto/files).

Presumably it used to be indexed, since I managed to get an environment with this package in the first place. However, now when I try to create the environment, I get this error:

```
ResolvePackageNotFound:
  - asn1crypto==0.24.0=py_1
```

**Comment by jjhelmus** [comment]
In the future please raise issues related to conda-forge packages in the appropriate [conda-forge feedstock](https://github.com/conda-forge/asn1crypto-feedstock).  

It looks like the noarch asn1crypto-0.24.0-py_1.tar.bz2 package was moved to the **broken** label, likely because it was found to be causing issues for users.  Therefore it will not show up in the standard noarch repodata.  It does show up in the [broken label repodata](https://conda.anaconda.org/conda-forge/label/broken/noarch/repodata.json) which can be accessed by adding the channel using `-c conda-forge/label/broken`.  I would not recommend using this package given that it is labeled as broken.

**Comment by Bezier89** [comment]
Got it. Thanks @jjhelmus
